// Original game rules inspired by the sourced traditions in the lore codex.
// These numbers and fictional realms are design choices, not religious claims.
export const TRAIT_RULESET='mythic-traits-v1';
const city=(yields,when={},count=null,cap=1)=>({yields,when,count,cap});
const combat=(amount,when={})=>({amount,when});
const trait=(name,summary,weakness,loreBasis,cityRules=[],combatRules=[],movement=null,healing=null)=>({name,summary,weakness,loreBasis,cityRules,combatRules,movement,healing});
export const FACTION_TRAITS=Object.freeze({
 gondor:trait('Heavenly Watch','Walled cities gain +2 culture. Guards and heroes gain +5 strength on friendly city tiles.','Benefits require walls and a city position; open-field strength is ordinary.','Michael leads the heavenly host against the dragon in Revelation 12.',[city({culture:2},{building:'walls'})],[combat(5,{kinds:['warrior','hero'],friendlyCity:true})]),
 rohan:trait('The Solar Course','Cities beside rivers gain +2 food; riders gain +4 strength on open grassland.','Dry settlements and rough-ground cavalry receive no advantage.','Ra is a solar deity whose daily passage orders the world.',[city({food:2},{river:true})],[combat(4,{kinds:['rider'],terrain:'grass'})]),
 elves:trait('Wisdom and the Citadel','Lore Quarters add +2 production when a Guard Hall is present. Guards gain +4 strength beside a friendly hero.','Requires civic investment and a compact formation.','Athena combines skilled craft, strategic warfare, and civic protection.',[city({production:2},{district:'campus',building:'barracks'})],[combat(4,{kinds:['warrior'],nearHero:true})]),
 mordor:trait('Hammer and Hearth','Forge Quarters beside hills add +2 production. Heroes gain +5 strength on hills.','Flat terrain and settlements without a forge lose the advantage.','Thor wields Mjolnir and protects the community from hostile giants.',[city({production:2},{district:'forge',adjacent:'hills'})],[combat(5,{kinds:['hero'],terrain:'hills'})]),
 zeus:trait('The High Assembly','Sanctuaries beside mountains add +2 culture. Heroes gain +4 strength while guarding friendly territory.','Authority is strongest at home; expeditions get no strength bonus.','Zeus is associated with divine kingship, assembly, and the heights of Olympus.',[city({culture:2},{district:'sanctuary',adjacent:'mountain'})],[combat(4,{kinds:['hero'],ownLand:true})]),
 vishnu:trait('Preservation','Cities at peace gain +1 food and +1 culture. Resting companies on friendly land heal 6 extra health.','War removes the city bonus; healing still requires resting at home.','Vishnu preserves cosmic order, including rescuing the earth as Varaha.',[city({food:1,culture:1},{peace:true})],[],null,{amount:6,when:{ownLand:true}}),
 poseidon:trait('Sea and Horse','Coastal cities gain +2 gold. Riders cross hills for 1 movement point.','Inland economies lose the benefit; riders still cannot cross water or mountains.','Poseidon is associated with the sea, earthquakes, and horses.',[city({gold:2},{adjacent:'water'})],[],{kinds:['rider'],terrain:'hills'},null),
 demeter:trait('The Cultivated Field','Each nearby owned farm adds +1 food, up to +3. Cities training settlers lose 1 production.','Farm investment is required, and expansion takes longer.','Demeter is associated with grain cultivation and the seasonal harvest.',[city({food:1},{},'farm',3),city({production:-1},{queue:'settler'})]),
 inanna:trait('Star of Court and Battle','Sanctuaries add +2 gold during peace. Heroes gain +5 strength in foreign territory.','War suspends court income; home defense has ordinary strength.','Inanna combines aspects of political power, love, and warfare.',[city({gold:2},{district:'sanctuary',peace:true})],[combat(5,{kinds:['hero'],foreignLand:true})]),
 artemis:trait('The Uncut Grove','Cities gain +1 food per adjacent untouched forest, up to +2. Archers cross forests for 1 movement.','Lumber mills remove the harvest bonus; open ground offers no mobility edge.','Artemis is associated with the hunt and wild places.',[city({food:1},{},'untouchedForest',2)],[],{kinds:['archer'],terrain:'forest'}),
 shiva:trait('The Turning Dance','Forge cities gain +2 culture but lose 1 food. Wounded heroes below half health gain +6 strength.','Industry slows growth, and the combat benefit requires a vulnerable hero.','Shiva Nataraja expresses cycles of creation and destruction through dance.',[city({culture:2,food:-1},{district:'forge'})],[combat(6,{kinds:['hero'],wounded:true})]),
 oshun:trait('River Covenant','River cities with a Sanctuary gain +2 food and +1 gold.','Requires both river geography and a Sanctuary; dry cities gain nothing.','Oshun is associated with river waters, fertility, and the Osogbo covenant.',[city({food:2,gold:1},{river:true,district:'sanctuary'})]),
 ogun:trait('The Iron Road','Owned mines add +1 production per city, up to +2. Builders cross forests for 1 movement.','Requires Stonecraft and mines; builders remain vulnerable civilians.','Ogun is associated with iron, tools, and the opening of paths.',[city({production:1},{},'mine',2)],[],{kinds:['builder'],terrain:'forest'}),
 hermes:trait('Crossroads','Trade Quarters add +1 gold per distinct neighboring resource type, up to +3. Settlers cross hills for 1 movement.','A resource-poor market gains nothing; mobile settlers need escorts.','Hermes is associated with travelers, exchange, and crossings.',[city({gold:1},{district:'market'},'resourceKinds',3)],[],{kinds:['settler'],terrain:'hills'}),
 brahma:trait('Fourfold Foundation','Cities of population 3 or less gain +2 production. Four-district cities gain +2 science.','The early benefit ends at population 4; the late benefit needs every district.','Brahma is a creator deity represented with four faces and linked to sacred learning.',[city({production:2},{small:true}),city({science:2},{districtCount:4})]),
 dagda:trait('The Welcoming Cauldron','Storehouses add +2 food. Sanctuaries in cities with a Trade Quarter add +1 culture.','Benefits depend on buildings; there is no military advantage.','The Dagda is associated with hospitality, the cauldron, and music.',[city({food:2},{building:'granary'}),city({culture:1},{district:'sanctuary',otherDistrict:'market'})]),
 susanoo:trait('Storm and Deliverance','Heroes gain +5 strength on river tiles. River cities gain +2 culture when at peace.','Leaving the river removes the strength bonus; war removes the civic benefit.','Susanoo defeats Yamata no Orochi and is associated with turbulent episodes and poetry.',[city({culture:2},{river:true,peace:true})],[combat(5,{kinds:['hero'],river:true})]),
 inari:trait('Rice and Livelihood','Each owned farm adds +1 gold, up to +2 per city. A river Trade Quarter adds +1 food.','Needs improved land; fox imagery represents messengers rather than a fox deity.','Inari is associated with rice, livelihood, and commercial prosperity.',[city({gold:1},{},'farm',2),city({food:1},{river:true,district:'market'})]),
 enki:trait('Waters of Knowledge','River Lore Quarters add +3 science but cost 1 gold per turn.','Research depends on rivers and a paid scholarly district.','Enki/Ea is associated with wisdom and subterranean fresh waters.',[city({science:3,gold:-1},{river:true,district:'campus'})]),
 lugh:trait('Many Arts','Cities gain +1 production for each pair of different districts, up to +2. Heroes beside a builder gain +4 strength.','Needs diverse investment; keeping a civilian near battle is risky.','Lugh gains admission through mastery of many arts and skills.',[city({production:1},{},'districtPairs',2)],[combat(4,{kinds:['hero'],nearBuilder:true})]),
 saraswati:trait('Learning and Music','Lore Quarters add +2 culture; a Sanctuary adds +1 science when a Lore Quarter is present.','Both paths need scholarly investment; there is no combat benefit.','Saraswati is associated with knowledge, speech, and music.',[city({culture:2},{district:'campus'}),city({science:1},{district:'campus',otherDistrict:'sanctuary'})]),
 amaterasu:trait('Return of the Light','Peaceful cities with Storehouses gain +2 production. Heroes at full health gain +3 strength.','War or injury switches off the corresponding advantage.','Amaterasu is linked to sunlight, rice cultivation, and weaving in Shinto accounts.',[city({production:2},{peace:true,building:'granary'})],[combat(3,{kinds:['hero'],fullHealth:true})]),
 quetzalcoatl:trait('Breath and Maize','Lore Quarters add +1 science per owned farm, up to +2. Settlers cross forests for 1 movement.','Learning needs cultivated land; settlers receive no combat protection.','Quetzalcoatl is associated with wind, humanity, and maize traditions.',[city({science:1},{district:'campus'},'farm',2)],[],{kinds:['settler'],terrain:'forest'}),
 osiris:trait('Reed and Renewal','River Storehouses add +3 food. Resting heroes below half health recover 4 extra health.','Settlements need both a river and Storehouses; renewal does not resurrect defeated units.','Osiris is connected with regeneration, kingship, and the afterlife.',[city({food:3},{river:true,building:'granary'})],[],null,{amount:4,when:{kinds:['hero'],wounded:true}}),
 isis:trait('Winged Protection','Cities with a resident hero gain +2 science. Resting companies beside a friendly hero heal 5 extra health.','Keeping the hero near home limits exploration; separated units heal normally.','Isis is associated with protective magic and the restoration of Osiris.',[city({science:2},{heroPresent:true})],[],null,{amount:5,when:{nearHero:true}}),
 horus:trait('The Falcon Throne','The original capital gains +2 production while it has a Guard Hall. Riders gain +4 strength on friendly territory.','The workshop bonus is confined to the original capital; invasions lose the rider bonus.','Horus is associated with falcon imagery and royal authority.',[city({production:2},{capital:true,building:'barracks'})],[combat(4,{kinds:['rider'],ownLand:true})]),
 lakshmi:trait('Lotus Prosperity','Cities with both Storehouses and a Trade Quarter gain +2 gold and +1 food.','Prosperity requires two investments and gives no early battlefield advantage.','Lakshmi is associated with prosperity, abundance, and auspiciousness.',[city({gold:2,food:1},{building:'granary',district:'market'})]),
 marduk:trait('The Ordered City','Walled cities gain +1 production per district, up to +3, but lose 1 gold.','Walls and diverse districts are costly; each fortified city has an upkeep tradeoff.','Marduk is Babylon’s patron and a figure of kingship and cosmic ordering.',[city({production:1},{building:'walls'},'districts',3),city({gold:-1},{building:'walls'})]),
 thoth:trait('The Scribe’s Reckoning','Lore Quarters add +1 science per known civic, up to +3, and cost 1 gold.','Scientific growth requires civic learning and sustained funding.','Thoth is associated with writing, reckoning, and learned knowledge.',[city({science:1},{district:'campus'},'civics',3),city({gold:-1},{district:'campus'})]),
 durga:trait('The Protected Threshold','Heroes gain +6 strength on friendly territory below half health. Sanctuaries with a Guard Hall add +2 culture.','The strongest defense requires an injured hero; foreign campaigns get no bonus.','Durga defeats Mahishasura and is associated with protective divine force.',[city({culture:2},{district:'sanctuary',building:'barracks'})],[combat(6,{kinds:['hero'],ownLand:true,wounded:true})]),
 viracocha:trait('First Foundations','Cities training builders gain +3 production. Builders cross hills for 1 movement.','Production helps only builders; armies and wonders train at ordinary speed.','Viracocha is associated with creation and journeys through the Andean world.',[city({production:3},{queue:'builder'})],[],{kinds:['builder'],terrain:'hills'}),
 nezha:trait('Fire Wheels','Heroes cross hills for 1 movement and gain +4 strength on unclaimed land.','Claims remove the strength bonus; rough forests still slow the hero.','Nezha is depicted with fire wheels and protective martial attributes.',[],[combat(4,{kinds:['hero'],neutralLand:true})],{kinds:['hero'],terrain:'hills'}),
 shango:trait('Thunder and Judgment','Heroes gain +5 strength when beside an allied guard. Guard Hall cities gain +2 culture during war.','Needs a supporting formation; civic advantage ends with war.','Shango is associated with thunder and traditions examining royal power.',[city({culture:2},{building:'barracks',war:true})],[combat(5,{kinds:['hero'],nearGuard:true})]),
 tlaloc:trait('Rain and Hail','River cities gain +1 food per adjacent hill, up to +3, but lose 1 production.','Water sustains growth at the expense of industry; flat riverbanks benefit less.','Tlaloc is associated with life-giving rain and dangerous storms or hail.',[city({food:1},{river:true},'hills',3),city({production:-1},{river:true})]),
 odin:trait('Raven Knowledge','Heroes see one hex farther. Lore Quarters add +2 science while at war.','The research advantage requires war; vision does not permit impossible movement.','Odin pursues knowledge and is accompanied by the ravens Huginn and Muninn.',[city({science:2},{district:'campus',war:true})]),
 freyja:trait('Gold and the Chosen','Trade Quarters add +2 culture. Archers below half health gain +4 strength.','Wounded archers are fragile; market investment is needed for culture.','Freyja is associated with precious adornment and a share of the battle-slain.',[city({culture:2},{district:'market'})],[combat(4,{kinds:['archer'],wounded:true})]),
 freyr:trait('Peaceful Plenty','Peaceful cities gain +1 food per adjacent untouched forest, up to +3.','War or lumber mills remove the benefit; peace offers no strength advantage.','Freyr is associated with fertility, prosperity, and peace.',[city({food:1},{peace:true},'untouchedForest',3)]),
 maui:trait('A Longer Day','Coastal cities training civilian companies gain +2 production. Heroes cross forests for 1 movement.','The coastal bonus applies only to builders and settlers; water remains impassable.','Māori Māui traditions include fishing up land and slowing the sun.',[city({production:2},{adjacent:'water',civilianQueue:true})],[],{kinds:['hero'],terrain:'forest'}),
 kukulkan:trait('Feathered Horizon','Lore Quarters beside mountains add +2 culture. Archers gain +4 strength on hills.','Needs highland geography and research investment; lowland archers are ordinary.','Kukulkan is the feathered serpent of Yucatec Maya traditions.',[city({culture:2},{district:'campus',adjacent:'mountain'})],[combat(4,{kinds:['archer'],terrain:'hills'})]),
 guanyin:trait('Compassionate Refuge','Peaceful Sanctuary cities gain +2 food. Resting civilian companies heal 6 extra health.','War removes the food advantage; no combat strength is granted.','Guanyin is the Buddhist bodhisattva of compassion and rescue.',[city({food:2},{district:'sanctuary',peace:true})],[],null,{amount:6,when:{kinds:['builder','settler']}}),
 brigid:trait('Threefold Craft','Cities with a Forge Quarter and Sanctuary gain +2 science. Resting builders recover 6 extra health.','The research advantage needs two districts; builders remain noncombatants.','Irish Brigid traditions connect poetry, healing, and smithcraft.',[city({science:2},{district:'forge',otherDistrict:'sanctuary'})],[],null,{amount:6,when:{kinds:['builder']}}),
 tangaroa:trait('Gifts of the Sea','Coastal Trade Quarters gain +1 gold per adjacent water tile, up to +3.','Strong ports depend on coast and trade investment; inland cities gain nothing.','Māori Tangaroa traditions connect the sea and relationships of reciprocity.',[city({gold:1},{district:'market'},'water',3)]),
 skadi:trait('The Mountain Hunt','Archers cross hills for 1 movement. Cities beside mountains gain +2 food with a Guard Hall.','The harvest bonus needs a highland hunting base; forests still slow archers.','Skadi is associated with mountains, hunting, and winter travel.',[city({food:2},{adjacent:'mountain',building:'barracks'})],[],{kinds:['archer'],terrain:'hills'}),
 gabriel:trait('The Herald’s Road','Settlers see one hex farther. Newly small cities gain +2 culture while at peace.','Growth beyond population 3 or war ends the city bonus; settlers need protection.','Gabriel delivers divine messages in the biblical annunciation accounts.',[city({culture:2},{small:true,peace:true})]),
 moses:trait('The Wilderness Journey','Settlers cross hills for 1 movement. Cities beside waste gain +2 food.','The economic benefit favors difficult land rather than rich grassland.','Moses leads the biblical wilderness journey and commissions Joshua.',[city({food:2},{adjacent:'waste'})],[],{kinds:['settler'],terrain:'hills'}),
 huitzilopochtli:trait('The Migrating Banner','Settler production gains +2 during war. Guards gain +4 strength on unclaimed land.','Expansion during war requires escorts; settled battlefields remove the strength bonus.','Huitzilopochtli is associated with Mexica migration and warfare.',[city({production:2},{queue:'settler',war:true})],[combat(4,{kinds:['warrior'],neutralLand:true})]),
 itzamna:trait('Skyglyph Houses','Cities with both a Lore Quarter and Sanctuary gain +2 science and +1 culture.','Requires two districts and provides no direct military advantage.','Itzamna is associated with Maya celestial and knowledge traditions; ancient identifications vary.',[city({science:2,culture:1},{district:'campus',otherDistrict:'sanctuary'})]),
 inti:trait('Sunlit Terraces','Each nearby farm beside a hill adds +1 culture, up to +3 per city.','Requires carefully placed farms; flat fields generate no extra culture.','Inti’s solar and royal associations connect with Andean agricultural traditions.',[city({culture:1},{},'terraceFarm',3)]),
 perun:trait('The Oak Oath','Guards gain +5 strength in friendly forests. Forest Sanctuaries add +2 gold during peace.','Benefits depend on holding woodland; war removes the sanctuary income.','Perun is named in oaths recorded in the Primary Chronicle and associated with thunder.',[city({gold:2},{district:'sanctuary',adjacent:'forest',peace:true})],[combat(5,{kinds:['warrior'],terrain:'forest',ownLand:true})]),
 esther:trait('Courage at Court','The original capital gains +3 culture during war; resting civilian companies at home heal 4 extra health.','Civic resolve is limited to one city and wartime; civilians still cannot attack.','Esther risks approaching the king to plead for her people.',[city({culture:3},{capital:true,war:true})],[],null,{amount:4,when:{kinds:['settler','builder'],ownLand:true}}),
});
export const factionTrait=id=>FACTION_TRAITS[id]||null;
export const traitSummary=id=>factionTrait(id)?.summary||'';
export const usesFactionTraits=state=>state.ruleset===TRAIT_RULESET;
const military=new Set(['hero','warrior','archer','rider']);
const distance=(a,b)=>Math.max(Math.abs(a.q-b.q),Math.abs(a.r-b.r),Math.abs(a.q+a.r-b.q-b.r));
const tileOf=(s,id)=>s.tiles.find(t=>t.id===id);
function cityContext(s,c){
 const center=tileOf(s,c.tileId),adjacent=s.tiles.filter(t=>distance(t,center)===1);
 return {center,adjacent,near:s.tiles.filter(t=>t.owner===c.faction&&t.id!==center.id&&distance(t,center)<=2),faction:s.factions.find(f=>f.id===c.faction)};
}
function cityMatches(s,c,x,w){
 const war=Object.values(x.faction.relations).includes('war');
 return (!w.district||c.districts.includes(w.district))&&(!w.otherDistrict||c.districts.includes(w.otherDistrict))&&(!w.building||c.buildings.includes(w.building))&&(!w.river||x.center.river||x.adjacent.some(t=>t.river))&&(!w.adjacent||x.adjacent.some(t=>t.terrain===w.adjacent))&&(!w.peace||!war)&&(!w.war||war)&&(!w.small||c.population<=3)&&(!w.districtCount||c.districts.length>=w.districtCount)&&(!w.capital||c.capitalOf===c.faction)&&(!w.queue||c.queue===w.queue)&&(!w.civilianQueue||['builder','settler'].includes(c.queue))&&(!w.heroPresent||s.units.some(u=>u.faction===c.faction&&u.kind==='hero'&&u.tileId===c.tileId));
}
function countCity(s,c,x,count){
 if(!count)return 1;
 if(['farm','mine'].includes(count))return x.near.filter(t=>t.improvement===count).length;
 if(count==='untouchedForest')return x.adjacent.filter(t=>t.terrain==='forest'&&!t.improvement).length;
 if(count==='resourceKinds')return new Set(x.adjacent.map(t=>t.resource).filter(Boolean)).size;
 if(count==='districtPairs')return Math.floor(new Set(c.districts).size/2);
 if(count==='districts')return new Set(c.districts).size;
 if(count==='civics')return x.faction.civics.length;
 if(count==='terraceFarm')return x.near.filter(t=>t.improvement==='farm'&&s.tiles.some(n=>n.terrain==='hills'&&distance(t,n)===1)).length;
 return x.adjacent.filter(t=>t.terrain===count).length;
}
export function traitCityYields(s,c){
 const result={food:0,production:0,gold:0,science:0,culture:0};if(!usesFactionTraits(s))return result;
 const x=cityContext(s,c);
 for(const rule of factionTrait(c.faction)?.cityRules||[])if(cityMatches(s,c,x,rule.when))for(const [key,value]of Object.entries(rule.yields))result[key]+=value*Math.min(rule.cap,countCity(s,c,x,rule.count));
 return result;
}
function unitMatches(s,u,w){
 const tile=tileOf(s,u.tileId);if(!tile)return false;
 const near=kind=>s.units.some(a=>a.id!==u.id&&a.faction===u.faction&&a.kind===kind&&distance(tile,tileOf(s,a.tileId))<=1);
 return (!w.kinds||w.kinds.includes(u.kind))&&(!w.terrain||tile.terrain===w.terrain)&&(!w.river||tile.river)&&(!w.ownLand||tile.owner===u.faction)&&(!w.foreignLand||tile.owner&&tile.owner!==u.faction)&&(!w.neutralLand||!tile.owner)&&(!w.wounded||u.hp*2<u.maxHp)&&(!w.fullHealth||u.hp===u.maxHp)&&(!w.friendlyCity||s.cities.some(c=>c.faction===u.faction&&c.tileId===u.tileId))&&(!w.nearHero||near('hero'))&&(!w.nearBuilder||near('builder'))&&(!w.nearGuard||near('warrior'));
}
export function traitCombatBonus(s,u){if(!usesFactionTraits(s)||!military.has(u.kind))return 0;return Math.min(6,(factionTrait(u.faction)?.combatRules||[]).reduce((n,r)=>n+(unitMatches(s,u,r.when)?r.amount:0),0));}
export function traitMovementCost(s,u,tile,ordinary){const m=usesFactionTraits(s)&&factionTrait(u.faction)?.movement;return m&&m.kinds.includes(u.kind)&&tile.terrain===m.terrain?1:ordinary;}
export function traitHealingBonus(s,u){const h=usesFactionTraits(s)&&factionTrait(u.faction)?.healing;return h&&unitMatches(s,u,h.when)?Math.min(6,h.amount):0;}
export function traitVisionBonus(s,u){return usesFactionTraits(s)&&((u.faction==='odin'&&u.kind==='hero')||(u.faction==='gabriel'&&u.kind==='settler'))?1:0;}
