// The fifty playable realms of Pre-Genesis. Every realm, capital, city, power and emblem name
// comes from the patron's own scripture, myth or sacred geography, and each one carries a
// citation in `sources`. Numbers and alliances are game rules; docs/FACTIONS.md explains them.
import {factionTrait} from './faction-traits.js';

// The four shared art styles, each named after the realm that introduced it.
// Native builds store a style by its index here, so never reorder this list.
export const VISUAL_STYLES = Object.freeze(['michael', 'ra', 'athena', 'thor']);

// Each art style also selects the champion's power effect.
const STYLE_POWERS = {michael: 'aegis', ra: 'charge', athena: 'counsel', thor: 'strike'};

const UNIT_LABELS = {warrior: 'Spearmen', archer: 'Archers', rider: 'Horsemen', settler: 'Settlers', builder: 'Builders'};

// Identity sources: [url, label, one-line summary of what the source says about the patron].
const IDENTITY_SOURCES = {
  greek: ['https://www.gutenberg.org/cache/epub/348/pg348-images.html', 'Hesiod, Theogony; Homeric Hymns, translated by H. G. Evelyn-White'],
  egypt: ['https://egyptianmuseum.org/deities-overview', 'Rosicrucian Egyptian Museum: Deities in Ancient Egypt'],
  norse: ['https://www.gutenberg.org/files/18947/18947-h/18947-h.htm', 'Snorri Sturluson, The Younger Edda, translated by Rasmus B. Anderson'],
  michael: ['https://www.biblegateway.com/passage/?search=Revelation+12&version=KJV', 'Revelation 12:7–9',
    'Revelation portrays Michael leading angels in battle against the dragon.'],
  gabriel: ['https://bible.usccb.org/bible/luke/1', 'Luke 1:19, 26–38',
    'Luke names Gabriel as the angel who announces the birth of Jesus to Mary.'],
  moses: ['https://bible.usccb.org/bible/deuteronomy/31', 'Deuteronomy 31:1–8, 14–15',
    'Deuteronomy depicts Moses commissioning Joshua before Israel enters the promised land.'],
  esther: ['https://bible.usccb.org/bible/esther/4', 'Esther 4; Greek additions C and D',
    'Esther risks an uninvited audience with the king to plead for her people.'],
  vishnu: ['https://www.metmuseum.org/art/collection/search/38530', 'The Metropolitan Museum of Art: Vishnu with Lakshmi and Sarasvati',
    'Vishnu is a Hindu deity associated with preserving cosmic order.'],
  shiva: ['https://www.metmuseum.org/essays/recognizing-the-gods', 'The Metropolitan Museum of Art: Recognizing the Gods',
    'Shiva’s identifying attributes in Hindu art include a third eye and a trident.'],
  brahma: ['https://www.metmuseum.org/art/collection/search/38265', 'The Metropolitan Museum of Art: Brahma',
    'Brahma is a Hindu creator deity, often represented with four faces.'],
  durga: ['https://www.metmuseum.org/essays/recognizing-the-gods', 'The Metropolitan Museum of Art: Recognizing the Gods',
    'Durga is represented in Hindu art defeating the buffalo demon.'],
  lakshmi: ['https://www.metmuseum.org/art/collection/search/38530', 'The Metropolitan Museum of Art: Vishnu with Lakshmi and Sarasvati',
    'Lakshmi appears beside Vishnu in this Hindu sculpture, carrying a lotus.'],
  saraswati: ['https://www.metmuseum.org/art/collection/search/38530', 'The Metropolitan Museum of Art: Vishnu with Lakshmi and Sarasvati',
    'Saraswati, spelled Sarasvati in this museum record, carries a vina in this Hindu sculpture.'],
  amaterasu: ['https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9440', 'Kokugakuin University: Encyclopedia of Shinto, Amaterasu',
    'Amaterasu is a sun kami; the cave episode explains the withdrawal and return of her light.'],
  susanoo: ['https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9152', 'Kokugakuin University: Encyclopedia of Shinto, Susanoo',
    'Susanoo defeats the serpent Yamata no Orochi in accounts preserved in Japanese chronicles.'],
  inari: ['https://inari.jp/en/saijin/', 'Fushimi Inari Taisha: Enshrined Deity',
    'Fushimi Inari Taisha connects Inari’s name and divine protection with rice and abundance.'],
  shango: ['https://www.britishmuseum.org/collection/object/E_Af1952-07-134', 'British Museum: Shango ceremonial baton',
    'Shango is a Yoruba thunder deity associated with the ose ceremonial baton.'],
  ogun: ['https://www.metmuseum.org/ko/essays/the-age-of-iron-in-west-africa', 'The Metropolitan Museum of Art: The Age of Iron in West Africa',
    'Ogun is a Yoruba deity associated with iron, roads and warriors.'],
  oshun: ['https://whc.unesco.org/en/list/1118', 'UNESCO World Heritage Centre: Osun-Osogbo Sacred Grove',
    'Osun, also spelled Oshun, is the river and fertility divinity associated with the Osun-Osogbo grove.'],
  brigid: ['https://celt.ucc.ie/published/T300010.html', 'University College Cork, CELT: Cath Maige Tuired',
    'Brigid appears as Bríg, daughter of the Dagda, in the Irish tale Cath Maige Tuired.'],
  lugh: ['https://celt.ucc.ie/published/T300010.html', 'University College Cork, CELT: Cath Maige Tuired',
    'Lugh, spelled Lug in this translation, leads the Tuatha Dé in Cath Maige Tuired.'],
  dagda: ['https://celt.ucc.ie/published/T300010.html', 'University College Cork, CELT: Cath Maige Tuired',
    'The Dagda is a powerful member of the Tuatha Dé in Cath Maige Tuired.'],
  inanna: ['https://oracc.museum.upenn.edu/amgg/listofdeities/inanaitar/', 'ORACC: Ancient Mesopotamian Gods and Goddesses, Inana/Ishtar',
    'Inanna, also written Inana, is associated with love, warfare and the planet Venus.'],
  enki: ['https://oracc.museum.upenn.edu/amgg/listofdeities/enki/', 'ORACC: Ancient Mesopotamian Gods and Goddesses, Enki/Ea',
    'Enki, known as Ea in Akkadian, is associated with wisdom, incantations and subterranean waters.'],
  marduk: ['https://oracc.museum.upenn.edu/amgg/Listofdeities/Marduk/index.html', 'ORACC: Ancient Mesopotamian Gods and Goddesses, Marduk',
    'Marduk is the patron deity of Babylon and became a leading Mesopotamian god.'],
  quetzalcoatl: ['https://www.britishmuseum.org/collection/term/BIOG230422', 'British Museum: Quetzalcoatl',
    'Quetzalcoatl is the Nahuatl name of the Feathered Serpent deity.'],
  tlaloc: ['https://www.loc.gov/item/2021667846/', 'Library of Congress: Sahagún, Florentine Codex, Book I, The Gods',
    'Book I of the Florentine Codex describes Tlaloc as the god who gives and withholds rain.'],
  huitzilopochtli: ['https://www.loc.gov/item/2021667848/', 'Library of Congress: Sahagún, Florentine Codex, Book III, The Origin of the Gods',
    'Book III of the Florentine Codex tells of Huitzilopochtli’s birth at Coatepec.'],
  kukulkan: ['https://mna.inah.gob.mx/images/agenda/archivo/GLOSARIO-DIOSES-MAYAS-LSM.pdf', 'Mexico, INAH National Museum of Anthropology: Mayan Gods glossary',
    'Kukulkan is identified as a feathered serpent and deity of knowledge in the INAH glossary.'],
  itzamna: ['https://www.metmuseum.org/it/exhibitions/gods-divinity-maya-art/visiting-guide', 'The Metropolitan Museum of Art: Lives of the Gods, Itzamnaaj',
    'Itzamnaaj is a deity named in colonial Yucatán; reading the associated ancient name glyph remains uncertain.'],
  inti: ['https://archive.org/details/royalcommentarie00vega', 'Garcilaso de la Vega, Royal Commentaries of Peru (1609), translated by Paul Rycaut',
    'Garcilaso describes the Sun as the chief god of the Incas and its gold-plated temple in Cuzco.'],
  viracocha: ['https://www.gutenberg.org/ebooks/20218', 'Pedro Sarmiento de Gamboa, History of the Incas (1572), translated by Clements Markham',
    'Sarmiento records Andean accounts of Viracocha making the peoples of the world at Tiahuanaco.'],
  maui: ['https://www.tepapa.govt.nz/digital-museum/explore-digital-museum/crustaceans-aotearoa-new-zealand-and-south-pacific/panenehu', 'Museum of New Zealand Te Papa Tongarewa: Panenehu Shows Koura to Tangaroa',
    'Te Papa records Māori stories of Māui pulling up the great fish and confronting Tuna.'],
  tangaroa: ['https://collections.tepapa.govt.nz/object/235625', 'Museum of New Zealand Te Papa Tongarewa: Tangaroa',
    'On some Cook Islands, Tangaroa was revered as a principal deity of the sea and creation.'],
  guanyin: ['https://asia.si.edu/education/educator-resources/teaching-china-with-the-smithsonian/explore-by-object/standing-figure-of-guanyin-as-buddha/', 'Smithsonian National Museum of Asian Art: Standing Figure of Guanyin',
    'Guanyin is the bodhisattva of compassion in Chinese Buddhism.'],
  nezha: ['https://www.britishmuseum.org/collection/object/A_2018-3005-42?selectedImageId=1613582316', 'British Museum: Nezha',
    'Nezha is a protective figure in Chinese religion, depicted as a youth with supernatural attributes.'],
  perun: ['https://pages.uoregon.edu/kimball/chronicle.htm', 'University of Oregon: excerpts from the Russian Primary Chronicle',
    'The Primary Chronicle names Perun among the gods invoked in the oaths of Oleg’s men.'],
};

function identityLore(sourceKey, leader) {
  const summary = IDENTITY_SOURCES[sourceKey][2];
  if (summary) return summary;
  if (sourceKey === 'greek') return `${leader} is attested in Hesiod’s Theogony or the Homeric Hymns.`;
  if (sourceKey === 'egypt') return `${leader} is included in the Rosicrucian Egyptian Museum’s guide to ancient Egyptian deities.`;
  return `${leader} appears in Snorri Sturluson’s Prose Edda; spellings vary across translations.`;
}

// The champion takes the singular verb; unit groups take the plural.
export const factionBonusDescription = (city, units, champion = 'The champion') => [
  ...Object.entries(city).map(([key, value]) => `+${value} ${key} per city`),
  ...Object.entries(units).flatMap(([kind, stats]) => Object.entries(stats).map(([key, value]) => {
    const stat = key === 'moves' ? 'movement' : key === 'charges' ? `build charge${value === 1 ? '' : 's'}` : key;
    return kind === 'hero' ? `${champion} gains +${value} ${stat}` : `${UNIT_LABELS[kind]} gain +${value} ${stat}`;
  })),
].join('; ') + '.';

// Roster buttons show the champion; a shared patron is added so the four realms of God differ.
export const factionLabel = faction => faction.patron && faction.patron !== faction.leader
  ? `${faction.leader} · ${faction.patron}`
  : faction.leader;

// realm() takes one entry per faction. Named fields are [name, citation] pairs:
//   realm      [name, citation]            capital [name, citation]
//   cities     [[names in founding order], citation]
//   power      [name, what the object or deed is, citation]
//   emblem     [name, what the crest shows, citation]
function realm(entry) {
  const {id, leader, patron = leader, tradition, visualStyle, color, cityYields, unitBonuses, sourceKey = id, description} = entry;
  const [sourceUrl, sourceLabel] = IDENTITY_SOURCES[sourceKey];
  const [name, nameSource] = entry.realm;
  const [capital, capitalSource] = entry.capital;
  const [cityNames, citySource] = entry.cities;
  const [powerName, powerLore, powerSource] = entry.power;
  const [emblemName, emblemNote, emblemSource] = entry.emblem;
  const faction = {
    id, name, leader, patron, tradition, capital, visualStyle, color, description,
    bonus: factionBonusDescription(cityYields, unitBonuses, leader),
    trait: factionTrait(id),
    gameplay: {cityYields, unitBonuses, heroPower: STYLE_POWERS[visualStyle]},
    powerName, powerLore,
    emblem: {name: emblemName, source: emblemSource},
    sourceKey, sourceUrl, sourceLabel,
    lore: identityLore(sourceKey, leader),
    imagery: emblemNote,
    cityNames: [...cityNames],
    sources: {
      leader: sourceLabel,
      name: nameSource,
      capital: capitalSource,
      cityNames: citySource,
      powerName: powerSource,
      emblem: emblemSource,
    },
  };
  faction.label = factionLabel(faction);
  return faction;
}

export const FACTIONS = [
  // Native builds identify realms by their position in this list; never reorder it.
  realm({
    id: 'michael', leader: 'Michael', patron: 'God', tradition: 'Christian', visualStyle: 'michael', color: '#94D2FF',
    cityYields: {gold: 2, production: 1}, unitBonuses: {},
    realm: ['Heavenly Host', 'Luke 2:13; Revelation 12:7 (KJV)'],
    capital: ['New Jerusalem', 'Revelation 21:2 (KJV)'],
    cities: [['Ephesus', 'Smyrna', 'Pergamos', 'Thyatira', 'Sardis', 'Philadelphia', 'Laodicea'],
      'Revelation 1:11 (KJV): the seven churches, in the order named'],
    power: ['War in Heaven', 'Michael and his angels fight the dragon and cast it out of heaven.', 'Revelation 12:7–9'],
    emblem: ['Sword and scales', 'Sword and scales, the attributes later Christian art gives Michael; Revelation itself names only the battle.',
      'Revelation 12:7; later Christian art of the archangel'],
    description: 'The seven churches of Revelation under the archangel who fought the dragon.',
  }),
  realm({
    id: 'ra', leader: 'Ra', tradition: 'Egyptian', visualStyle: 'ra', color: '#F7BE89', sourceKey: 'egypt',
    cityYields: {food: 1}, unitBonuses: {rider: {moves: 1, strength: 6}},
    realm: ['Kemet', 'Egyptian km.t, “the Black Land” (Erman and Grapow, Wörterbuch V 126)'],
    capital: ['Heliopolis', 'Genesis 41:45 (On); Herodotus 2.3'],
    cities: [['Memphis', 'Thebes', 'Hermonthis', 'Bubastis', 'Leontopolis', 'Sakhebu'],
      'Herodotus 2.3, 2.59–60, 2.99; Strabo 17.1.19, 17.1.47; Papyrus Westcar 9.9–11 (Sakhebu)'],
    power: ['Day-Barque of Ra', 'Ra crosses the sky each day in his barque and drives back the serpent Apophis.', 'Book of the Dead, chapters 15 and 100'],
    emblem: ['Sun disk on the barque', 'The sun disk riding the day-barque, as on Egyptian solar vignettes.',
      'Book of the Dead, chapter 15; British Museum ostracon EA 29509'],
    description: 'The Black Land of Egypt, ruled from the sun city of Heliopolis.',
  }),
  realm({
    id: 'athena', leader: 'Athena', tradition: 'Greek', visualStyle: 'athena', color: '#92DEB5', sourceKey: 'greek',
    cityYields: {science: 2}, unitBonuses: {archer: {strength: 5}},
    realm: ['Attica', 'Apollodorus, Library 3.14.1; Herodotus 8.55'],
    capital: ['Athens', 'Apollodorus, Library 3.14.1 (Athena wins the city)'],
    cities: [['Lindos', 'Tegea', 'Alalcomenae', 'Ilion', 'Pellene', 'Coronea'],
      'Herodotus 2.182; Pausanias 8.45.4, 9.33.5, 7.27.2, 9.34.1; Iliad 6.297'],
    power: ['Guise of Mentor', 'Athena takes the likeness of Mentor to counsel Telemachus and stand beside Odysseus.', 'Odyssey 2.267–268; 22.205–206'],
    emblem: ['Owl and olive', 'The owl and olive sprig of Athenian silver coinage.', 'Athenian tetradrachm, about 430 BCE (University of Colorado)'],
    description: 'Attica and the Greek cities that kept temples of Athena.',
  }),
  realm({
    id: 'thor', leader: 'Thor', tradition: 'Norse', visualStyle: 'thor', color: '#C25E53', sourceKey: 'norse',
    cityYields: {production: 2}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Þrúðvangar', 'Gylfaginning 21; Grímnismál 4 (Þrúðheimr)'],
    capital: ['Bilskírnir', 'Gylfaginning 21; Grímnismál 24'],
    cities: [['Mæren', 'Hlaðir', 'Þórsnes', 'Himinbjörg', 'Glitnir', 'Landviði'],
      'Heimskringla, Hákonar saga góða 14–18 (Mæren, Hlaðir); Eyrbyggja saga 4 (Þórsnes); Grímnismál 13, 15, 17'],
    power: ['Mjölnir', 'Dwarven smiths forge the hammer that never misses and returns to Thor’s hand.', 'Skáldskaparmál 35; Gylfaginning 21'],
    emblem: ['Mjölnir', 'A hammer pendant of the kind worn in the Viking Age.', 'British Museum, Room 41 guide: Thor’s hammer pendant'],
    description: 'Thor’s Fields of Strength and the northern places of his worship.',
  }),

  realm({
    id: 'zeus', leader: 'Zeus', tradition: 'Greek', visualStyle: 'thor', color: '#C59F3A', sourceKey: 'greek',
    cityYields: {gold: 1, culture: 1}, unitBonuses: {hero: {strength: 4}},
    realm: ['Olympus', 'Hesiod, Theogony 62–75, 113; Iliad 1.494–499'],
    capital: ['Olympia', 'Pausanias 5.10 (the temple of Zeus)'],
    cities: [['Dodona', 'Lyctus', 'Nemea', 'Aegina', 'Lycosura', 'Dium'],
      'Iliad 16.233–235; Theogony 477–484; Pausanias 2.15.2, 2.29–30, 8.38; Thucydides 4.78; Diodorus 17.16'],
    power: ['Thunderbolt', 'The Cyclopes give Zeus thunder and the lightning bolt, by which he rules gods and mortals.', 'Hesiod, Theogony 139–141, 504–506'],
    emblem: ['Thunderbolt', 'The two-ended thunderbolt of Greek vase painting and coinage.', 'Hesiod, Theogony 504–506'],
    description: 'Olympus and the sanctuaries of Zeus from Olympia to Dodona.',
  }),
  realm({
    id: 'vishnu', leader: 'Vishnu', tradition: 'Hindu', visualStyle: 'michael', color: '#83A1F3',
    cityYields: {culture: 2}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Vaikuntha', 'Bhagavata Purana 3.15'],
    capital: ['Dvaraka', 'Vishnu Purana 5.23'],
    cities: [['Ayodhya', 'Mathura', 'Badari', 'Guruvayur', 'Puri', 'Tirumala'],
      'Ramayana, Bala Kanda 5; Vishnu Purana book 5; Mahabharata book 3; Narayaniyam; Skanda Purana, Purushottama-kshetra and Venkatachala mahatmyas'],
    power: ['Varaha', 'As the boar Varaha, Vishnu lifts the earth up from the cosmic waters.', 'Vishnu Purana 1.4'],
    emblem: ['Conch', 'Panchajanya, the conch that Vishnu, as Krishna, sounds before battle.', 'Bhagavad Gita 1.15'],
    description: 'Vishnu’s heaven and the holy cities of his avatars.',
  }),
  realm({
    id: 'poseidon', leader: 'Poseidon', tradition: 'Greek', visualStyle: 'thor', color: '#0091B5', sourceKey: 'greek',
    cityYields: {gold: 3}, unitBonuses: {rider: {strength: 4}},
    realm: ['Atlantis', 'Plato, Critias 113c–114c (Poseidon’s allotment)'],
    capital: ['Isthmia', 'Pausanias 2.1.7'],
    cities: [['Onchestus', 'Aegae', 'Helice', 'Sunium', 'Calauria', 'Taenarum'],
      'Iliad 2.506, 8.203, 13.21; Odyssey 3.278; Pausanias 2.33.2, 3.25.4, 7.24.5'],
    power: ['Earthshaker', 'Homer’s standing epithet for Poseidon, the god who shakes the earth.', 'Iliad 7.445; Homeric Hymn 22'],
    emblem: ['Trident', 'The trident with which Poseidon struck the Acropolis.', 'Apollodorus, Library 3.14.1'],
    description: 'Poseidon’s allotted island and his sanctuaries on the Greek coasts.',
  }),
  realm({
    id: 'demeter', leader: 'Demeter', tradition: 'Greek', visualStyle: 'michael', color: '#83870B', sourceKey: 'greek',
    cityYields: {food: 2}, unitBonuses: {builder: {charges: 1}},
    realm: ['Rharian Plain', 'Homeric Hymn to Demeter 450–456; Pausanias 1.38.6'],
    capital: ['Eleusis', 'Homeric Hymn to Demeter 270–274'],
    cities: [['Andania', 'Phigalia', 'Hermione', 'Enna', 'Potniae', 'Lerna'],
      'Pausanias 4.1.5, 8.42.1, 2.35.4, 9.8.1, 2.37.1; Cicero, Against Verres 2.4.106–107'],
    power: ['Mysteries of Eleusis', 'Demeter teaches the lords of Eleusis her rites, which bless those who see them.', 'Homeric Hymn to Demeter 473–482'],
    emblem: ['Ears of wheat', 'Ears of wheat, the grain Demeter gives to be sown across the inhabited world.', 'Apollodorus, Library 1.5.2'],
    description: 'The first-sown plain of Eleusis and the shrines of Demeter.',
  }),
  realm({
    id: 'inanna', leader: 'Inanna', tradition: 'Mesopotamian', visualStyle: 'athena', color: '#7275CC',
    cityYields: {science: 1, culture: 1}, unitBonuses: {archer: {strength: 5}},
    realm: ['Eanna', 'ETCSL 1.4.1, Inana’s descent, line 6; ETCSL 1.3.1'],
    capital: ['Uruk', 'ETCSL 1.4.1, line 6 (Unug)'],
    cities: [['Bad-tibira', 'Zabalam', 'Adab', 'Nippur', 'Kish', 'Akkad'],
      'ETCSL 1.4.1, lines 6–13: the temples Inana abandons, in order'],
    power: ['Star of Inanna', 'Her eight-pointed star stands for the planet Venus on Babylonian boundary stones.', 'Kudurru of Meli-Shipak, Louvre Sb 22'],
    emblem: ['Eight-pointed star', 'The eight-pointed star carved for Ishtar on Babylonian kudurrus.', 'Kudurru of Meli-Shipak, Louvre Sb 22'],
    description: 'Inanna’s Uruk and the temples she left on her descent.',
  }),
  realm({
    id: 'artemis', leader: 'Artemis', tradition: 'Greek', visualStyle: 'ra', color: '#708D28', sourceKey: 'greek',
    cityYields: {food: 1, science: 1}, unitBonuses: {archer: {strength: 5}},
    realm: ['Ortygia', 'Homeric Hymn to Apollo 16'],
    capital: ['Brauron', 'Pausanias 1.33.1; Euripides, Iphigenia in Tauris 1462–1467'],
    cities: [['Aulis', 'Amarynthus', 'Munichia', 'Stymphalus', 'Limnae', 'Caryae'],
      'Pausanias 9.19.6, 1.31.5, 1.1.4, 8.22.7, 4.4.2, 3.10.7'],
    power: ['Golden Shafts', 'The hymn hails Artemis as the goddess of the golden arrows.', 'Homeric Hymn 27.1–2'],
    emblem: ['Bow and arrow', 'The bow Artemis asks of Zeus and receives from the Cyclopes.', 'Callimachus, Hymn 3'],
    description: 'Artemis’s birthplace and her sanctuaries from Brauron to Caryae.',
  }),
  realm({
    id: 'shiva', leader: 'Shiva', tradition: 'Hindu', visualStyle: 'thor', color: '#A695EC',
    cityYields: {production: 1, gold: 1}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Kailasa', 'Kalidasa, Meghaduta 1.58–62'],
    capital: ['Kashi', 'Skanda Purana, Kashi Khanda'],
    cities: [['Chidambaram', 'Somnath', 'Ujjain', 'Kedarnath', 'Rameswaram', 'Madurai'],
      'Koyil Puranam; Shiva Purana, Kotirudra Samhita (the jyotirlingas); Meghaduta 1.30–38; Tiruvilaiyadal Puranam'],
    power: ['Tandava', 'The dance of Shiva as Nataraja, which turns the cycle of creation and dissolution.', 'Koyil Puranam; The Met, Shiva as Nataraja (39328)'],
    emblem: ['Trident and drum', 'The trishula with the damaru drum tied to its shaft.', 'The Met, Recognizing the Gods; Shiva as Nataraja (39328)'],
    description: 'Shiva’s mountain and the great shrines of his lingam and dance.',
  }),
  realm({
    id: 'oshun', leader: 'Oshun', tradition: 'Yoruba', visualStyle: 'michael', color: '#B7A63D',
    cityYields: {culture: 2}, unitBonuses: {settler: {moves: 1}},
    realm: ['Osun-Osogbo', 'UNESCO World Heritage List 1118'],
    capital: ['Osogbo', 'UNESCO World Heritage List 1118'],
    cities: [['Ile-Ife', 'Igede', 'Ilesa', 'Ido-Osun', 'Ikirun', 'Iponda'],
      'S. Johnson, The History of the Yorubas (1921), chapter 1; J. Murphy and M. Sanford, Osun across the Waters (2001)'],
    power: ['Abebe', 'The brass fan that Osun’s devotees carry in the Osogbo festival.', 'Murphy and Sanford, Osun across the Waters (2001)'],
    emblem: ['Abebe fan', 'Osun’s round brass fan.', 'Murphy and Sanford, Osun across the Waters (2001)'],
    description: 'The sacred grove of Osogbo and the towns along the Osun river.',
  }),
  realm({
    id: 'ogun', leader: 'Ogun', tradition: 'Yoruba', visualStyle: 'thor', color: '#179765',
    cityYields: {production: 2}, unitBonuses: {builder: {charges: 1}},
    realm: ['Ire', 'Oriki “Ogun Onire”; S. Barnes (ed.), Africa’s Ogun (1997)'],
    capital: ['Ire-Ekiti', 'S. Barnes (ed.), Africa’s Ogun (1997)'],
    cities: [['Ondo', 'Ilawe', 'Ado-Ekiti', 'Ikole', 'Akure', 'Oko'],
      'S. Barnes (ed.), Africa’s Ogun (1997): Ogun festival towns of Ekiti and Ondo'],
    power: ['Clearing the Path', 'Ogun cuts the first road through the forest with his iron blade.', 'S. Barnes (ed.), Africa’s Ogun (1997); Smithsonian EEPA 1992-028'],
    emblem: ['Machete', 'The iron cutlass that clears the way.', 'The Met, The Age of Iron in West Africa'],
    description: 'Ire, Ogun’s town, and the Ekiti and Ondo towns of his festivals.',
  }),
  realm({
    id: 'hermes', leader: 'Hermes', tradition: 'Greek', visualStyle: 'ra', color: '#FFB3A8', sourceKey: 'greek',
    cityYields: {gold: 3}, unitBonuses: {settler: {moves: 1}},
    realm: ['Arcadia', 'Homeric Hymn to Hermes 2'],
    capital: ['Cyllene', 'Homeric Hymn to Hermes 2'],
    cities: [['Pheneus', 'Tanagra', 'Pharae', 'Acacesium', 'Pylos', 'Pieria'],
      'Pausanias 8.14.10, 9.22.1, 7.22.2, 8.36.10; Homeric Hymn to Hermes 70, 216, 342'],
    power: ['Golden Sandals', 'Hermes binds on immortal golden sandals that carry him over sea and land.', 'Odyssey 5.44–46'],
    emblem: ['Kerykeion', 'The herald’s staff that Apollo gives Hermes.', 'Homeric Hymn to Hermes 529–532'],
    description: 'Arcadia, where Hermes was born on Mount Cyllene, and his cult towns.',
  }),
  realm({
    id: 'brahma', leader: 'Brahma', tradition: 'Hindu', visualStyle: 'michael', color: '#B25E98',
    cityYields: {food: 1, production: 1}, unitBonuses: {builder: {charges: 1}},
    realm: ['Brahmaloka', 'Kaushitaki Upanishad 1.3–5'],
    capital: ['Pushkar', 'Padma Purana, Srishti Khanda'],
    cities: [['Brahmavarta', 'Kurukshetra', 'Prayaga', 'Naimisha', 'Gaya', 'Brahmagiri'],
      'Manusmriti 2.17; Mahabharata 1.1 and 3.81; Matsya Purana 104–112; Vayu Purana, Gaya Mahatmya; Brahma Purana, Gautami Mahatmya'],
    power: ['Four Vedas', 'The four Vedas come forth from Brahma’s four mouths.', 'Bhagavata Purana 3.12.37'],
    emblem: ['Vedic manuscripts', 'Four bound palm-leaf manuscripts, for the four Vedas that come from Brahma’s four mouths.', 'Bhagavata Purana 3.12.37; The Met, Raga Brahma (825648)'],
    description: 'Brahma’s world and the sacred places of sacrifice and pilgrimage.',
  }),
  realm({
    id: 'dagda', leader: 'Dagda', tradition: 'Irish', visualStyle: 'athena', color: '#AFD99B',
    cityYields: {food: 1, culture: 1}, unitBonuses: {hero: {strength: 4}},
    realm: ['Tuatha Dé Danann', 'Cath Maige Tuired §1 (CELT T300010)'],
    capital: ['Brú na Bóinne', 'Tochmarc Étaíne §1'],
    cities: [['Murias', 'Ailech', 'Cnogba', 'Dubad', 'Mag Tuired', 'Brí Léith'],
      'Cath Maige Tuired §7 (Murias); Metrical Dindshenchas (Ailech, Cnogba, Dubad); Cath Maige Tuired; Tochmarc Étaíne (Brí Léith)'],
    power: ['Cauldron of the Dagda', 'The cauldron brought from Murias, from which no one ever went away unsatisfied.', 'Cath Maige Tuired §7'],
    emblem: ['Cauldron', 'The Dagda’s cauldron from Murias.', 'Cath Maige Tuired §7'],
    description: 'The Tuatha Dé Danann, from the Boyne mound to the northern cities.',
  }),
  realm({
    id: 'susanoo', leader: 'Susanoo', tradition: 'Shinto', visualStyle: 'thor', color: '#B690E4',
    cityYields: {gold: 3}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Izumo', 'Kojiki 1.18 (Chamberlain translation)'],
    capital: ['Suga', 'Kojiki 1.20'],
    cities: [['Torikami', 'Susa', 'Kumano', 'Hikawa', 'Yasaka', 'Ne-no-Kuni'],
      'Kojiki 1.18–23; Izumo Fudoki (Susa, Kumano); Hikawa and Yasaka shrine traditions'],
    power: ['Ten-Span Sword', 'With his ten-span sword Susanoo slays the eight-headed serpent Orochi.', 'Kojiki 1.19'],
    emblem: ['Ten-span sword', 'A straight sword over the waves of the sea plain he was given to rule.', 'Kojiki 1.13, 1.19'],
    description: 'Izumo, where Susanoo slew the serpent, and the shrines of his cult.',
  }),
  realm({
    id: 'inari', leader: 'Inari', tradition: 'Shinto', visualStyle: 'athena', color: '#FFB1C3',
    cityYields: {food: 2}, unitBonuses: {settler: {moves: 1}},
    realm: ['Yamashiro', 'Yamashiro Fudoki fragment (the Inari foundation account)'],
    capital: ['Fushimi', 'Fushimi Inari Taisha'],
    cities: [['Inariyama', 'Kasama', 'Takekoma', 'Yūtoku', 'Ōji', 'Toyokawa'],
      'Yamashiro Fudoki; K. Smyers, The Fox and the Jewel (1999): the major Inari shrines'],
    power: ['White Bird of Inari', 'A rice cake shot as a target turns into a white bird; where it lands, rice grows.', 'Yamashiro Fudoki fragment'],
    emblem: ['Hōju jewel', 'The wish-granting jewel carried by Inari’s fox messengers.', 'K. Smyers, The Fox and the Jewel (1999)'],
    description: 'The province of Fushimi and the great Inari shrines.',
  }),
  realm({
    id: 'enki', leader: 'Enki', tradition: 'Mesopotamian', visualStyle: 'athena', color: '#7DDFD1',
    cityYields: {science: 2}, unitBonuses: {hero: {strength: 4}},
    realm: ['Abzu', 'ETCSL 1.1.3, Enki and the World Order'],
    capital: ['Eridu', 'ETCSL 4.80.1, Temple Hymn 1; ETCSL 1.1.4'],
    cities: [['Kuara', 'Ur', 'Shuruppak', 'Dilmun', 'Magan', 'Meluhha'],
      'ETCSL 4.80.1, Temple Hymn 6 (Kuara); ETCSL 1.1.3 (Ur, Dilmun, Magan, Meluhha); Epic of Gilgamesh XI 11–31 (Shuruppak)'],
    power: ['Waters of the Abzu', 'Enki fills the Tigris with the sweet water of the abzu.', 'ETCSL 1.1.3, Enki and the World Order'],
    emblem: ['Flowing vase', 'The vase with streams of water flowing from it, Enki’s sign on cylinder seals.', 'ORACC, Enki/Ea'],
    description: 'The sweet-water deep of Eridu and the lands Enki ordered.',
  }),
  realm({
    id: 'lugh', leader: 'Lugh', tradition: 'Irish', visualStyle: 'ra', color: '#409551',
    cityYields: {culture: 2}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Tailtiu', 'Metrical Dindshenchas, Tailtiu; Lebor Gabála Érenn'],
    capital: ['Temair', 'Cath Maige Tuired §53 (Tara)'],
    cities: [['Gorias', 'Findias', 'Falias', 'Uisnech', 'Nás', 'Emain Ablach'],
      'Cath Maige Tuired §7; Lebor Gabála Érenn (Uisnech); Metrical Dindshenchas (Nás); Oidheadh Chloinne Tuireann (Emain Ablach)'],
    power: ['Samildánach', 'At Tara, Lugh is admitted as the one master of all the arts together.', 'Cath Maige Tuired §53–72'],
    emblem: ['Spear', 'The spear of Lugh, brought from Gorias.', 'Cath Maige Tuired §7'],
    description: 'Tara and the four cities from which the Tuatha Dé brought their treasures.',
  }),
  realm({
    id: 'saraswati', leader: 'Saraswati', tradition: 'Hindu', visualStyle: 'athena', color: '#94B255',
    cityYields: {science: 2}, unitBonuses: {builder: {charges: 1}},
    realm: ['Sapta Sindhu', 'Rig Veda 8.24.27; 6.61.12'],
    capital: ['Sharada Peeth', 'Kalhana, Rajatarangini 1.37'],
    cities: [['Sringeri', 'Plaksha', 'Vinashana', 'Prithudaka', 'Basar', 'Koothanur'],
      'Mahabharata 9.38, 9.53; Manusmriti 2.21 (Vinashana); temple traditions of Sringeri, Basar and Koothanur'],
    power: ['Hamsa', 'The swan-like bird that carries Saraswati.', 'The Met, Saraswati, goddess of learning (78265)'],
    emblem: ['Vina', 'The vina Saraswati plays.', 'The Met, Saraswati, goddess of learning (78265)'],
    description: 'The land of seven rivers and the seats of learning.',
  }),
  realm({
    id: 'amaterasu', leader: 'Amaterasu', tradition: 'Shinto', visualStyle: 'ra', color: '#B95C88',
    cityYields: {production: 1, science: 1}, unitBonuses: {rider: {strength: 4}},
    realm: ['Takamagahara', 'Kojiki 1.1'],
    capital: ['Ise', 'Nihon Shoki, Suinin 25'],
    cities: [['Kasanui', 'Hinokuma', 'Takachiho', 'Himuka', 'Kashihara', 'Isuzu'],
      'Nihon Shoki, Sujin 6 (Kasanui), book 1 variant (Hinokuma), Jimmu (Kashihara); Kojiki 1.37 (Takachiho, Himuka); Ise Jingu (Isuzu river)'],
    power: ['Yata no Kagami', 'The mirror that drew Amaterasu from the rock cave, later given to her grandson Ninigi.', 'Kojiki 1.16, 1.38'],
    emblem: ['Mirror', 'The round bronze mirror enshrined at Ise.', 'Kojiki 1.16; Ise Jingu'],
    description: 'The High Plain of Heaven and the shrines of the sun kami.',
  }),
  realm({
    id: 'quetzalcoatl', leader: 'Quetzalcoatl', tradition: 'Mexica (Nahua)', visualStyle: 'athena', color: '#14BDAD',
    cityYields: {science: 1, culture: 1}, unitBonuses: {settler: {moves: 1}},
    realm: ['Tollan', 'Florentine Codex, book 3, chapters 3–14'],
    capital: ['Cholollan', 'Florentine Codex, book 3, chapter 12'],
    cities: [['Tamoanchan', 'Teotihuacan', 'Tollantzinco', 'Cuauhtitlan', 'Coatzacoalco', 'Tlillan Tlapallan'],
      'Florentine Codex, book 3, chapters 12–14, and book 7, chapter 2; Leyenda de los Soles; Anales de Cuauhtitlan'],
    power: ['Wind of Ehecatl', 'As the wind, Quetzalcoatl blows until the new sun and moon begin to move.', 'Florentine Codex, book 7, chapter 2'],
    emblem: ['Wind jewel', 'The cut-shell pectoral that Quetzalcoatl wears as the wind god.', 'British Museum, stone bust of Quetzalcoatl (Am1825,1210.11)'],
    description: 'Tollan and the cities of the Feathered Serpent’s story.',
  }),

  realm({
    id: 'osiris', leader: 'Osiris', tradition: 'Egyptian', visualStyle: 'michael', color: '#6ABA77', sourceKey: 'egypt',
    cityYields: {food: 2}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Field of Reeds', 'Book of the Dead, chapter 110'],
    capital: ['Abydos', 'Plutarch, On Isis and Osiris 18–20; Strabo 17.1.42'],
    cities: [['Busiris', 'Mendes', 'Heracleopolis', 'Rosetau', 'Abaton', 'Thinis'],
      'Herodotus 2.46, 2.59; Book of the Dead, chapters 1, 17, 117–119; Diodorus 1.22'],
    power: ['Djed Pillar', 'The djed, the backbone of Osiris, set up as an amulet of stability.', 'Book of the Dead, chapter 155'],
    emblem: ['Djed pillar', 'The pillar of four bars that stands for Osiris.', 'Book of the Dead, chapter 155'],
    description: 'The Field of Reeds and the Egyptian cities of Osiris’s cult.',
  }),
  realm({
    id: 'isis', leader: 'Isis', tradition: 'Egyptian', visualStyle: 'michael', color: '#C06240', sourceKey: 'egypt',
    cityYields: {science: 1, culture: 1}, unitBonuses: {hero: {strength: 4}},
    realm: ['Chemmis', 'Herodotus 2.156 (the island where Horus was hidden)'],
    capital: ['Philae', 'Diodorus 1.22'],
    cities: [['Coptos', 'Byblos', 'Iseum', 'Sais', 'Menouthis', 'Pharos'],
      'Plutarch, On Isis and Osiris 14–16, 20; Herodotus 2.170–171; Strabo, book 17 (Greco-Roman Isis sanctuaries)'],
    power: ['Knot of Isis', 'The tyet amulet, which carries the blood and magic of Isis to protect the dead.', 'Book of the Dead, chapter 156'],
    emblem: ['Tyet knot', 'The looped knot of Isis, made in red stone for the dead.', 'Book of the Dead, chapter 156'],
    description: 'The floating island of Chemmis and the temples of Isis.',
  }),
  realm({
    id: 'horus', leader: 'Horus', tradition: 'Egyptian', visualStyle: 'ra', color: '#A07A00', sourceKey: 'egypt',
    cityYields: {production: 1, culture: 1}, unitBonuses: {rider: {strength: 4}},
    realm: ['Two Lands', 'Royal title nb tawy; The Contendings of Horus and Seth (Papyrus Chester Beatty I)'],
    capital: ['Edfu', 'Edfu temple inscriptions'],
    cities: [['Nekhen', 'Buto', 'Ombos', 'Letopolis', 'Athribis', 'Apollinopolis Parva'],
      'Herodotus 2.155–156, 2.166; Strabo 17.1.44, 17.1.48'],
    power: ['Winged Disk of Behdet', 'Horus of Behdet takes the form of a winged sun disk to fight the followers of Seth.', 'Edfu, the Legend of the Winged Disk'],
    emblem: ['Wedjat eye', 'The eye of Horus, injured and made whole.', 'The Met, wedjat eye amulet (547767)'],
    description: 'The Two Lands of the pharaoh, the living Horus, ruled from Edfu.',
  }),
  realm({
    id: 'lakshmi', leader: 'Lakshmi', tradition: 'Hindu', visualStyle: 'michael', color: '#9E66B4',
    cityYields: {gold: 1, culture: 1}, unitBonuses: {builder: {charges: 1}},
    realm: ['Kshirasagara', 'Vishnu Purana 1.9 (Lakshmi rises from the ocean of milk)'],
    capital: ['Karavira', 'Karavira Mahatmya (Kolhapur)'],
    cities: [['Tiruchanur', 'Uraiyur', 'Thirunaraiyur', 'Srirangam', 'Thiruvellarai', 'Kumbakonam'],
      'Venkatachala Mahatmya (Tiruchanur); Nalayira Divya Prabandham (the Divya Desam shrines)'],
    power: ['Gajalakshmi', 'Elephants pour water over Lakshmi as she sits on the lotus.', 'Shri Sukta; The Met, Lakshmi (78264)'],
    emblem: ['Lotus', 'The lotus that is Lakshmi’s seat and attribute.', 'The Met, Lakshmi (78264)'],
    description: 'The ocean of milk and the temples of Lakshmi.',
  }),
  realm({
    id: 'marduk', leader: 'Marduk', tradition: 'Mesopotamian', visualStyle: 'michael', color: '#5F7BCE',
    cityYields: {production: 1, science: 1}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Esagila', 'Enuma Elish VI 55–66'],
    capital: ['Babylon', 'Code of Hammurabi, prologue'],
    cities: [['Borsippa', 'Sippar', 'Dilbat', 'Kutha', 'Larsa', 'Isin'],
      'Code of Hammurabi, prologue (L. W. King translation)'],
    power: ['Net of Anu', 'Marduk spreads the net, his father Anu’s gift, to catch Tiamat.', 'Enuma Elish IV 41–44, 95'],
    emblem: ['Spade', 'The marru spade that marks Marduk on boundary stones.', 'ORACC, Marduk'],
    description: 'Marduk’s Babylon and the cities Hammurabi restored.',
  }),
  realm({
    id: 'thoth', leader: 'Thoth', tradition: 'Egyptian', visualStyle: 'athena', color: '#58ACED', sourceKey: 'egypt',
    cityYields: {science: 2}, unitBonuses: {settler: {moves: 1}},
    realm: ['Ogdoad', 'Hermopolitan cosmogony (Khemenu, “City of the Eight”); R. Wilkinson, The Complete Gods and Goddesses of Ancient Egypt (2003)'],
    capital: ['Hermopolis', 'Strabo 17.1.40'],
    cities: [['Hermopolis Parva', 'Pselchis', 'Tentyris', 'Latopolis', 'Elephantine', 'Panopolis'],
      'Strabo 17.1.18, 17.1.41, 17.1.44, 17.1.47, 17.1.54; Herodotus 2.28–29'],
    power: ['Scribe’s Palette', 'The dead ask for the palette and ink-pot of Thoth.', 'Book of the Dead, chapter 94'],
    emblem: ['Scribe’s palette', 'The scribe’s palette with its two ink wells and reed pens.', 'Book of the Dead, chapter 94'],
    description: 'The Eight of Hermopolis and the Egyptian towns Strabo describes.',
  }),
  realm({
    id: 'durga', leader: 'Durga', tradition: 'Hindu', visualStyle: 'thor', color: '#BE5B77',
    cityYields: {food: 1, production: 1}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Manidvipa', 'Devi Bhagavata Purana 12.10'],
    capital: ['Vindhyachal', 'Devi Mahatmya 11.41–42 (the Vindhya mountains)'],
    cities: [['Kamakhya', 'Kalighat', 'Jwalamukhi', 'Hinglaj', 'Chamundi', 'Tarapith'],
      'Kalika Purana (Kamakhya); Pithanirnaya (the Shakta pitha lists)'],
    power: ['Mahishasuramardini', 'Durga slays the buffalo demon Mahishasura and gives heaven back to the gods.', 'Devi Mahatmya, chapters 2–3'],
    emblem: ['Lion', 'The lion the Himalaya gives Durga to ride into battle.', 'Devi Mahatmya, chapter 2'],
    description: 'The Jewel Island of the Goddess and the seats of Shakti.',
  }),
  realm({
    id: 'viracocha', leader: 'Viracocha', tradition: 'Andean (Inca)', visualStyle: 'michael', color: '#EDB5EA',
    cityYields: {production: 2}, unitBonuses: {builder: {charges: 1}},
    realm: ['Collasuyu', 'Guaman Poma, Nueva corónica (1615); Cieza de León, Crónica del Perú II, chapter 5'],
    capital: ['Tiahuanaco', 'Sarmiento de Gamboa, History of the Incas, chapter 7'],
    cities: [['Cacha', 'Urcos', 'Pucara', 'Pachacamac', 'Chucuito', 'Copacabana'],
      'Betanzos, Suma y narración, chapters 1–2; Cieza de León I, chapters 72, 102–103, and II, chapter 5; Ramos Gavilán, Historia de Copacabana (1621)'],
    power: ['Pacarina', 'The places of origin from which Viracocha called each people out of the earth.', 'Cristóbal de Molina, Relación de las fábulas y ritos (1575)'],
    emblem: ['Island in the lake', 'The island rising from Lake Titicaca, where the world was made anew.', 'Sarmiento de Gamboa, History of the Incas, chapters 6–7'],
    description: 'The southern quarter of the Inca world, where Viracocha made the nations.',
  }),
  realm({
    id: 'nezha', leader: 'Nezha', tradition: 'Chinese', visualStyle: 'ra', color: '#D8BCFD',
    cityYields: {culture: 2}, unitBonuses: {archer: {strength: 5}},
    realm: ['Xiqi', 'Fengshen Yanyi (Nezha fights for Zhou)'],
    capital: ['Chentang Pass', 'Fengshen Yanyi, chapter 12'],
    cities: [['Qianyuan Shan', 'Cuiping Shan', 'Zhaoge', 'Mengjin', 'Sishui Pass', 'Tong Pass'],
      'Fengshen Yanyi, chapters 12–14 and the later campaign chapters'],
    power: ['Wind-Fire Wheels', 'His teacher Taiyi Zhenren gives Nezha wheels of wind and fire to ride.', 'Fengshen Yanyi, chapter 14'],
    emblem: ['Wind-fire wheel', 'A wheel wrapped in flame, the vehicle of Nezha.', 'Fengshen Yanyi, chapter 14'],
    description: 'The Zhou domain and the passes of the Investiture of the Gods.',
  }),
  realm({
    id: 'shango', leader: 'Shango', tradition: 'Yoruba', visualStyle: 'thor', color: '#E082AD',
    cityYields: {food: 2}, unitBonuses: {hero: {strength: 4}},
    realm: ['Oyo', 'S. Johnson, The History of the Yorubas (1921), chapter 8'],
    capital: ['Oyo-Ile', 'S. Johnson, The History of the Yorubas (1921)'],
    cities: [['Koso', 'Igboho', 'Ede', 'Saki', 'Iseyin', 'Ogbomoso'],
      'S. Johnson, The History of the Yorubas (1921): Koso, Igboho and the towns of Oyo'],
    power: ['Edun Ara', 'The thunderstones Shango hurls as lightning, kept on his shrines.', 'S. Johnson, The History of the Yorubas (1921)'],
    emblem: ['Oshe double axe', 'The double axe that crowns the ose Shango dance staff.', 'The Met, Ose Shango by Onakunle Aribikona (314326)'],
    description: 'The Oyo kingdom Shango once ruled and its towns.',
  }),
  realm({
    id: 'tlaloc', leader: 'Tlaloc', tradition: 'Mexica (Nahua)', visualStyle: 'athena', color: '#36BE9C',
    cityYields: {culture: 2}, unitBonuses: {builder: {charges: 1}},
    realm: ['Tlalocan', 'Florentine Codex, book 3, appendix, chapter 2'],
    capital: ['Tlaloctepetl', 'Durán, Book of the Gods and Rites, chapter 8'],
    cities: [['Pantitlan', 'Tetzcoco', 'Chalco', 'Xochimilco', 'Cuitlahuac', 'Mizquic'],
      'Florentine Codex, book 2, chapter 20 (Pantitlan); Durán, Historia de las Indias (the lake towns)'],
    power: ['Jars of the Tlaloque', 'The Tlaloque pour rain, hail and frost from their jars.', 'Historia de los mexicanos por sus pinturas; Florentine Codex, book 1, chapter 4'],
    emblem: ['Goggle-eyed face', 'Tlaloc’s ringed eyes and fanged mouth, as on his temple vessels.', 'INAH, Templo Mayor Museum; The Met, rain god mask (313255)'],
    description: 'Tlaloc’s paradise and the lake towns that prayed for rain.',
  }),

  realm({
    id: 'odin', leader: 'Odin', tradition: 'Norse', visualStyle: 'athena', color: '#79DCEB', sourceKey: 'norse',
    cityYields: {science: 1, production: 1}, unitBonuses: {hero: {strength: 4}},
    realm: ['Asgard', 'Gylfaginning 9'],
    capital: ['Valhalla', 'Grímnismál 8–10; Gylfaginning 38–41'],
    cities: [['Glaðsheimr', 'Vingólf', 'Valaskjálf', 'Sökkvabekkr', 'Hleiðr', 'Sigtúnir'],
      'Grímnismál 6–8; Gylfaginning 14; Thietmar of Merseburg, Chronicon 1.17 (Hleiðr); Ynglinga saga 5 (Sigtúnir)'],
    power: ['Huginn and Muninn', 'Odin’s two ravens fly over the world each day and bring him news.', 'Grímnismál 20; Gylfaginning 38'],
    emblem: ['Raven', 'One of Odin’s ravens. The sources give Odin one eye, pledged at Mímir’s well, and no eyepatch.',
      'Grímnismál 20; Völuspá 28'],
    description: 'The home of the Æsir and Odin’s halls from Grímnismál.',
  }),
  realm({
    id: 'freyja', leader: 'Freyja', tradition: 'Norse', visualStyle: 'michael', color: '#E68867', sourceKey: 'norse',
    cityYields: {gold: 1, culture: 1}, unitBonuses: {archer: {strength: 5}},
    realm: ['Fólkvangr', 'Grímnismál 14; Gylfaginning 24'],
    capital: ['Sessrúmnir', 'Gylfaginning 24'],
    cities: [['Nóatún', 'Breiðablik', 'Ýdalir', 'Hörgr', 'Gimlé', 'Fensalir'],
      'Grímnismál 5, 12, 16; Gylfaginning 17, 35; Hyndluljóð 10 (Hörgr); Völuspá 64 (Gimlé)'],
    power: ['Falcon Cloak', 'Freyja lends Loki her falcon cloak so he can fly to the giants.', 'Þrymskviða 3–5; Skáldskaparmál 1'],
    emblem: ['Brísingamen', 'The necklace Brísingamen.', 'Þrymskviða 13'],
    description: 'Freyja’s field of the chosen slain and the halls of the gods.',
  }),
  realm({
    id: 'freyr', leader: 'Freyr', tradition: 'Norse', visualStyle: 'athena', color: '#938100', sourceKey: 'norse',
    cityYields: {food: 2}, unitBonuses: {builder: {charges: 1}},
    realm: ['Álfheimr', 'Grímnismál 5'],
    capital: ['Uppsala', 'Ynglinga saga 10; Adam of Bremen, Gesta 4.26'],
    cities: [['Barri', 'Gymisgarðar', 'Vanaheimr', 'Þverá', 'Aðalból', 'Frösö'],
      'Skírnismál 6, 39; Vafþrúðnismál 39; Víga-Glúms saga 9; Hrafnkels saga 2–3; Frösö runestone place name'],
    power: ['Gullinbursti', 'The dwarves give Freyr a golden-bristled boar that runs over sky and sea.', 'Skáldskaparmál 35; Gylfaginning 49'],
    emblem: ['Gullinbursti', 'Freyr’s golden-bristled boar.', 'Skáldskaparmál 35'],
    description: 'The elf-home given to Freyr and the Swedish seat of his cult.',
  }),
  realm({
    id: 'maui', leader: 'Māui', tradition: 'Polynesian', visualStyle: 'michael', color: '#E8828A',
    cityYields: {production: 1, culture: 1}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Te Ika-a-Māui', 'G. Grey, Polynesian Mythology (1855); Te Ara'],
    capital: ['Hawaiki', 'G. Grey, Polynesian Mythology (1855)'],
    cities: [['Te Upoko-o-te-Ika', 'Te Waka-a-Māui', 'Rakiura', 'Haleakalā', 'Ka‘uiki', 'Tonga'],
      'Te Ara, Māori place names; W. D. Westervelt, Legends of Maui (1910); E. W. Gifford, Tongan Myths and Tales (1924)'],
    power: ['Snaring the Sun', 'Māui and his brothers snare the sun with ropes so the days grow longer.', 'G. Grey, Polynesian Mythology (1855); Te Ara'],
    emblem: ['Fishhook', 'The hook made from his grandmother’s jawbone, with which Māui fished up the land.', 'Te Ara, Whenua: how the land was shaped'],
    description: 'The fish Māui pulled up and the islands of his deeds.',
  }),
  realm({
    id: 'kukulkan', leader: 'Kukulkan', tradition: 'Maya', visualStyle: 'athena', color: '#51BC89',
    cityYields: {production: 1, science: 1}, unitBonuses: {archer: {strength: 5}},
    realm: ['Itza', 'The Book of Chilam Balam of Chumayel'],
    capital: ['Chichen Itza', 'Diego de Landa, Relación de las cosas de Yucatán, chapter 6'],
    cities: [['Mayapan', 'Chakanputun', 'Bakhalal', 'Uxmal', 'Ichcansiho', 'Cuzamil'],
      'Landa, Relación, chapters 6 and 27; The Book of Chilam Balam of Chumayel'],
    power: ['Return of Kukulcan', 'Landa records that Kukulcan left Mayapan and was afterwards honoured as a god.', 'Landa, Relación, chapter 6'],
    emblem: ['Feathered serpent', 'The plumed serpent head of Chichen Itza’s stairways.', 'National Museum of the American Indian, Chichen Itza'],
    description: 'The Itza of Chichen Itza and the Yucatán towns of Landa’s history.',
  }),
  realm({
    id: 'guanyin', leader: 'Guanyin', tradition: 'Chinese Buddhist', visualStyle: 'michael', color: '#916ABF',
    cityYields: {culture: 2}, unitBonuses: {hero: {strength: 4}},
    realm: ['Potalaka', 'Avatamsaka Sutra, Gandavyuha (Avalokiteshvara on Mount Potalaka)'],
    capital: ['Putuoshan', 'Chün-fang Yü, Kuan-yin (2001)'],
    cities: [['Xiangshan', 'Luojia', 'Wutai', 'Emei', 'Jiuhua', 'Upper Tianzhu'],
      'Chün-fang Yü, Kuan-yin (2001); Xiangshan baojuan (the Miaoshan legend)'],
    power: ['Vase of Pure Water', 'The sweet dew of Guanyin’s vase revives the fallen ginseng tree.', 'Journey to the West, chapter 26'],
    emblem: ['Vase and willow', 'The water vase with a willow branch that Guanyin holds.', 'Smithsonian, Standing Figure of Guanyin; Journey to the West, chapter 26'],
    description: 'Guanyin’s island mountain and the great Buddhist mountains of China.',
  }),
  realm({
    id: 'brigid', leader: 'Brigid', tradition: 'Irish', visualStyle: 'michael', color: '#B56D13',
    cityYields: {science: 1, culture: 1}, unitBonuses: {builder: {charges: 1}},
    realm: ['Laigin', 'Lebor Gabála Érenn (Laigin); Kildare lies in Leinster'],
    capital: ['Cill Dara', 'Cogitosus, Life of Brigit'],
    cities: [['Fochart', 'Carman', 'Tlachtga', 'Cruachan', 'Emain Macha', 'Ard Macha'],
      'Cogitosus, Life of Brigit; Gerald of Wales, Topographia Hibernica 2.34–36; Metrical Dindshenchas (Carman, Tlachtga); Noínden Ulad (Emain Macha)'],
    power: ['Brat Bríde', 'Brigid’s mantle, left out on the eve of her feast to receive her blessing.', 'A. Carmichael, Carmina Gadelica (1900); Irish and Scottish Gaelic folk custom'],
    emblem: ['Brigid’s cross', 'The woven rush cross made for her feast on the first of February.', 'Irish folk custom of Lá Fhéile Bríde'],
    description: 'Leinster, the church of Kildare and the old assembly places.',
  }),
  realm({
    id: 'tangaroa', leader: 'Tangaroa', tradition: 'Polynesian', visualStyle: 'ra', color: '#3FB2E5',
    cityYields: {gold: 3}, unitBonuses: {builder: {charges: 1}},
    realm: ['Te Moana-nui-a-Kiwa', 'Te Ara, Tangaroa – the sea'],
    capital: ['Taputapuatea', 'UNESCO World Heritage List 1529'],
    cities: [['Rurutu', 'Mangaia', 'Aitutaki', 'Opoa', 'Tahiti', 'Rarotonga'],
      'T. Henry, Ancient Tahiti (1928); W. W. Gill, Myths and Songs from the South Pacific (1876); British Museum Oc,LMS.19 (the figure from Rurutu)'],
    power: ['Breath of Tangaroa', 'The tides rise and fall with the breathing of Tangaroa.', 'E. Best, Maori Religion and Mythology (1924)'],
    emblem: ['Fish', 'A fish, for Tangaroa as the ancestor of the creatures of the sea.', 'Te Ara, Tangaroa and the genealogy of fish'],
    description: 'The great ocean of Kiwa and its island marae.',
  }),
  realm({
    id: 'skadi', leader: 'Skadi', tradition: 'Norse', visualStyle: 'ra', color: '#00BACD', sourceKey: 'norse',
    cityYields: {food: 1, production: 1}, unitBonuses: {archer: {strength: 5}},
    realm: ['Jötunheimr', 'Gylfaginning 8, 23'],
    capital: ['Þrymheimr', 'Grímnismál 11; Gylfaginning 23'],
    cities: [['Útgarðr', 'Járnviðr', 'Hnitbjörg', 'Grjótúnagarðar', 'Geirröðargarðar', 'Gastropnir'],
      'Gylfaginning 45; Völuspá 40; Skáldskaparmál 6, 17, 18; Fjölsvinnsmál 12'],
    power: ['Öndurdís', 'Skadi, the ski goddess, travels the mountains on skis and hunts with a bow.', 'Gylfaginning 23; the skaldic name öndurdís'],
    emblem: ['Skis and mountains', 'A pair of skis below the mountains of Þrymheimr.', 'Gylfaginning 23'],
    description: 'The giants’ world and the strongholds named in the Eddas.',
  }),

  realm({
    id: 'gabriel', leader: 'Gabriel', patron: 'God', tradition: 'Christian', visualStyle: 'athena', color: '#E4C781',
    cityYields: {culture: 2}, unitBonuses: {settler: {moves: 1}},
    realm: ['Galilee', 'Luke 1:26'],
    capital: ['Nazareth', 'Luke 1:26'],
    cities: [['Cana', 'Capernaum', 'Bethsaida', 'Nain', 'Tiberias', 'Chorazin', 'Magdala'],
      'John 2:1, 1:44, 6:23; Matthew 4:13, 11:21, 15:39; Luke 7:11 (KJV)'],
    power: ['Annunciation', 'Gabriel is sent to Nazareth to announce to Mary the birth of Jesus.', 'Luke 1:26–38'],
    emblem: ['Lily', 'The lily of later Annunciation paintings; Luke gives Gabriel no attribute, and no Bible text gives him a trumpet.',
      'Luke 1:26–38; later Christian art of the Annunciation'],
    description: 'The Galilean towns of the Gospels, where Gabriel brought the Annunciation.',
  }),
  realm({
    id: 'moses', leader: 'Moses', patron: 'God', tradition: 'Hebrew Bible', visualStyle: 'michael', color: '#B0C9FF',
    cityYields: {food: 1, culture: 1}, unitBonuses: {settler: {moves: 1}},
    realm: ['Twelve Tribes', 'Exodus 24:4'],
    capital: ['Kadesh', 'Deuteronomy 1:46'],
    cities: [['Gilgal', 'Shiloh', 'Shechem', 'Hebron', 'Bethel', 'Kirjath-jearim'],
      'Joshua 4:19, 18:1, 24:1, 14:13, 18:22, 18:14 (KJV)'],
    power: ['Pillar of Cloud', 'God goes before Israel by day in a pillar of cloud and by night in a pillar of fire.', 'Exodus 13:21–22'],
    emblem: ['Tablets of the covenant', 'The two tablets of stone written on both sides.', 'Exodus 32:15–16; 34:1'],
    description: 'The tribes of Israel, from the wilderness camp at Kadesh into Canaan.',
  }),
  realm({
    id: 'huitzilopochtli', leader: 'Huitzilopochtli', tradition: 'Mexica (Nahua)', visualStyle: 'ra', color: '#2987C8',
    cityYields: {production: 1, culture: 1}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Aztlan', 'Codex Boturini; Durán, Historia de las Indias, chapter 2'],
    capital: ['Tenochtitlan', 'Codex Mendoza, folio 2r'],
    cities: [['Coatepec', 'Chapultepec', 'Culhuacan', 'Tizaapan', 'Tzompanco', 'Tlatelolco'],
      'Florentine Codex, book 3, chapter 1; Codex Boturini; Durán, Historia de las Indias, chapter 6'],
    power: ['Xiuhcoatl', 'Born armed at Coatepec, Huitzilopochtli strikes down Coyolxauhqui with the fire serpent.', 'Florentine Codex, book 3, chapter 1'],
    emblem: ['Hummingbird', 'The hummingbird of his name, huitzilin.', 'Florentine Codex, book 1, chapter 1'],
    description: 'The Mexica migration from Aztlan to Tenochtitlan.',
  }),
  realm({
    id: 'itzamna', leader: 'Itzamna', tradition: 'Maya', visualStyle: 'michael', color: '#009799',
    cityYields: {science: 1, culture: 1}, unitBonuses: {warrior: {strength: 4}},
    realm: ['Copan', 'The Met, Lives of the Gods (2022); National Museum of the American Indian, Copan'],
    capital: ['Izamal', 'B. de Lizana, Historia de Yucatán (1633); D. López de Cogolludo, Historia de Yucathan (1688)'],
    cities: [['Palenque', 'Tikal', 'Yaxchilan', 'Dzibilchaltun', 'Ake', 'Kabah'],
      'Classic Maya royal cities (archaeological sites); Landa, Relación (Ake)'],
    power: ['Itzam Ye', 'The great celestial bird, a form or companion of the aged sky god.', 'The Met, Lives of the Gods (2022)'],
    emblem: ['Folded codex', 'A Maya screenfold book, for the god who first made letters.',
      'Landa, Relación; K. Taube, The Major Gods of Ancient Yucatan (1992), God D'],
    description: 'The Maya kingdoms from Izamal to Copan.',
  }),
  realm({
    id: 'inti', leader: 'Inti', tradition: 'Andean (Inca)', visualStyle: 'ra', color: '#CCD188',
    cityYields: {culture: 2}, unitBonuses: {hero: {strength: 4}},
    realm: ['Tawantinsuyu', 'Guaman Poma, Nueva corónica (1615); Garcilaso de la Vega, Royal Commentaries (1609)'],
    capital: ['Cuzco', 'Garcilaso de la Vega, Royal Commentaries 1.15–16'],
    cities: [['Island of the Sun', 'Pacaritambo', 'Huanacauri', 'Vilcas', 'Tumipampa', 'Sacsayhuaman'],
      'Garcilaso, Royal Commentaries 1.15, 3.20, 7.27; Sarmiento de Gamboa, History of the Incas, chapters 11–12; Cieza de León I, chapters 44, 89'],
    power: ['Inti Raymi', 'The solstice feast of the Sun, held in the great square of Cuzco.', 'Garcilaso, Royal Commentaries 6.20–23'],
    emblem: ['Sun face', 'The Sun as a face with rays, like the gold plate in the temple of Cuzco.', 'Garcilaso, Royal Commentaries 3.20'],
    description: 'The Inca realm of four quarters and the shrines of the Sun.',
  }),
  realm({
    id: 'perun', leader: 'Perun', tradition: 'Slavic', visualStyle: 'thor', color: '#DB9249',
    cityYields: {gold: 1, science: 1}, unitBonuses: {builder: {charges: 1}},
    realm: ['Rus’', 'Primary Chronicle, years 907, 945 and 980'],
    capital: ['Kyiv', 'Primary Chronicle, year 980 (the idol of Perun on the hill)'],
    cities: [['Chernihiv', 'Pereiaslavl', 'Polotsk', 'Rostov', 'Liubech', 'Novgorod'],
      'Primary Chronicle, year 907 (the towns of Oleg’s treaty, sworn by Perun) and year 980 (Novgorod)'],
    power: ['Oath by Perun', 'Oleg’s men swear the treaty with Byzantium by their weapons and by Perun.', 'Primary Chronicle, years 907 and 945'],
    emblem: ['Axe', 'An axe, for the weapons laid down when the Rus’ swore by Perun.', 'Primary Chronicle, year 945'],
    description: 'Kyivan Rus’ and the towns of the treaty sworn by Perun.',
  }),
  realm({
    id: 'esther', leader: 'Esther', patron: 'God', tradition: 'Hebrew Bible', visualStyle: 'michael', color: '#CF87CC',
    cityYields: {gold: 1, culture: 1}, unitBonuses: {settler: {moves: 1}},
    realm: ['Persia and Media', 'Esther 1:3, 1:19'],
    capital: ['Shushan', 'Esther 1:2'],
    cities: [['Achmetha', 'Ahava', 'Casiphia', 'Tel-abib', 'Tel-melah', 'Tel-harsa'],
      'Ezra 6:2, 8:15, 8:17, 2:59; Ezekiel 3:15 (KJV)'],
    power: ['Golden Sceptre', 'King Ahasuerus holds out the golden sceptre and spares Esther, who came unbidden.', 'Esther 5:2'],
    emblem: ['Sceptre and myrtle', 'The golden sceptre, with myrtle for her Hebrew name Hadassah.', 'Esther 5:2; 2:7'],
    description: 'The Persian court at Shushan and the exile towns of Ezra and Ezekiel.',
  }),
];

function powerDescription(faction) {
  const name = faction.leader;
  switch (faction.gameplay.heroPower) {
    case 'aegis': return `${name} heals friendly units within 2 hexes by 24 and gives military units +6 strength for 2 turns.`;
    case 'charge': return `${name} gives friendly units within 2 hexes +2 movement this turn and military units +4 strength for 2 turns.`;
    case 'counsel': return `${name} heals friendly units within 2 hexes by 30 and reveals the land within 5 hexes for 2 turns.`;
    case 'strike': return `${name} deals 25 damage to enemy units and 20 to enemy cities within 2 hexes. It cannot capture a city.`;
  }
}
export const HERO_POWERS = FACTIONS.map(f => ({
  factionId: f.id,
  name: f.powerName,
  cooldown: 4,
  description: powerDescription(f),
  lore: f.powerLore,
  source: f.sources.powerName,
}));

// Opponent selection uses a private RNG so the map RNG stays unchanged.
// Fisher–Yates supplies three distinct, seed-dependent opponents for every realm.
export function campaignRoster(factionId, seed) {
  const player = FACTIONS.find(f => f.id === factionId);
  if (!player) return campaignRoster('michael', seed);
  let random = (Number(seed) >>> 0 || 42) ^ 0x9e3779b9;
  for (const char of factionId) random = Math.imul(random ^ char.charCodeAt(0), 16777619) >>> 0;
  const opponents = FACTIONS.filter(f => f.id !== factionId);
  for (let i = opponents.length - 1; i > 0; i--) {
    random = (Math.imul(random, 1664525) + 1013904223) >>> 0;
    const j = Math.floor(random / 4294967296 * (i + 1));
    [opponents[i], opponents[j]] = [opponents[j], opponents[i]];
  }
  return [player, ...opponents.slice(0, 3)];
}
