// Short, source-linked summaries of Hindu, Shinto, Yoruba, Irish, Mesoamerican, Andean,
// Chinese, Polynesian and Slavic traditions. faction-lore.js adds the realm notes.
const source = (id, title, url, kind = 'museum') => ({id, title, url, kind});
const story = (title, text, ...sourceIds) => ({title, text, sourceIds});
const relation = (name, role) => ({name, role});
const symbol = (name, meaning) => ({name, meaning});

export const LORE_WORLD = {
  vishnu: {
    identity: 'Vishnu is a major Hindu god who sustains the order of the cosmos; Vaishnava traditions revere him as the supreme divinity.',
    worldview: ['Preservation is active work. Vishnu takes the form a threatened world needs, so each avatar is a distinct saving act, and between the ages he rests on the cosmic waters.'],
    stories: [
      story('The ocean between worlds',
        'Vishnu rests on the serpent Shesha in the primordial waters. A lotus rising from him bears Brahma the creator. A Bengali image places Lakshmi at his feet with Narada and Garuda nearby.',
        'ocean'),
      story('Varaha restores the earth',
        'As the boar Varaha, Vishnu dives into the ocean and raises the earth from beneath it. A Guler painting shows the rescue: restoring a threatened world, not conquest for its own sake.',
        'varaha'),
    ],
    relationships: [
      relation('Lakshmi', 'His consort, goddess of prosperity.'),
      relation('Shesha', 'The many-headed serpent on whom he rests.'),
      relation('Garuda', 'The bird who carries him.'),
    ],
    symbols: [
      symbol('Conch and discus', 'The conch he sounds and the discus he throws.'),
      symbol('Lotus', 'Links his cosmic rest with creation.'),
      symbol('Boar', 'Marks Varaha, who restored the earth.'),
    ],
    practice: ['Devotional images may join several avatars; the Kashmiri Vaikuntha form combines human, lion and boar faces.'],
    variants: ['Lists of avatars and regional images differ, and one community’s image is not a rule for every Vaishnava tradition.'],
    sources: [
      source('ocean', 'The Met — Vishnu Narayana on Shesha', 'https://www.metmuseum.org/art/collection/search/78252'),
      source('varaha', 'The Met — Vishnu as Varaha', 'https://www.metmuseum.org/art/collection/search/37953'),
      source('vaikuntha', 'The Met — Vaikuntha Vishnu', 'https://www.metmuseum.org/art/collection/search/38515'),
    ],
  },
  shiva: {
    identity: 'Shiva is a major Hindu god whose traditions join the ascetic and the householder, cosmic change and liberation.',
    worldview: ['Calling Shiva only a destroyer misses the balance of Nataraja, Lord of the Dance, in whom creation, preservation and dissolution turn together, and who offers refuge to the devotee.'],
    stories: [
      story('The dance within the flames',
        'In the Chola bronzes Shiva dances in a ring of fire. One hand holds the drum of creation, another the fire of dissolution; his foot presses on ignorance while his raised hand offers refuge.',
        'dance'),
      story('The poison from the ocean',
        'When gods and asuras churn the ocean for its treasures, a deadly poison rises too. Shiva swallows it while Parvati watches, and his throat turns blue.',
        'churning'),
    ],
    relationships: [
      relation('Parvati', 'His consort.'),
      relation('Vishnu', 'A fellow actor in the churning of the ocean.'),
    ],
    symbols: [
      symbol('Damaru', 'The small drum of creation.'),
      symbol('Trident', 'His weapon and sign.'),
      symbol('Ring of fire', 'Dissolution within the cosmic cycle.'),
    ],
    practice: ['A Nataraja bronze is a sacred image; its posture and gestures teach the relation between cosmic activity and liberation.'],
    variants: ['Shaiva traditions differ in theology and ritual. Nataraja is one form, and its meanings do not apply to every image of Shiva.'],
    sources: [
      source('dance', 'The Met — Shiva as Nataraja', 'https://www.metmuseum.org/art/collection/search/39328'),
      source('churning', 'British Museum — the churning of the ocean', 'https://www.britishmuseum.org/collection/object/A_2007-3005-7'),
    ],
  },
  brahma: {
    identity: 'Brahma is the Hindu creator god, usually shown with four faces. He is distinct from Brahman, the philosophical term for ultimate reality.',
    worldview: ['Creation happens again and again within cosmic time. His four faces show a presence facing every direction, and his book and water pot tie the making of the world to sacred knowledge.'],
    stories: [
      story('A lotus above the waters',
        'After a cosmic flood, a lotus rises from the resting Vishnu. Brahma appears upon it and brings forth the ordered world, its beings and its teachings.',
        'creation'),
      story('The creator as music',
        'A Mankot painting shows Brahma as a raga. His four heads share one crown, and his hands hold a water pot, rosary, Vedic book and sacred grass.',
        'raga'),
    ],
    relationships: [
      relation('Vishnu', 'From whose lotus Brahma is born.'),
      relation('Saraswati', 'His consort in a Thanjavur painting and many other images.'),
    ],
    symbols: [
      symbol('Four faces', 'Presence in every direction.'),
      symbol('Hamsa', 'The swan-like bird he rides.'),
      symbol('Book and water pot', 'Knowledge and ritual.'),
    ],
    practice: ['Brahma appears in Indian and Southeast Asian sacred art, from Cambodian stone to north Indian painting.'],
    variants: ['His role in creation does not mean every Hindu community gives him equal devotion; the Brahma and Saraswati pairing is one of several.'],
    sources: [
      source('creation', 'National Museum of Asian Art — Vishnu’s Cosmic Ocean', 'https://asia.si.edu/accessibility/vishnus-cosmic-ocean-accessible-exhibition-text/'),
      source('raga', 'The Met — Raga Brahma', 'https://www.metmuseum.org/art/collection/search/825648'),
      source('faces', 'The Met — Brahma, Cambodia', 'https://www.metmuseum.org/art/collection/search/38265'),
      source('couple', 'British Museum — Brahma and Sarasvati', 'https://www.britishmuseum.org/collection/object/A_1962-1231-0-13-28'),
    ],
  },
  saraswati: {
    identity: 'Saraswati is the Hindu goddess of knowledge, speech, music and the arts, first praised in the Rig Veda as a sacred river.',
    worldview: ['Flowing water and learning meet in her history. Her images join cultivated skill, sacred study and disciplined worship.'],
    stories: [
      story('From river to learning',
        'The Vedic Saraswati is a river of the northwest. Later devotion honours her as the goddess of knowledge and the arts, a change across centuries rather than one story.',
        'wisdom'),
      story('The goddess with the vina',
        'In Ravi Varma’s print Saraswati sits by a lotus pond playing the vina, holding a manuscript and rosary, with a peacock beside her in place of the usual swan.',
        'print'),
    ],
    relationships: [
      relation('Brahma', 'Her consort in many images.'),
      relation('Vishnu and Lakshmi', 'Beside whom some eastern Indian sculptures place her.'),
    ],
    symbols: [
      symbol('Vina', 'Music and the arts.'),
      symbol('Manuscript', 'Learning and its keeping.'),
      symbol('Rosary', 'Discipline and recitation.'),
    ],
    practice: ['Devotion to Saraswati makes study and artistic training sacred work.'],
    variants: ['Japanese Benzaiten grew from Saraswati through Buddhism but has her own history; regional family groupings also differ.'],
    sources: [
      source('wisdom', 'National Museum of Asian Art — Wisdom of the Goddess', 'https://asia.si.edu/whats-on/exhibitions/wisdom-of-the-goddess/'),
      source('print', 'The Met — Saraswati, goddess of learning', 'https://www.metmuseum.org/art/collection/search/78265'),
      source('regional', 'The Met — Vishnu with Lakshmi and Sarasvati', 'https://www.metmuseum.org/art/collection/search/38120'),
      source('japan', 'British Museum — Benzaiten', 'https://www.britishmuseum.org/collection/object/A_1924-0714-0-2'),
    ],
  },
  lakshmi: {
    identity: 'Lakshmi, also called Shri, is the Hindu goddess of good fortune, prosperity and abundance, the consort of Vishnu.',
    worldview: ['Prosperity in her images means fertility, flourishing life and well-being, shown through water, lotus and living creatures, not wealth alone.'],
    stories: [
      story('Rising from the ocean',
        'When gods and asuras churn the ocean of milk, Lakshmi rises among its treasures. The same labour also brings up a deadly poison.',
        'churning'),
      story('The elephants’ offering',
        'In Gaja-Lakshmi images elephants pour water over the goddess. In a Ravi Varma print a white elephant offers her a garland as she stands on a lotus.',
        'print'),
    ],
    relationships: [
      relation('Vishnu', 'Her consort, whose rest she attends.'),
      relation('Kamalatmika', 'A Tantric form of Lakshmi seated on a lotus with elephants.'),
    ],
    symbols: [
      symbol('Lotus', 'Her seat and attribute.'),
      symbol('Elephants with water', 'The Gaja-Lakshmi image of abundance.'),
      symbol('Garland', 'An offering of honour.'),
    ],
    practice: ['Her image travelled through temple sculpture, painting and cheap devotional prints into many homes.'],
    variants: ['Kamalatmika belongs to a Tantric setting, and Bengali festival images place Lakshmi in Durga’s family; neither is a universal genealogy.'],
    sources: [
      source('churning', 'British Museum — the churning of the ocean', 'https://www.britishmuseum.org/collection/object/A_2007-3005-7'),
      source('print', 'The Met — Lakshmi', 'https://www.metmuseum.org/art/collection/search/78264'),
      source('kamala', 'The Met — the goddess Kamalatmika', 'https://www.metmuseum.org/art/collection/search/849494'),
      source('family', 'British Museum — Bengali Durga shara', 'https://www.britishmuseum.org/collection/object/A_1989-0204-0-42'),
    ],
  },
  durga: {
    identity: 'Durga is a powerful Hindu goddess, central to Shakta traditions that worship the Divine Mother as supreme.',
    worldview: ['The Devi Mahatmya shows the goddess restoring a cosmos the gods could not save alone. Devotees also welcome her as a mother returning home.'],
    stories: [
      story('Mahishasura, the buffalo demon',
        'Durga fights Mahishasura, who changes shape and becomes a buffalo. A Kolkata print shows him defeated at her feet while her many hands hold the gods’ weapons.',
        'mahisha'),
      story('Shumbha and Nishumbha',
        'The brothers Shumbha and Nishumbha seize the realms of the gods, and the goddess and her forms defeat their armies. The episodes are recited in Durga worship.',
        'puja'),
    ],
    relationships: [
      relation('Parvati and Shiva', 'With whom many traditions link Durga.'),
      relation('Lakshmi, Saraswati, Ganesha and Kartikeya', 'Her family in Bengali festival images.'),
    ],
    symbols: [
      symbol('Lion', 'The mount she rides.'),
      symbol('Many weapons', 'The powers the gods give her.'),
      symbol('Buffalo', 'Marks the Mahishasura story.'),
    ],
    practice: ['Durga Puja joins worship, recitation and carefully made images; Bengali tableaux celebrate her homecoming as well as her victory.'],
    variants: ['Durga, Kali and other forms relate differently across texts and communities, and the Bengali family grouping is regional.'],
    sources: [
      source('mahisha', 'The Met — Sri Sri Durga', 'https://www.metmuseum.org/art/collection/search/786759'),
      source('puja', 'Belur Math — Durga Puja and the Devi Mahatmya', 'https://belurmath.org/durga-puja-at-belur-math/', 'tradition'),
      source('family', 'British Museum — Bengali Durga shara', 'https://www.britishmuseum.org/collection/object/A_1989-0204-0-42'),
    ],
  },
  amaterasu: {
    identity: 'Amaterasu-Ōmikami is the Japanese kami of the sun and the ancestor of the imperial line, enshrined at Ise.',
    worldview: ['Light, rice fields, weaving and right relations belong together. When she withdraws, the whole world suffers, and it takes a community of kami to bring her light back.'],
    stories: [
      story('The rock cave of heaven',
        'Offended by Susanoo’s outrages, Amaterasu shuts herself in a cave and the world goes dark. The kami hang a mirror and jewels and dance outside; their laughter draws her out, and daylight returns.',
        'cave'),
      story('A home at Ise',
        'Ise Jingu tells how Yamatohime-no-mikoto searched for a lasting place to enshrine Amaterasu after the sacred mirror left the palace, and found it at Ise.',
        'ise'),
    ],
    relationships: [
      relation('Susanoo', 'Her brother, whose deeds drive her into the cave.'),
      relation('Ninigi', 'Her grandson, who brings the regalia to earth.'),
      relation('Toyouke', 'The kami of food at Ise’s Outer Shrine.'),
    ],
    symbols: [
      symbol('Mirror', 'The sacred mirror of the cave story, enshrined at Ise.'),
      symbol('Sunlight', 'The life lost while she hides.'),
      symbol('Jewels', 'Part of the cave story and the imperial regalia.'),
    ],
    practice: ['Ise’s Inner Shrine is dedicated to Amaterasu; its sacred mirror is never shown to visitors.'],
    variants: ['The Kojiki, Nihon Shoki and shrine traditions differ, and “kami” is broader than “god” or “goddess”.'],
    sources: [
      source('cave', 'National Museum of Asian Art — Arts of Japan, Amaterasu', 'https://docent.asia.si.edu/wp-content/uploads/Arts-of-Japan.pdf'),
      source('ise', 'Ise Jingu — about the shrines and their history', 'https://www.isejingu.or.jp/en/about/index.html', 'tradition'),
    ],
  },
  susanoo: {
    identity: 'Susanoo is a Japanese kami whose stories span disorder in heaven, rescue in Izumo and rule in the land below.',
    worldview: ['He is neither simply a storm god nor a villain: the kami who wrecks the order of heaven also saves a family from a serpent. Place and kinship shape each story.'],
    stories: [
      story('A pledge, then disorder',
        'Susanoo visits Amaterasu and swears a pledge to prove his intent, then wrecks her rice fields and weaving hall. She withdraws into the cave, and the kami expel him from heaven.',
        'susanoo'),
      story('Kushinadahime and the serpent',
        'In Izumo Susanoo turns Kushinadahime into a comb for his hair, slays the eight-headed serpent Orochi and finds the sword Kusanagi in its tail. At Suga he builds their home and sings a poem.',
        'kushi', 'susanoo'),
    ],
    relationships: [
      relation('Amaterasu', 'His sister.'),
      relation('Kushinadahime', 'The woman he rescues and marries.'),
      relation('Ashinazuchi and Tenazuchi', 'Her parents.'),
    ],
    symbols: [
      symbol('Comb', 'Kushinadahime, hidden in his hair.'),
      symbol('Kusanagi', 'The sword found in the serpent’s tail.'),
      symbol('Eightfold fence', 'The image of his poem at Suga.'),
    ],
    practice: ['Izumo keeps his sacred places and family ties; his wedding poem links him with poetry as well as force.'],
    variants: ['The Kojiki and other texts tell his story differently, and the label “storm god” does not cover every role.'],
    sources: [
      source('susanoo', 'Kokugakuin University — Susanoo', 'https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9152', 'scholarship'),
      source('kushi', 'Kokugakuin University — Kushinadahime', 'https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9366', 'scholarship'),
    ],
  },
  inari: {
    identity: 'Inari is the Japanese kami of rice, food and prosperity. At Fushimi Inari Taisha, Inari Ōkami unites five enshrined kami.',
    worldview: ['Food and livelihood link farming, household protection and trade. Inari’s many local forms reflect the communities that founded shrines, not one fixed biography.'],
    stories: [
      story('The rice-cake target',
        'The Yamashiro record tells how Hata no Irogu shot at a rice cake. It turned into a white bird and flew to a mountain, and rice grew where it landed, giving the shrine its name.',
        'faith'),
      story('The rice-bearing visitor',
        'A later tradition shows Inari as an old man carrying rice who promises to protect Kūkai’s temple Tōji, evidence of how kami and Buddhist worship were joined.',
        'faith'),
    ],
    relationships: [
      relation('Uka-no-Mitama', 'The rice kami central to Fushimi.'),
      relation('Kūkai', 'The Buddhist teacher of the Tōji tradition.'),
      relation('White foxes', 'Revered messengers of Inari; Inari is not a fox.'),
    ],
    symbols: [
      symbol('Rice', 'Food, livelihood and the founding story.'),
      symbol('White fox', 'The messenger, not the kami.'),
      symbol('Vermilion', 'At Fushimi, protection and plentiful harvest.'),
    ],
    practice: ['Fushimi explains Inari’s blessing as food, clothing, shelter and a flourishing life.'],
    variants: ['Some forms join Inari with the Buddhist Dakiniten and others do not; appearance and gender vary by tradition.'],
    sources: [
      source('faith', 'Kokugakuin University — Inari faith', 'https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9027', 'scholarship'),
      source('fushimi', 'Fushimi Inari Taisha — enshrined deity', 'https://inari.jp/en/saijin/', 'tradition'),
      source('fox', 'Fushimi Inari Taisha — foxes and shrine colour', 'https://inari.jp/en/faq/', 'tradition'),
    ],
  },
  oshun: {
    identity: 'Oshun, or Osun, is the Yoruba orisha of the Osun river, of fertility and of the bond between people and sacred places.',
    worldview: ['The river is a living presence, not a resource. At Osogbo its grove, shrines, art and worshippers form one sacred landscape, and well-being depends on keeping faith with the orisha.'],
    stories: [
      story('The river and Oba',
        'A tradition recorded for the Osogbo World Heritage nomination tells how Osun became a river after a quarrel with Oba, another wife of Shango. It is one local account among several.',
        'nomination'),
      story('A grove renewed',
        'In the twentieth century Susanne Wenger and Yoruba artists such as Adebisi Akanji rebuilt threatened shrines at Osogbo, sustaining a living religious community.',
        'grove', 'film'),
    ],
    relationships: [
      relation('Shango and Oba', 'Part of the river story told at Osogbo.'),
      relation('The people of Osogbo', 'Keep faith with the river and the grove.'),
    ],
    symbols: [
      symbol('River water', 'A living presence of fertility and protection.'),
      symbol('Sacred grove', 'Home of shrines, worship and memory.'),
    ],
    practice: ['The yearly festival renews the bond between the goddess, the town and the grove, where shrines to other orisha also stand.'],
    variants: ['Yoruba traditions and their Atlantic diasporas are related but distinct; this dossier centres on Osogbo.'],
    sources: [
      source('nomination', 'Nigeria — Osun-Osogbo World Heritage nomination', 'https://whc.unesco.org/uploads/nominations/1118.pdf', 'tradition'),
      source('grove', 'UNESCO — Osun-Osogbo Sacred Grove', 'https://whc.unesco.org/en/list/1118', 'scholarship'),
      source('film', 'The Met — Osun-Osogbo Sacred Grove', 'https://www.metmuseum.org/ko/perspectives/osun-osogbo'),
    ],
  },
  ogun: {
    identity: 'Ogun is the Yoruba orisha of iron and of all the useful and dangerous work of tools and weapons.',
    worldview: ['Iron clears paths, tills land, serves healers and wounds enemies. Ogun’s domain is the practical work communities rely on, and his power must be handled with care.'],
    stories: [
      story('Clearing the way',
        'A Smithsonian photograph from Lagos shows Arabi Ajigbale, dressed in Ogun’s cloths, sweeping the market before the masqueraders enter: the opening of the path made visible.',
        'path'),
      story('Iron in the healer’s work',
        'A Yoruba herbalist’s iron staff links Ogun with Osanyin and Erinle. Iron blades open forest paths and cut the plants healers need.',
        'staff'),
    ],
    relationships: [
      relation('Blacksmiths', 'Craftsmen whose work lies in Ogun’s domain.'),
      relation('Osanyin and Erinle', 'Healing orisha linked with the herbalist’s staff.'),
    ],
    symbols: [
      symbol('Iron blade', 'Clearing, cutting and making.'),
      symbol('Tools', 'The power of iron beyond war.'),
      symbol('Cleared path', 'Passage made possible.'),
    ],
    practice: ['Museum archives record Ogun festivals, shrines and performances in particular Yoruba towns, a living practice.'],
    variants: ['Stories and duties vary between communities; this dossier does not treat one version of the Ire story as the only one.'],
    sources: [
      source('path', 'Smithsonian — Arabi Ajigbale clears the way', 'https://www.si.edu/object/archives/components/sova-eepa-1992-028-ref3598'),
      source('staff', 'National Museum of African Art — herbalist’s staff', 'https://www.si.edu/object/herbalists-staff%3Anmafa_76-3-4'),
      source('cosmos', 'National Museum of African Art — Areogun’s bowl', 'https://africa.si.edu/collection/selected-artwork/1712'),
    ],
  },
  shango: {
    identity: 'Shango, or Sango, is the Yoruba orisha of thunder and lightning, remembered in Oyo as a king who became divine.',
    worldview: ['Royal charisma does not guarantee right conduct. The stories join great power to its consequences, and ritual art sets that power among worshippers, shrines and town.'],
    stories: [
      story('The king and his power',
        'The Met describes Shango as an ambitious king of Oyo whose fascination with powers such as lightning outran his control. His memory joins charisma to the cost of misused power.',
        'king'),
      story('The staff leaves the shrine',
        'At yearly festivals devotees carry the ose Shango staff out of the shrine and dance with it. Artists reshape the staff but always keep its double axe.',
        'staff'),
    ],
    relationships: [
      relation('The kings of Oyo', 'The setting of his human and divine rule.'),
      relation('Twins', 'Under his protection in traditions the Met records.'),
      relation('Devotees', 'Keep his shrines and dance with his staff.'),
    ],
    symbols: [
      symbol('Double axe', 'The crown of the ose Shango staff.'),
      symbol('Thunderstones', 'Lightning made visible, kept on his shrines.'),
      symbol('Dance staff', 'Links shrine, artist and worshipper.'),
    ],
    practice: ['Shrine figures and staffs serve worship; twin figures belong to a separate duty of family care.'],
    variants: ['Oyo, other Yoruba towns and the diaspora religions tell related but different stories of his family.'],
    sources: [
      source('king', 'The Met — Abiyamo figure and Shango', 'https://www.metmuseum.org/art/collection/search/312182'),
      source('staff', 'The Met — Ose Shango by Onakunle Aribikona', 'https://www.metmuseum.org/art/collection/search/314326'),
      source('twins', 'The Met — twin figure and ritual care', 'https://www.metmuseum.org/art/collection/search/314456'),
    ],
  },
  dagda: {
    identity: 'The Dagda is a mighty figure of the Irish Tuatha Dé Danann, linked in medieval tales with plenty, strength, knowledge and music.',
    worldview: ['His authority includes feeding a host and commanding music, not only striking enemies. The tales can make him comic and still immensely capable.'],
    stories: [
      story('Service under Bres',
        'Under the unjust king Bres, the Dagda is forced to build ramparts. His humiliation is part of a wider failure of kingship and hospitality that the Tuatha Dé rise against.',
        'battle'),
      story('Calling back the harp',
        'After the battle the Dagda, Lugh and Ogma pursue the Fomorians. The Dagda calls his stolen harp from the wall and plays the music of sorrow, joy and sleep.',
        'harp'),
    ],
    relationships: [
      relation('Brigid', 'His daughter in Irish texts.'),
      relation('Lugh and Ogma', 'His companions in recovering the harp.'),
      relation('Bres', 'The king whose rule fails in hospitality.'),
    ],
    symbols: [
      symbol('Cauldron', 'From which no one leaves unsatisfied.'),
      symbol('Harp', 'Whose music he commands.'),
      symbol('Ramparts', 'The labour forced on him by Bres.'),
    ],
    practice: ['This evidence is medieval literature from Christian Ireland; it keeps older figures but gives no complete ritual.'],
    variants: ['Translations differ on names and the harp. The tale is not a single “Celtic scripture”, and Irish figures should not borrow British or continental attributes.'],
    sources: [
      source('battle', 'UCC CELT — Cath Maige Tuired, translated by Elizabeth Gray', 'https://celt.ucc.ie/document/T300010/', 'primary'),
      source('harp', 'UCC CELT — The Second Battle of Moytura, section 163', 'https://celt.ucc.ie/published/T300011/text163.html', 'primary'),
    ],
  },
  lugh: {
    identity: 'Lugh, or Lug, is a hero of the Irish Tuatha Dé Danann, famed for mastering every art and for leading them in Cath Maige Tuired.',
    worldview: ['His gift is not one craft others lack but the joining of all the crafts a people needs, so his leadership rests on coordination and judgement.'],
    stories: [
      story('The master of all arts',
        'At Tara the doorkeeper refuses Lugh craft after craft, since the court already has each specialist. Lugh asks whether anyone there has all of them together, and is let in.',
        'battle'),
      story('The fair of Tailtiu',
        'The place-lore of Tailtiu tells of the woman who died clearing a plain. Lugh, her foster-son, founds the yearly assembly in her memory, with its games and fair dealing.',
        'tailtiu', 'history'),
    ],
    relationships: [
      relation('Tailtiu', 'His foster-mother.'),
      relation('Nuada', 'The king whose court admits him.'),
      relation('The craftsmen of Tara', 'Whose skills Lugh unites.'),
    ],
    symbols: [
      symbol('Many crafts', 'The key to his admission at Tara.'),
      symbol('Assembly ground', 'A place of memory and order.'),
      symbol('Spear', 'His treasure, brought from Gorias.'),
    ],
    practice: ['Lughnasadh keeps the importance of the harvest assembly, though medieval explanations cannot recover every older rite.'],
    variants: ['Calling Lugh a sun god hides the texts’ stress on skill, kingship and kinship; Irish Lug and continental Lugus need separate evidence.'],
    sources: [
      source('battle', 'UCC CELT — The Second Battle of Moytura', 'https://celt.ucc.ie/document/T300011/', 'primary'),
      source('tailtiu', 'UCC CELT — Metrical Dindshenchas, Tailtiu', 'https://celt.ucc.ie/published/T106500D/text033.html', 'primary'),
      source('history', 'UCC CELT — Keating’s History of Ireland', 'https://celt.ucc.ie/document/T100054/', 'primary'),
    ],
  },
  brigid: {
    identity: 'Brigid, or Brigit, is an Irish goddess of poetry and learned skill. Her medieval evidence must be kept apart from the lives of Saint Brigit of Kildare.',
    worldview: ['The surviving notices tie inspired speech to healing and smithcraft, concrete kinds of knowledge. They also show how little of her story survives.'],
    stories: [
      story('Three Brigits',
        'Cormac’s Glossary names Brigit the poet and her sisters of healing and of smithcraft. This brief notice lies behind later ideas of a threefold goddess.',
        'glossary'),
      story('Grief for Ruadán',
        'In Cath Maige Tuired, Ruadán, son of Brigit and Bres, wounds the smith Goibniu and is killed. Brigit’s lament for him is remembered as the first keening in Ireland.',
        'ruadan'),
    ],
    relationships: [
      relation('The Dagda', 'Her father.'),
      relation('Bres', 'The father of her son Ruadán.'),
      relation('Ruadán', 'The son she mourns.'),
    ],
    symbols: [
      symbol('Poetry', 'Her clearly attested domain.'),
      symbol('Smithcraft', 'Linked with a Brigit in the glossary.'),
      symbol('Lament', 'Her grief for Ruadán.'),
    ],
    practice: ['Modern devotional communities read these fragments in living ways; their practice is modern tradition, not ancient record.'],
    variants: ['Saint Brigit’s cross, Kildare’s miracles and her Christian feast are separate evidence, and the link between saint and goddess is debated.'],
    sources: [
      source('glossary', 'Clann Bhríde — primary passages on Brigit', 'https://clannbhride.org/articles-and-essays/finding-brighid-in-the-ancient-lore/', 'tradition'),
      source('ruadan', 'UCC CELT — The Second Battle of Moytura, section 124', 'https://celt.ucc.ie/published/T300011/text124.html', 'primary'),
      source('debate', 'University College Cork — Brigit, saint or goddess?', 'https://www.ucc.ie/en/smg/newsevents/', 'scholarship'),
    ],
  },
  viracocha: {
    identity: 'Viracocha, or Tiqzi Wiracocha, is the Andean creator in accounts recorded before and after the Spanish conquest.',
    worldview: ['Making beings and ordering places go together: roads, places of origin and the creator’s journey give the land its history. Colonial writers preserve this testimony but filter it through their own beliefs.'],
    stories: [
      story('A world ordered after darkness',
        'The National Museum of the American Indian presents Wiracocha as maker of sun, moon, stars, plants, animals and people, who laid out the first roads. Other accounts set creation after an earlier destruction.',
        'creator', 'chronicle'),
      story('The fire at Cacha',
        'At Cacha, people threaten the wandering creator. Fire falls from the sky, and when they recognise his power and plead with him, he ends it.',
        'chronicle'),
    ],
    relationships: [
      relation('Inti and Mama Quilla', 'The sun and moon he makes.'),
      relation('The Andean peoples', 'Called out at their places of origin.'),
    ],
    symbols: [
      symbol('Road', 'Creation joined to the ordering of the land.'),
      symbol('Lake Titicaca', 'Where many accounts place the making of the world.'),
      symbol('Fire at Cacha', 'A local story of recognition.'),
    ],
    practice: ['These stories belong to specific Andean places; the roads also have a human history as works of the Inca state.'],
    variants: ['Wiracocha is not automatically every earlier staff-bearing image, and Christian comparisons in colonial sources are not facts about older belief.'],
    sources: [
      source('creator', 'National Museum of the American Indian — Tiqzi Wiracocha', 'https://americanindian.si.edu/inkaroad/ancestors/creationstories/the-creator.html'),
      source('chronicle', 'Pedro Sarmiento de Gamboa — History of the Incas, translated by Clements Markham', 'https://www.gutenberg.org/ebooks/20218', 'primary'),
    ],
  },
  nezha: {
    identity: 'Nezha is a young protector god of Chinese religion and literature, widely honoured in Taiwan as the Third Prince.',
    worldview: ['His stories weigh duty to family and community, the cost of violence and the chance of a new life. Buddhist, Daoist, temple and novel traditions each place him differently.'],
    stories: [
      story('The dragon prince',
        'Nezha kills a dragon king’s son and brings danger on his family. To spare them, he gives his body back to his parents: a hard lesson in responsibility.',
        'taiwan', 'opera'),
      story('A body made of lotus',
        'His teacher, an immortal, rebuilds Nezha from lotus stems and flowers, and his story continues beyond death. Retellings differ on what leads to this and what follows.',
        'taiwan'),
    ],
    relationships: [
      relation('Li Jing', 'His father.'),
      relation('The dragon king', 'Whose son Nezha kills.'),
      relation('His immortal teacher', 'Who gives him a lotus body.'),
    ],
    symbols: [
      symbol('Wind-fire wheels', 'The wheels he rides.'),
      symbol('Universe ring', 'His weapon.'),
      symbol('Lotus', 'The substance of his new body.'),
    ],
    practice: ['Taiwanese temple processions perform the Third Prince, and Singapore temples honour him: a living tradition.'],
    variants: ['The Investiture of the Gods and Journey to the West are witnesses, not scripture, and a modern film should not replace temple tradition.'],
    sources: [
      source('taiwan', 'Taiwan Review — Dancing with the Gods', 'https://taiwanreview.nat.gov.tw/AMP/Culture/Taiwan-Review/25135/Dancing-with-the-Gods', 'tradition'),
      source('opera', 'Kaohsiung Cultural Center — Nezha opera synopsis', 'https://english.khcc.gov.tw/PhotoData/PIC1111031.pdf', 'tradition'),
      source('symbols', 'Singapore National Heritage Board — Balestier heritage trail', 'https://www.nhb.gov.sg/~/media/nhb/files/places/trails/balestier/balestier.pdf'),
    ],
  },
  quetzalcoatl: {
    identity: 'Quetzalcoatl, the Feathered Serpent, is a great Mesoamerican god. This dossier follows Nahua and Mexica accounts.',
    worldview: ['Human life depends on divine acts that win both existence and food. As the wind, Ehecatl, he gives breath and motion to the world.'],
    stories: [
      story('The bones of earlier people',
        'Quetzalcoatl goes down to Mictlantecuhtli, lord of the dead, to bring back the bones of an earlier humanity. With them, and the gods’ own blood, people live again.',
        'bones', 'wind'),
      story('Wind sets the heavens moving',
        'In the creation account the National Museum of Anthropology presents, Ehecatl-Quetzalcoatl blows until the new sun and moon begin to move, so day and night can follow each other.',
        'wind'),
    ],
    relationships: [
      relation('Mictlantecuhtli', 'Lord of the dead, keeper of the bones.'),
      relation('Ehecatl', 'His form as the wind.'),
      relation('Kukulkan', 'A related Maya feathered serpent with its own stories.'),
    ],
    symbols: [
      symbol('Feathered serpent', 'Bird plumage on a serpent body.'),
      symbol('Wind jewel', 'The cut-shell ornament he wears.'),
      symbol('Curved staff', 'His sign on the museum’s stela.'),
    ],
    practice: ['Priests and rulers could bear his name or title, so each image needs its own historical setting.'],
    variants: ['Creation stories, the wind god and the ruler Topiltzin Quetzalcoatl overlap; this dossier does not merge them into one biography.'],
    sources: [
      source('bones', 'British Museum — stone bust of Quetzalcoatl', 'https://www.britishmuseum.org/collection/object/E_Am1825-1210-11'),
      source('wind', 'Museo Nacional de Antropología — stela of Quetzalcoatl', 'https://mna.inah.gob.mx/detalle_pieza_mes.php?id=344'),
      source('codex', 'Library of Congress — Florentine Codex, Book III, The Origin of the Gods', 'https://www.loc.gov/item/2021667848/', 'primary'),
    ],
  },
  tlaloc: {
    identity: 'Tlaloc is the rain god of central Mexico; Mexica worship tied him to water, crops, mountains and dangerous storms.',
    worldview: ['The rain that feeds the maize can also destroy it with hail. Tlaloc stands for an uncertain bond with water, never a guaranteed blessing.'],
    stories: [
      story('The mountain of sustenance',
        'At Tenochtitlan’s Templo Mayor the northern shrine belonged to Tlaloc. INAH describes it as a sacred mountain of food, paired with Huitzilopochtli’s Coatepec to the south.',
        'temple'),
      story('Water poured on the earth',
        'The Templo Mayor Museum explains a blue jar with Tlaloc’s face as a vessel from which rain reaches the earth, alongside offerings to calm crop-destroying storms.',
        'museum'),
    ],
    relationships: [
      relation('Huitzilopochtli', 'Shares the twin shrines of the Templo Mayor.'),
      relation('The Tlaloque', 'His helpers, who pour the rain.'),
    ],
    symbols: [
      symbol('Ringed eyes', 'His best-known feature.'),
      symbol('Fangs', 'The mark of his mouth.'),
      symbol('Water jar', 'Rain poured out on the world.'),
    ],
    practice: ['Offerings and temple rites sought a working relationship with powers that could feed or ruin the fields.'],
    variants: ['Rain gods have long histories across Mesoamerica; Mixtec, Maya and Mexica religions are distinct, and Chaak is not another spelling of Tlaloc.'],
    sources: [
      source('temple', 'INAH — the Templo Mayor and its sacred mountains', 'https://lugares.inah.gob.mx/es/node/4463'),
      source('museum', 'INAH — Templo Mayor Museum, Tlaloc gallery', 'https://lugares.inah.gob.mx/en/node/5284'),
      source('mask', 'The Met — Mixtec rain god mask', 'https://www.metmuseum.org/art/collection/search/313255'),
      source('codex', 'Library of Congress — Florentine Codex, Book I, The Gods', 'https://www.loc.gov/item/2021667846/', 'primary'),
    ],
  },
  maui: {
    identity: 'Māui is the ancestral trickster and hero of many Polynesian peoples. This dossier follows Māori accounts from Aotearoa New Zealand.',
    worldview: ['His deeds depend on knowledge from his elders as much as on daring. The women and ancestors who teach him are part of every triumph.'],
    stories: [
      story('Fishing up the land',
        'Māui hides in his brothers’ canoe. Far out at sea he baits his grandmother’s jawbone hook and hauls up the great fish, Te Ika-a-Māui, the North Island.',
        'fish'),
      story('Knowledge from the elders',
        'The jawbone of Murirangawhenua also helps Māui slow the sun, Tama-nui-te-rā. From Mahuika he learns the secret of fire.',
        'elders'),
    ],
    relationships: [
      relation('Taranga', 'His mother.'),
      relation('Murirangawhenua', 'The grandmother whose jawbone he uses.'),
      relation('Mahuika', 'The elder who keeps fire.'),
    ],
    symbols: [
      symbol('Jawbone hook', 'An inherited gift that raises the land.'),
      symbol('Canoe', 'The brothers’ voyage.'),
      symbol('The sun', 'Whose pace he slows.'),
    ],
    practice: ['Māui stories tie places, kin and the handing on of knowledge together, with duties to the people who tell them.'],
    variants: ['Māori, Hawaiian, Samoan and Tongan Māui stories differ; this dossier does not merge them or borrow a modern film’s inventions.'],
    sources: [
      source('fish', 'Te Ara — the North and South islands', 'https://teara.govt.nz/en/whenua-how-the-land-was-shaped/page-2', 'scholarship'),
      source('elders', 'Te Ara — kaumātua in early traditions', 'https://teara.govt.nz/en/kaumatua-maori-elders/page-2', 'scholarship'),
    ],
  },
  kukulkan: {
    identity: 'Kukulkan is the Yucatec Maya name of the Feathered Serpent, linked above all with Chichen Itza and later with Mayapan.',
    worldview: ['Feathered-serpent imagery joins earth and sky, but its meaning belongs to particular Maya places and peoples; shared images do not erase differences.'],
    stories: [
      story('The lord of Chichen Itza',
        'Diego de Landa recorded a tradition of a lord called Kukulcan at Chichen Itza, who ordered the city of Mayapan. His informants disagreed about when he came.',
        'landa'),
      story('A serpent of light',
        'At Chichen Itza the equinox sun casts a shadow serpent down the pyramid called Kukulkan’s temple. The Smithsonian presents Maya readings of Kukulkan joining earth and sky.',
        'chichen'),
    ],
    relationships: [
      relation('The Itza', 'The Maya people of Chichen Itza.'),
      relation('Quetzalcoatl', 'The Nahua feathered serpent, with his own stories.'),
    ],
    symbols: [
      symbol('Feathered serpent', 'His principal image.'),
      symbol('Serpent-head stairways', 'Place him in the city’s great spaces.'),
      symbol('Plumed ornaments', 'Worn in ritual at Chichen Itza.'),
    ],
    practice: ['Maya artists carved the Feathered Serpent on buildings and ornaments worn in ritual.'],
    variants: ['Landa wrote as a colonial friar and must be read critically; Kukulkan should not take on every deed of Quetzalcoatl or the K’iche’ Q’ukumatz.'],
    sources: [
      source('landa', 'Diego de Landa — Relación de las cosas de Yucatán, translated by William Gates', 'https://sacred-texts.com/nam/maya/ybac/ybac10.htm', 'primary'),
      source('chichen', 'National Museum of the American Indian — Chichen Itza', 'https://maya.nmai.si.edu/gallery/chichen-itza'),
      source('ornaments', 'The Met — feathered serpent face ornaments', 'https://www.metmuseum.org/art/collection/search/722156'),
    ],
  },
  guanyin: {
    identity: 'Guanyin is the Chinese name of Avalokiteshvara, the Buddhist bodhisattva of compassion, not a creator god or a conqueror.',
    worldview: ['Compassion answers the suffering of particular beings. Guanyin’s many forms show that responsiveness, and serve the path to liberation, not the growth of an empire.'],
    stories: [
      story('The Universal Gate',
        'Chapter 25 of the Lotus Sutra says that beings in danger who call on Guanyin are freed from fear and harm. It is a teaching on compassionate response.',
        'lotus'),
      story('Hands that see suffering',
        'Chinese thousand-armed images set eyes in Guanyin’s palms, to see suffering and to help in many ways. Amitabha Buddha often appears above.',
        'arms'),
    ],
    relationships: [
      relation('Amitabha', 'The Buddha shown with Guanyin in many images.'),
      relation('Beings in distress', 'Those whose cries Guanyin hears.'),
    ],
    symbols: [
      symbol('Eyes in the palms', 'Seeing joined to helping.'),
      symbol('Many arms', 'Many ways to help.'),
      symbol('Vase and willow', 'The pure water of compassion.'),
    ],
    practice: ['Devotion includes recitation, offerings and rites of compassionate aid; a dated Ming painting was made for such a rite.'],
    variants: ['Guanyin’s forms vary in gender and in the number of heads and arms; the bodhisattva is not a Shinto kami or every Asian mercy goddess.'],
    sources: [
      source('lotus', 'City of Ten Thousand Buddhas — Lotus Sutra, chapter 25', 'https://www.cttbusa.org/dfs25/dfs25.asp', 'primary'),
      source('arms', 'National Museum of Asian Art — thousand-armed Guanyin', 'https://asia.si.edu/explore-art-culture/collections/search/edanmdm%3Afsg_F1917.110/'),
      source('ritual', 'The Met — Guanyin by Zhou Bangzhang', 'https://www.metmuseum.org/art/collection/search/811172'),
    ],
  },
  tangaroa: {
    identity: 'Tangaroa is the atua of the sea in Māori tradition. This dossier follows Māori accounts, not every Polynesian figure of a similar name.',
    worldview: ['The sea gives life and takes it. Te Ara notes that “god of the sea” only partly captures Tangaroa’s many moods, and genealogy binds sea creatures to people and their duties.'],
    stories: [
      story('The descendants part ways',
        'In one genealogy Tangaroa is a child of Ranginui and Papatūānuku. Through his son Punga come Ikatere, whose line goes to the sea as fish, and Tūtewehiwehi, whose line goes inland as reptiles.',
        'fish'),
      story('Carving comes from the sea',
        'Ruatepupuke enters Tangaroa’s undersea house to rescue his son, sets it alight and brings its carved posts back to the human world, the origin of carving.',
        'carving'),
    ],
    relationships: [
      relation('Ranginui and Papatūānuku', 'His parents in a widely known genealogy.'),
      relation('Punga', 'Ancestor of fish and reptiles.'),
      relation('Ruatepupuke', 'Brings carving from the sea.'),
    ],
    symbols: [
      symbol('Fish', 'Living descendants in a sacred genealogy.'),
      symbol('Carved posts', 'Taken from the undersea house.'),
      symbol('First catch', 'Returned to the sea as an offering.'),
    ],
    practice: ['Māori fishing customs include karakia and returning the first fish, a relationship with Tangaroa rather than ownership of the sea.'],
    variants: ['Some traditions make Tangaroa the husband of Papatūānuku and rival of Ranginui; genealogies vary by community.'],
    sources: [
      source('fish', 'Te Ara — Tangaroa and the genealogy of fish', 'https://teara.govt.nz/en/te-hi-ika-maori-fishing/page-1', 'scholarship'),
      source('carving', 'Te Ara — Tangaroa, the sea', 'https://teara.govt.nz/en/tangaroa-the-sea', 'scholarship'),
      source('practice', 'Te Ara — Māori fishing', 'https://teara.govt.nz/en/te-hi-ika-maori-fishing', 'scholarship'),
    ],
  },
  itzamna: {
    identity: 'Itzamna, written Itzamnaaj for Classic Maya art, is an aged sky god of priestly knowledge. The reading of his ancient name is still debated.',
    worldview: ['Maya gods have histories told in images and inscriptions. A colonial name cannot always be matched to an older figure with certainty.'],
    stories: [
      story('The great celestial bird',
        'A Maya whistling vessel shows a majestic bird linked with the aged sky god, and with stories of a young solar hero who confronts it. The bird may be his form, his companion or his foe.',
        'bird'),
      story('Divine ancestry at Copan',
        'Copan’s Rosalila temple sets the founding king K’inich Yax K’uk’ Mo’ among images of the celestial bird, joining kingship, sacred ancestry and architecture.',
        'copan'),
    ],
    relationships: [
      relation('The Principal Bird Deity', 'Linked with Itzamna in ways scholars still debate.'),
      relation('K’inich Yax K’uk’ Mo’', 'Copan’s founding king.'),
    ],
    symbols: [
      symbol('Aged face', 'His main identifying feature.'),
      symbol('Great bird', 'His bird form or companion.'),
      symbol('Name glyph', 'Evidence of his ancient name, not fully read.'),
    ],
    practice: ['Royal monuments and painted vessels tie divine stories to ceremony and rule, and are read alongside inscriptions.'],
    variants: ['Classic Maya evidence spans many cities and centuries; the colonial Itzamna and every earlier bird image are not one unchanging figure.'],
    sources: [
      source('bird', 'The Met — Maya whistling vessel and the Principal Bird Deity', 'https://www.metmuseum.org/art/collection/search/310542'),
      source('copan', 'National Museum of the American Indian — Copan', 'https://maya.nmai.si.edu/gallery/copan'),
      source('name', 'The Met — Lives of the Gods, visiting guide', 'https://www.metmuseum.org/fr/exhibitions/gods-divinity-maya-art/visiting-guide'),
    ],
  },
  inti: {
    identity: 'Inti is the Sun of Inca religion, divine ancestor of the ruling line and a presence in the seasons of Andean life.',
    worldview: ['Descent from the Sun tied the ruling line to the ordering of its homeland, and the Sun’s yearly cycle linked public ceremony with the farming year.'],
    stories: [
      story('The children sent from the lake',
        'Inti sends Manco Capac and Mama Ocllo from Lake Titicaca to found an ordered human community. Their journey ends at Cuzco, and Manco Capac becomes the first Inca.',
        'children'),
      story('Where the staff sinks',
        'In a related version the pair carry a golden staff and are told to settle where it sinks into the ground. It sinks at Cuzco.',
        'staff'),
    ],
    relationships: [
      relation('Manco Capac and Mama Ocllo', 'The children he sends to found Cuzco.'),
      relation('Tiqzi Wiracocha', 'Maker of the Sun in the Smithsonian’s account.'),
      relation('The Inca rulers', 'Who claimed descent from the Sun.'),
    ],
    symbols: [
      symbol('Sun', 'His visible form.'),
      symbol('Golden staff', 'The sign that chose Cuzco.'),
      symbol('Solstice', 'The turning point of his great feast.'),
    ],
    practice: ['Inti Raymi honours the Sun at the southern winter solstice with processions, dance and feasting that vary between communities.'],
    variants: ['Modern Cuzco’s pageant is not a record of every Inca rite, and Inti is distinct from the creator Wiracocha and local sacred powers.'],
    sources: [
      source('children', 'National Museum of the American Indian — Children of the Sun', 'https://americanindian.si.edu/inkaroad/ancestors/creationstories/children-sun.html'),
      source('staff', 'National Museum of the American Indian — Inka activity guide', 'https://americanindian.si.edu/sites/1/files/pdf/education/Inka-activity-guide.pdf'),
      source('festival', 'National Museum of the American Indian — reciprocity and Inti Raymi', 'https://americanindian.si.edu/nk360/inka-water/reciprocity/reciprocity'),
      source('garcilaso', 'Garcilaso de la Vega — Royal Commentaries of Peru, translated by Paul Rycaut', 'https://archive.org/details/royalcommentarie00vega', 'primary'),
    ],
  },
  huitzilopochtli: {
    identity: 'Huitzilopochtli is the patron god of the Mexica, linked with war, the sun and their migration to Tenochtitlan.',
    worldview: ['His stories tie the people’s identity to journey, conflict and a sacred centre. They belong to Mexica religion, not to every people called Aztec.'],
    stories: [
      story('Birth at Coatepec',
        'When Coatlicue is found pregnant, her daughter Coyolxauhqui and her sons turn against her. Huitzilopochtli is born armed and defeats them; the carved Coyolxauhqui stone lay at the foot of his temple.',
        'birth', 'codex'),
      story('The patron on the migration',
        'Migration traditions tell how Huitzilopochtli led the people from Aztlan, his image carried by priests, and gave them the name Mexica along the way.',
        'migration'),
    ],
    relationships: [
      relation('Coatlicue', 'His mother.'),
      relation('Coyolxauhqui', 'His sister and enemy at Coatepec.'),
      relation('Tlaloc', 'Holder of the other shrine on the Templo Mayor.'),
    ],
    symbols: [
      symbol('Hummingbird', 'Part of his name and imagery.'),
      symbol('Coatepec', 'The serpent mountain his temple stood for.'),
      symbol('Carried image', 'His presence on the migration.'),
    ],
    practice: ['The Templo Mayor put his cult at the centre of Tenochtitlan; its war and offerings should be neither hidden nor sensationalised.'],
    variants: ['Colonial sources preserve Mexica traditions through changing politics, and his solar role does not make him the same as Tonatiuh.'],
    sources: [
      source('birth', 'INAH — the Templo Mayor and the Coatepec story', 'https://inah.gob.mx/zonas/zona-arqueologica-templo-mayor'),
      source('migration', 'M. Coe and R. Koontz, Mexico (hosted by INAH)', 'https://deas.inah.gob.mx/pdf/biblioteca/repositorio/repositorio%2821040%29-4563.pdf', 'scholarship'),
      source('solar', 'INAH — solar and Huitzilopochtli imagery', 'https://lugares.inah.gob.mx/en/node/5011'),
      source('codex', 'Library of Congress — Florentine Codex, Book III, The Origin of the Gods', 'https://www.loc.gov/item/2021667848/', 'primary'),
    ],
  },
  perun: {
    identity: 'Perun is the Slavic thunder god best attested in Kyivan Rus’, where he guarded warriors’ oaths and princely power.',
    worldview: ['The written evidence is scarce: it records public worship and sworn treaties, not a cycle of myths, and most of it comes from Christian authors describing an older or rival faith.'],
    stories: [
      story('The oath with Byzantium',
        'In the treaties with Byzantium the chronicle sets the Rus’ who swear by Perun beside those who swear as Christians. His name binds a public promise.',
        'perun', 'conversion'),
      story('The idol cast into the river',
        'Volodymyr sets up a wooden Perun with a silver head and golden moustache in Kyiv, and after his baptism has it dragged away and thrown into the Dnipro.',
        'perun', 'chronicle'),
    ],
    relationships: [
      relation('Volodymyr', 'The prince who raised and then removed the Kyiv idol.'),
      relation('Warriors', 'Who swore their oaths by Perun.'),
      relation('Saint Elijah', 'Who took over some thunder lore in later folk belief.'),
    ],
    symbols: [
      symbol('Thunder and lightning', 'His best-attested domain.'),
      symbol('Silver head and golden moustache', 'The Kyiv idol in the chronicle.'),
    ],
    practice: ['The sources attest oaths and public cult but not enough detail to reconstruct a full ceremony.'],
    variants: ['The detailed Perun and Veles combat myth is a scholarly reconstruction from fragments, not a preserved Slavic text.'],
    sources: [
      source('perun', 'Encyclopedia of Ukraine — Perun', 'https://www.encyclopediaofukraine.com/display.asp?linkpath=pages%5CP%5CE%5CPerun.htm', 'scholarship'),
      source('conversion', 'Encyclopedia of Ukraine — Christianization of Ukraine', 'https://www.encyclopediaofukraine.com/display.asp?linkpath=pages%5CC%5CH%5CChristianizationofUkraine.htm', 'scholarship'),
      source('chronicle', 'Cambridge — treaties with the Greeks and Rus’ religion', 'https://www.cambridge.org/core/books/abs/beginnings-of-russian-history/treaties-with-the-greeks-and-russian-heathenism/637AE366E2D9825D50E48FF3CD5A3780', 'scholarship'),
      source('primary', 'University of Oregon — excerpts from the Russian Primary Chronicle', 'https://pages.uoregon.edu/kimball/chronicle.htm', 'primary'),
    ],
  },
};
