// Original, source-linked paraphrases. Traditional accounts are distinguished from game fiction.
const source=(id,title,url,kind='museum')=>({id,title,url,kind});
const story=(title,text,...sourceIds)=>({title,text,sourceIds});
const relation=(name,role)=>({name,role});
const symbol=(name,meaning)=>({name,meaning});
const adaptation='Aurevale, its faction name, military units, numerical bonuses and champion powers are inventions for Pre-Genesis. They are not claims about this tradition or its practitioners.';

export const LORE_WORLD={
vishnu:{
 identity:'Vishnu is a major Hindu deity associated with sustaining cosmic order; in Vaishnava traditions he is revered as the supreme divinity.',
 worldview:['Preservation is an active task. Vishnu takes forms suited to a world in danger, so an avatar is more than a different costume for the same warrior. Images also place him beyond ordinary time, resting between the destruction of one world and the emergence of another.'],
 stories:[story('The ocean between worlds','Vishnu rests on the serpent Shesha in the primordial waters. A lotus associated with him bears Brahma, the creator. A nineteenth-century Bengali image places Lakshmi at his feet and includes Narada, Garuda and other attendants, bringing several devotional relationships into one scene.','ocean'),story('Varaha restores the earth','As Varaha, the boar avatar, Vishnu rescues the earth from beneath the ocean. A Guler painting shows this cosmic rescuer in battle, riding Garuda. The episode concerns restoration of a threatened world, rather than conquest for its own sake.','varaha')],
 relationships:[relation('Lakshmi','Divine consort associated with prosperity.'),relation('Shesha','The many-headed serpent who supports his cosmic repose.'),relation('Garuda','His avian vehicle and attendant.')],
 symbols:[symbol('Discus','A weapon used by Vishnu and his avatars.'),symbol('Lotus','Connects cosmic repose with creation.'),symbol('Boar','Identifies Varaha, the earth-restoring avatar.')],
 practice:['Devotional images may combine avatars and attendants to express a particular community’s understanding of Vishnu. The Kashmiri Vaikuntha form, for example, combines human, lion and boar faces.'],
 variants:['Avatar lists, theological priorities and regional images differ. A Bengali devotional print and a Kashmiri Vaikuntha image should not be treated as interchangeable instructions for every Vaishnava tradition.'],adaptation,
 sources:[source('ocean','The Met: Vishnu Narayana on Shesha','https://www.metmuseum.org/art/collection/search/78252'),source('varaha','The Met: Vishnu as Varaha','https://www.metmuseum.org/art/collection/search/37953'),source('vaikuntha','The Met: Vaikuntha Vishnu','https://www.metmuseum.org/art/collection/search/38515')]
},
shiva:{
 identity:'Shiva is a major Hindu deity whose traditions bring together asceticism, household life, cosmic transformation and liberation.',
 worldview:['Calling Shiva only a destroyer misses the balance visible in Nataraja, the Lord of Dance: creation, preservation and dissolution form a continuous cycle. The image also offers refuge to the devotee within that cycle.'],
 stories:[story('The dance within the flames','In the Chola Nataraja image, Shiva dances inside a ring of fire. One hand holds a drum associated with the first sound of creation; another carries destructive fire. His planted foot subdues the figure of delusion, while the raised foot and pointing hand offer a path of refuge.','dance'),story('The poison from the ocean','When gods and asuras churn the ocean for its treasures, dangerous poison appears as well. In the British Museum’s painted account, Shiva swallows it while Parvati and the gods watch; a blue mark at his throat identifies the act. The same cosmic undertaking produces both abundance and peril.','churning')],
 relationships:[relation('Parvati','His divine consort, present in the ocean-churning painting.'),relation('Vishnu','Another participant in narratives of cosmic preservation; not simply a permanent enemy.')],
 symbols:[symbol('Damaru','The small drum associated with creation in the dance.'),symbol('Flame','Dissolution within the cosmic cycle.'),symbol('Raised foot','Refuge and release in Nataraja imagery.')],
 practice:['A bronze Nataraja is a sacred image, not merely a diagram of combat abilities. Its posture and hand gestures communicate the relationship between cosmic activity and the devotee’s hope for liberation.'],
 variants:['Shaiva traditions differ in theology and ritual. Nataraja is one specific form, and the meaning of its gestures should not be generalized to every image of Shiva.'],adaptation,
 sources:[source('dance','The Met: Shiva as Nataraja','https://www.metmuseum.org/art/collection/search/39328'),source('churning','British Museum: The churning of the ocean','https://www.britishmuseum.org/collection/object/A_2007-3005-7')]
},
brahma:{
 identity:'Brahma is the Hindu creator deity, commonly represented with four faces. He is distinct from Brahman, the philosophical term for ultimate reality.',
 worldview:['Creation appears within recurrent cosmic time rather than as a single political founding. Brahma’s four faces express a comprehensive presence, while his books and ritual implements connect the formation of the world with sacred knowledge.'],
 stories:[story('A lotus above the cosmic waters','In a creation account presented by the National Museum of Asian Art, a lotus emerges from Vishnu as he rests after a cosmic flood. Brahma appears upon it and brings forth the ordered world, its beings and its teachings. Creation therefore follows a period of dissolution.','creation'),story('The creator as sacred musician','An eighteenth-century Mankot painting presents Brahma as a raga, a musical personification. His four heads share a crown; his hands hold a water vessel, rosary, Vedic book and sacred grass. This is an artistic interpretation of divine knowledge, not an additional account of a battle.','raga')],
 relationships:[relation('Vishnu','The lotus-born creation account connects Brahma with Vishnu’s cosmic repose.'),relation('Saraswati','Appears as his consort in a Thanjavur painting; other regional relationships also exist.')],
 symbols:[symbol('Four faces','A visual expression of universality.'),symbol('Hamsa','The goose or swan-like divine vehicle.'),symbol('Book and water vessel','Knowledge and ritual action.')],
 practice:['Brahma appears in Indian and Southeast Asian sacred art. A Cambodian sculpture and a north Indian painting show that the same deity can be represented through distinct regional artistic languages.'],
 variants:['His role within creation stories does not imply that all Hindu communities give him the same devotional prominence. The Brahma–Saraswati pairing is attested, but it is not the only regional arrangement of divine families.'],adaptation,
 sources:[source('creation','National Museum of Asian Art: Vishnu’s Cosmic Ocean','https://asia.si.edu/accessibility/vishnus-cosmic-ocean-accessible-exhibition-text/'),source('raga','The Met: Raga Brahma','https://www.metmuseum.org/art/collection/search/825648'),source('faces','The Met: Cambodian Brahma','https://www.metmuseum.org/art/collection/search/38265'),source('couple','British Museum: Brahma and Sarasvati','https://www.britishmuseum.org/collection/object/A_1962-1231-0-13-28')]
},
saraswati:{
 identity:'Saraswati is a Hindu goddess of knowledge, language, music and the arts, with early associations with a sacred river.',
 worldview:['The relationship between flowing water and learning is part of her religious history, not a license to collapse every river goddess into one figure. Her images join cultivated skill, sacred study and disciplined worship.'],
 stories:[story('From sacred river to learning','The Vedic Saraswati is associated with a river in the northwestern subcontinent. Later devotional images emphasize knowledge and artistic expression. This is a development across religious history, rather than one universally narrated transformation scene.','wisdom'),story('The goddess with the vina','Ravi Varma’s late nineteenth-century print seats Saraswati beside a lotus pond. She plays the vina, holds a manuscript and rosary, and is accompanied by a peacock rather than the more usual swan. The objects identify music, learning and religious practice within a single image.','print')],
 relationships:[relation('Brahma','Her consort in many images, including a Thanjavur painting.'),relation('Vishnu and Lakshmi','Some eastern Indian sculptures place Saraswati beside Vishnu with Lakshmi, demonstrating regional variation.')],
 symbols:[symbol('Vina','Music and the arts.'),symbol('Manuscript','Learning and the preservation of knowledge.'),symbol('Rosary','Religious discipline and recitation.')],
 practice:['Devotion to Saraswati gives scholarship and artistic training sacred significance. Her iconography makes study visible through instruments and books, rather than through an invented arsenal.'],
 variants:['Benzaiten in Japan developed through Buddhist transmission of Saraswati traditions and has a distinct history. Regional consort arrangements also differ; neither the Japanese form nor a Bengali family grouping should overwrite other traditions.'],adaptation,
 sources:[source('wisdom','National Museum of Asian Art: Wisdom of the Goddess','https://asia.si.edu/whats-on/exhibitions/wisdom-of-the-goddess/'),source('print','The Met: Saraswati, goddess of learning','https://www.metmuseum.org/art/collection/search/78265'),source('regional','The Met: Vishnu with Lakshmi and Sarasvati','https://www.metmuseum.org/art/collection/search/38120'),source('japan','British Museum: Benzaiten','https://www.britishmuseum.org/collection/object/A_1924-0714-0-2')]
},
lakshmi:{
 identity:'Lakshmi, also called Shri, is a Hindu goddess of auspiciousness, prosperity and abundance, closely associated with Vishnu.',
 worldview:['Prosperity in her imagery includes fertility, flourishing life and well-being. Reducing her to a treasury bonus would discard the water, plants and living creatures through which artists express abundance.'],
 stories:[story('Emergence from the ocean','In a painted account of the cosmic churning, Lakshmi appears among the treasures brought from the sea. The gods and asuras have undertaken an immense cooperative effort, but its results include both precious gifts and dangerous poison. Her appearance belongs within that larger cosmic event.','churning'),story('The elephants’ offering','Gaja-Lakshmi images show elephants honoring or bathing the goddess. In a Ravi Varma print, a white elephant offers a garland while Lakshmi stands on a lotus; swans and young birds reinforce the setting’s fertility. The image develops an established devotional theme through a modern printing medium.','print')],
 relationships:[relation('Vishnu','Divine consort; she attends his cosmic repose.'),relation('Kamalatmika','A Tantric form associated with Lakshmi, represented on a lotus with celestial elephants.')],
 symbols:[symbol('Lotus','A principal seat and attribute of the goddess.'),symbol('Elephants with water','The Gaja-Lakshmi theme of lustration and abundance.'),symbol('Garland','An offering of honor in the cited print.')],
 practice:['Her imagery circulated through temple sculpture, painting and inexpensive devotional prints. These media brought familiar religious subjects into different settings and audiences.'],
 variants:['Kamalatmika belongs to a particular Tantric context. Bengali festival images may present Lakshmi within Durga’s family, while other traditions give different relationships; one arrangement is not a universal genealogy.'],adaptation,
 sources:[source('churning','British Museum: The churning of the ocean','https://www.britishmuseum.org/collection/object/A_2007-3005-7'),source('print','The Met: Lakshmi','https://www.metmuseum.org/art/collection/search/78264'),source('kamala','The Met: Goddess Kamalatmika','https://www.metmuseum.org/art/collection/search/849494'),source('family','British Museum: Bengali Durga śara','https://www.britishmuseum.org/collection/object/A_1989-0204-0-42')]
},
durga:{
 identity:'Durga is a powerful Hindu goddess, especially central to Shakta traditions that revere the Divine Mother as supreme.',
 worldview:['The Devi Mahatmya presents divine feminine power as capable of restoring a cosmos that the gods cannot secure by themselves. Devotion also approaches the formidable goddess as a mother who returns to her family.'],
 stories:[story('Mahishasura, the buffalo adversary','Durga confronts Mahishasura, whose changing forms include a buffalo. A Kolkata print shows the defeated buffalo and the adversary’s human form at her feet, while her many hands carry weapons. The scene expresses a decisive victory of the goddess over a threat to divine order.','mahisha'),story('Shumbha and Nishumbha','The Devi Mahatmya’s later cycle concerns the brothers Shumbha and Nishumbha, who seize the gods’ domains. The goddess and her manifestations confront their forces. Belur Math presents these episodes as part of the scripture recited and interpreted in Durga worship, not as unrelated monster-hunting tales.','puja')],
 relationships:[relation('Parvati and Shiva','Durga is associated with Parvati and Shiva in many traditions.'),relation('Lakshmi, Saraswati, Ganesha and Karttikeya','Appear with Durga in Bengali festival family groupings.')],
 symbols:[symbol('Lion','Her vehicle in many images.'),symbol('Multiple weapons','The many powers she brings to the conflict.'),symbol('Buffalo','Identifies the Mahishasura episode.')],
 practice:['Durga Puja combines worship, scriptural recitation and carefully made images. Bengali clay tableaux often emphasize the goddess’s homecoming as well as her victory.'],
 variants:['The Bengali presentation of Lakshmi and Saraswati as Durga’s children is regional. Durga, Kali and other manifestations are related differently across texts and communities; they should not become interchangeable game portraits.'],adaptation,
 sources:[source('mahisha','The Met: Sri Sri Durga','https://www.metmuseum.org/art/collection/search/786759'),source('puja','Belur Math: Durga Puja and the Devi Mahatmya','https://belurmath.org/durga-puja-at-belur-math/','tradition'),source('family','British Museum: Bengali Durga śara','https://www.britishmuseum.org/collection/object/A_1989-0204-0-42')]
},
amaterasu:{
 identity:'Amaterasu-Omikami is a Japanese kami associated with the sun and with the ancestry of the imperial family.',
 worldview:['Light, cultivated fields, weaving and right relationships are connected in the classical narratives. Her withdrawal harms the whole world, so the restoration of light requires the work of a community of kami.'],
 stories:[story('The heavenly rock cave','After Susanoo’s destructive behavior, Amaterasu withdraws into a cave and the world loses its light. The other kami prepare a mirror, jewels and a performance outside. Their laughter draws her attention; when she looks out, she is brought from the cave and daylight returns.','cave'),story('Finding a home at Ise','Ise Jingu recounts how Yamatohime-no-mikoto searched for an enduring place to enshrine Amaterasu after the sacred mirror had left the imperial palace. The search ends at Ise. This shrine foundation tradition concerns worship in a particular place, not a second cosmic creation.','ise')],
 relationships:[relation('Susanoo','Her brother in the classical accounts, whose actions provoke the cave withdrawal.'),relation('Ninigi','Her grandson, associated with the descent of imperial regalia.'),relation('Toyouke','The kami at Ise’s Outer Shrine who provides sacred food.')],
 symbols:[symbol('Mirror','A sacred symbol enshrined at Ise and an object in the cave narrative.'),symbol('Sunlight','The life-giving presence lost during her withdrawal.'),symbol('Jewels','Part of the cave’s lure and the imperial regalia tradition.')],
 practice:['Ise’s Inner Shrine is dedicated to Amaterasu; its sacred mirror is not an object ordinarily displayed to visitors.'],
 variants:['The Kojiki, Nihon Shoki and shrine traditions do not offer a single identical account. “Kami” has a wider range than the game category “god or goddess.”'],adaptation,
 sources:[source('cave','National Museum of Asian Art: Arts of Japan, Amaterasu','https://docent.asia.si.edu/wp-content/uploads/Arts-of-Japan.pdf'),source('ise','Ise Jingu: About the shrines and their history','https://www.isejingu.or.jp/en/about/index.html','tradition')]
},
susanoo:{
 identity:'Susanoo is a Japanese kami whose classical stories include disruption in heaven, protection in Izumo and authority in the otherworld.',
 worldview:['He cannot be reduced to either a benevolent weather deity or a villain. The same narrative figure damages the ordered heavenly realm and saves a family threatened by a serpent. Place, genealogy and changing circumstances matter.'],
 stories:[story('A pledge followed by disorder','Susanoo visits Amaterasu in heaven and undergoes a pledge ritual when his intentions are questioned. After declaring victory, he commits destructive acts that cause her to withdraw into the heavenly cave. He is expelled, marking a limit on behavior even among the kami.','susanoo'),story('Kushinadahime and the serpent','In Izumo, Susanoo saves Kushinadahime from Yamata-no-Orochi. He turns her into a comb for safekeeping in his hair, defeats the serpent and obtains the sword Kusanagi. He then establishes a dwelling at Suga and marries her. The Kojiki associates their wedding with a foundational waka verse.','kushi','susanoo')],
 relationships:[relation('Amaterasu','His sister in classical accounts.'),relation('Kushinadahime','The woman he rescues and marries.'),relation('Ashinazuchi and Tenazuchi','Kushinadahime’s parents, associated with the Suga dwelling.')],
 symbols:[symbol('Comb','The transformed Kushinadahime in the rescue episode.'),symbol('Kusanagi sword','Discovered in connection with the defeated serpent.'),symbol('Eightfold fence','An image in the wedding poem associated with Suga.')],
 practice:['Izumo traditions preserve specific sacred places and family relationships. The wedding poem connects Susanoo with poetry as well as danger and force.'],
 variants:['Kokugakuin’s account distinguishes the Kojiki’s stories from other textual traditions. Modern shorthand such as “storm god” does not encompass every attested role.'],adaptation,
 sources:[source('susanoo','Kokugakuin University: Susanoo','https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9152','scholarship'),source('kushi','Kokugakuin University: Kushinadahime','https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9366','scholarship')]
},
inari:{
 identity:'Inari is a Japanese kami tradition associated with food, rice and prosperity. At Fushimi Inari Taisha, Inari Okami encompasses five enshrined kami.',
 worldview:['Food and livelihood connect agriculture, household protection and commercial success. Inari’s many local forms reflect the different communities that established shrines rather than a uniform personality with one fixed biography.'],
 stories:[story('The rice-cake target','A foundation account preserved from the Yamashiro provincial record tells of Hata no Irogu shooting at a rice cake. It becomes a white bird and flies to a mountain; rice grows where it lands. The story connects the shrine’s name and place with the value of grain.','faith'),story('The rice-bearing visitor','In a later Buddhist-linked image, Inari appears as an old man carrying rice and promising protection to Kukai’s Toji temple. This is evidence of historical combinations between kami and Buddhist worship, not proof that all Inari shrines share one doctrine.','faith')],
 relationships:[relation('Ukanomitama','A rice-associated kami central to Fushimi’s enshrinement.'),relation('Kukai','The Buddhist teacher associated with the Toji protection tradition.'),relation('White foxes','Revered messengers or attendants; Inari is not simply a fox.')],
 symbols:[symbol('Rice','Food, sustenance and the foundation narrative.'),symbol('White fox','A messenger, distinguished from the enshrined kami.'),symbol('Vermilion shrine color','Associated at Fushimi with protection and abundant harvests.')],
 practice:['Fushimi’s own explanation emphasizes nourishment, clothing, shelter and a flourishing life. Its five enshrined kami express different virtues within Inari Okami.'],
 variants:['Some forms combine Inari with Buddhist Dakiniten; others do not. Descriptions of gender, appearance and divine identity must be tied to a particular tradition.'],adaptation,
 sources:[source('faith','Kokugakuin University: Inari Shinko','https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9027','scholarship'),source('fushimi','Fushimi Inari Taisha: Enshrined deity','https://inari.jp/en/saijin/','tradition'),source('fox','Fushimi Inari Taisha: Questions about foxes and shrine color','https://inari.jp/en/faq/','tradition')]
},
oshun:{
 identity:'Oshun, or Ọṣun, is a Yoruba orisha associated with the Ọṣun River, fertility and sustaining relationships between people and sacred places.',
 worldview:['The river is not merely a resource controlled by a distant character. At Osogbo, its grove, shrines, art and ritual community form a living sacred landscape. Local traditions connect well-being with obligations to the orisha.'],
 stories:[story('The river and Oba','The Nigerian nomination for the Osun-Osogbo World Heritage site records a tradition in which Osun becomes a river after a disagreement involving Oba, another wife of Sango. This is a locally documented account; it should not be presented as the single Yoruba explanation of her origins.','nomination'),story('A grove renewed','In the twentieth century, local artists and worshippers renewed threatened shrines at Osogbo. Susanne Wenger worked with Yoruba artists including Adebisi Akanji. Their work did not create a forgotten fantasy cult: it helped sustain an existing religious community and its sacred landscape.','grove','film')],
 relationships:[relation('Sango and Oba','Connected with Osun in the river-origin account recorded at Osogbo.'),relation('The Osogbo community','Maintains reciprocal ritual relationships with the river and grove.')],
 symbols:[symbol('River water','A living sacred presence associated with fertility and protection.'),symbol('Sacred grove','The setting of shrines, worship and communal memory.')],
 practice:['The annual festival renews connections among the goddess, the community and the grove. Shrines to other orisha also stand there; the sacred landscape does not imply that Osun rules a homogeneous “African pantheon.”'],
 variants:['Yoruba traditions and their Atlantic diasporas have related but distinct histories. This entry centers Osogbo evidence and does not substitute it for every practice involving Oshun or Oxum.'],adaptation,
 sources:[source('nomination','Nigeria: Osun-Osogbo World Heritage nomination','https://whc.unesco.org/uploads/nominations/1118.pdf','tradition'),source('grove','UNESCO: Osun-Osogbo Sacred Grove','https://whc.unesco.org/en/list/1118','scholarship'),source('film','The Met: Osun-Osogbo Sacred Grove','https://www.metmuseum.org/ko/perspectives/osun-osogbo')]
},
ogun:{
 identity:'Ogun is the Yoruba orisha of iron and the dangerous, useful capacities of metalworking, tools and weapons.',
 worldview:['Iron can clear a path, cultivate land, enable healing or inflict injury. Ogun’s significance therefore extends beyond warfare to the practical work on which communities depend. A tool’s usefulness does not remove the need to handle its power responsibly.'],
 stories:[story('Clearing the way in performance','A Smithsonian field photograph from Lagos records Arabi Ajigbale, dressed in the iron deity’s cloths, sweeping the market before other masqueraders enter. This documented performance makes the opening of a path visible. It is evidence of a particular ritual setting, not a transcript of every Ogun creation story.','path'),story('Iron in the healer’s work','A Yoruba herbalist’s iron staff in the National Museum of African Art connects Ogun with Osanyin and Erinle. Iron blades open routes through woodland and cut the plants used by healers. The object shows how distinct sacred powers cooperate through skilled human work.','staff')],
 relationships:[relation('Blacksmiths and metalworkers','Craft specialists whose work falls within Ogun’s domain.'),relation('Osanyin and Erinle','Healing deities connected with the cited herbalist’s staff.')],
 symbols:[symbol('Iron blade','A means of clearing, cutting and making.'),symbol('Tools','The practical power of iron beyond weapons.'),symbol('Cleared path','A ritual image of enabling passage and action.')],
 practice:['Museum archives document Ogun festivals, shrines and performances in specific Yoruba communities. These records show active practice rather than a closed list of ancient tales.'],
 variants:['Oral narratives and ritual obligations vary by community. This entry does not turn an unverified version of the Ire story into universal canon or treat every iron implement as Ogun’s exclusive emblem.'],adaptation,
 sources:[source('path','Smithsonian: Arabi Ajigbale clears the way','https://www.si.edu/object/archives/components/sova-eepa-1992-028-ref3598'),source('staff','National Museum of African Art: Herbalist’s staff','https://www.si.edu/object/herbalists-staff%3Anmafa_76-3-4'),source('cosmos','National Museum of African Art: Areogun’s bowl','https://africa.si.edu/collection/selected-artwork/1712')]
},
shango:{
 identity:'Shango, or Sango, is a Yoruba orisha of thunder and lightning, remembered in Oyo traditions as a deified king.',
 worldview:['Royal charisma does not guarantee right conduct. Accounts of Sango connect extraordinary power with its consequences, while ritual art places that power within relationships among worshippers, shrines and a community.'],
 stories:[story('The king and uncontrolled power','The Met describes Sango as an ambitious former ruler of Oyo whose fascination with extraordinary powers, including lightning, exceeded his ability to control them. His remembered charisma is inseparable from the tragic effects of misused power. This is not a simple tale of an always-just warrior king.','king'),story('The staff leaves the shrine','At annual festivals, devotees carry ose Sango from shrines and dance with them. Yoruba artists repeatedly reinterpret the staff’s form while retaining its characteristic double axe. The action brings a shrine emblem into public performance rather than turning it into an ordinary battlefield weapon.','staff')],
 relationships:[relation('Oyo kingship','A central setting for traditions of his mortal and divine authority.'),relation('Twins','The Met records traditions in which twins receive Sango’s protection.'),relation('Devotees','Maintain shrines and carry his emblems in ritual dance.')],
 symbols:[symbol('Double axe','The identifying summit of an ose Sango staff.'),symbol('Lightning','A manifestation of formidable divine power.'),symbol('Dance staff','A ritual object linking shrine, artist and worshipper.')],
 practice:['Shrine figures and staffs operate within worship. Their purpose cannot be understood solely from shape or decorative beauty. Twin memorial figures also belong to distinct obligations of family care.'],
 variants:['Oyo traditions, other Yoruba communities and Atlantic diaspora religions preserve related but differing accounts. This entry does not combine their family stories into a single fixed genealogy.'],adaptation,
 sources:[source('king','The Met: Abiyamo figure and Sango','https://www.metmuseum.org/art/collection/search/312182'),source('staff','The Met: Ose Sango by Onakunle Aribikona','https://www.metmuseum.org/art/collection/search/314326'),source('twins','The Met: Twin figure and ritual care','https://www.metmuseum.org/art/collection/search/314456')]
},
dagda:{
 identity:'The Dagda is a powerful figure of the Irish Tuatha De Danann, associated in medieval narrative with abundance, strength, knowledge and music.',
 worldview:['His authority includes feeding a company and commanding a performance, not simply striking an enemy. Medieval tales can make him physically comic while still treating him as immensely capable.'],
 stories:[story('Service under Bres','In Cath Maige Tuired, Bres’s rule reduces the Dagda to building fortifications. The humiliation belongs to a wider failure of kingship and hospitality, against which the Tuatha De organize resistance.','battle'),story('Calling back the harp','After the battle, the Dagda, Lug and Ogma pursue the Fomorians. The Dagda summons his captured harp from a wall, then plays music that produces sorrow, joy and sleep. The recovery joins force, memory and artistic mastery.','harp')],
 relationships:[relation('Brigit','Named as his daughter in Irish texts.'),relation('Lug and Ogma','Companions in the recovery of the harp.'),relation('Bres','The ruler whose demands expose failed hospitality.')],
 symbols:[symbol('Cauldron','An inexhaustible source of satisfaction for a company in the tale.'),symbol('Harp','An instrument whose melodies the Dagda commands.'),symbol('Earthwork','A reminder of the labor imposed under Bres.')],
 practice:['The surviving evidence here is medieval literature recorded in a Christian manuscript culture. It preserves important material about pre-Christian figures without supplying a complete ancient ritual manual.'],
 variants:['Translations differ in spelling and in their treatment of the harp and the harper Uaithne. The tale is not a uniform “Celtic scripture,” and Irish figures should not automatically inherit attributes from every continental or British deity.'],adaptation,
 sources:[source('battle','UCC CELT: Cath Maige Tuired, translated by Elizabeth Gray','https://celt.ucc.ie/document/T300010/','primary'),source('harp','UCC CELT: The Second Battle of Moytura, section 163','https://celt.ucc.ie/published/T300011/text163.html','primary')]
},
lugh:{
 identity:'Lugh, also spelled Lug, is an Irish Tuatha De Danann figure renowned for combining many skills and for leadership in Cath Maige Tuired.',
 worldview:['His distinction is not possession of one craft that everyone else lacks. He can unite the crafts needed by the whole community, making coordination and judgment central to his leadership.'],
 stories:[story('The many-skilled visitor','At Tara, Lug offers successive skills, but the gatekeeper answers that the court already has such specialists. Lug then asks whether it has one person who possesses all those abilities. His admission makes combined expertise the basis of authority.','battle'),story('The fair for Tailtiu','The place-lore of Tailtiu connects an assembly with the woman whose exhausting labor cleared land. Other Irish accounts identify Lug as her foster-son and associate the annual gathering with her commemoration. The festival’s social setting includes fair dealing and restraint, not only contests.','tailtiu','history')],
 relationships:[relation('Tailtiu','His foster-mother in Irish accounts of the commemorative fair.'),relation('Nuadu','The ruler whose court receives the many-skilled visitor.'),relation('The craft specialists','Members of the community whose abilities Lug brings together.')],
 symbols:[symbol('Multiple crafts','The defining feature of his admission to Tara.'),symbol('Assembly ground','A place of commemoration and communal order.'),symbol('Spear','One of the Tuatha De’s celebrated treasures associated with Lug.')],
 practice:['Lughnasadh traditions preserve the importance of seasonal assembly, but a medieval explanation of a festival does not establish every detail of earlier worship.'],
 variants:['Calling Lugh merely a “sun god” obscures the explicit literary emphasis on skill, kingship and obligations to kin. Irish Lug and similarly named continental figures require separate evidence.'],adaptation,
 sources:[source('battle','UCC CELT: The Second Battle of Moytura','https://celt.ucc.ie/document/T300011/','primary'),source('tailtiu','UCC CELT: Metrical Dindshenchas, Tailtiu','https://celt.ucc.ie/published/T106500D/text033.html','primary'),source('history','UCC CELT: Keating’s History of Ireland','https://celt.ucc.ie/document/T100054/','primary')]
},
brigid:{
 identity:'Brigid, or Brigit, is an Irish goddess associated with poetry and skilled knowledge. Medieval evidence must be distinguished from the separate biographies of Saint Brigit of Kildare.',
 worldview:['The surviving references connect inspired speech with healing and metalwork. These are concrete forms of knowledge rather than an undifferentiated power called “magic.” They also show how little of a complete ancient biography survives.'],
 stories:[story('Three Brigits in the glossary','Cormac’s Glossary describes Brigit the poet and names sisters associated with healing and smithwork. This brief learned notice underlies many later accounts of a threefold goddess, but does not itself provide the modern maiden–mother–crone scheme.','glossary'),story('Grief for Ruadan','In Cath Maige Tuired, Ruadan, son of Brigit and Bres, attacks the smith Goibniu and is killed. Brigit mourns him; the narrative associates her lament with the beginning of keening in Ireland. Her loss cuts across the divisions between the fighting peoples.','ruadan')],
 relationships:[relation('The Dagda','Her father in the medieval notices.'),relation('Bres','Father of her son Ruadan.'),relation('Ruadan','The son mourned in the battle narrative.')],
 symbols:[symbol('Poetic speech','An explicitly attested area of her patronage.'),symbol('Smithwork','Associated with a Brigit in the glossary.'),symbol('Lament','The narrative sign of grief for Ruadan.')],
 practice:['Modern devotional communities interpret these fragmentary texts in living ways. Their practices deserve identification as modern tradition, rather than being silently projected into antiquity.'],
 variants:['Saint Brigit’s cross, Kildare miracles and Christian feast belong to a different body of evidence. The relationship between saint and goddess remains debated; this entry does not simply declare one to be the other in disguise.'],adaptation,
 sources:[source('glossary','Clann Bhride: primary passages concerning Brigit','https://clannbhride.org/articles-and-essays/finding-brighid-in-the-ancient-lore/','tradition'),source('ruadan','UCC CELT: The Second Battle of Moytura, section 124','https://celt.ucc.ie/published/T300011/text124.html','primary'),source('debate','University College Cork: Brigit, Saint or Goddess?','https://www.ucc.ie/en/smg/newsevents/','scholarship')]
},
viracocha:{
 identity:'Viracocha, or Tiqzi Wiracocha, is a creator figure in Andean accounts recorded in several forms before and after the Spanish conquest.',
 worldview:['The creation of beings and the ordering of places belong together. Roads, emergence sites and the movement of the creator give the landscape a history. Colonial descriptions preserve valuable testimony but also filter it through outsiders’ religious and political assumptions.'],
 stories:[story('A world ordered after darkness','The National Museum of the American Indian presents Tiqzi Wiracocha as creator of the sun, moon, stars, plants, animals and people, and as the one who laid out the first routes of the Inka road system. Other recorded accounts place creation after an earlier catastrophe.','creator','chronicle'),story('The encounter at Cacha','A colonial narrative describes inhabitants threatening Viracocha at Cacha. Fire descends upon the place; when they recognize his power and appeal to him, the danger is ended. The story explains a sacred locality through an encounter with the creator, but survives in a politically charged colonial text.','chronicle')],
 relationships:[relation('Inti and Mamaquilla','Sun and moon created in the Smithsonian’s account.'),relation('Andean peoples and places','Created and ordered through differing emergence traditions.')],
 symbols:[symbol('Road','Connects creation with the ordering of the inhabited landscape.'),symbol('Lake Titicaca','A major setting in recorded creation accounts.'),symbol('Fire at Cacha','Marks a localized recognition story.')],
 practice:['Sacred narratives cannot be separated from specific Andean places. The roads also served a historical empire; a mythic origin does not replace their human engineering history.'],
 variants:['Wiracocha is not automatically identical with every earlier Andean staff-bearing image. Colonial writers sometimes imposed Christian comparisons; those interpretations are not accepted here as facts about pre-conquest belief.'],adaptation,
 sources:[source('creator','National Museum of the American Indian: Tiqzi Wiracocha','https://americanindian.si.edu/inkaroad/ancestors/creationstories/the-creator.html'),source('chronicle','Sarmiento de Gamboa: Viracocha creation accounts, Markham translation','https://sacred-texts.com/nam/inca/inca01.htm','primary')]
},
nezha:{
 identity:'Nezha is a youthful protector in Chinese religious and literary traditions, also widely called the Third Prince or Santaizi in Taiwan.',
 worldview:['His stories turn on obligations to family and community, the consequences of violent action and the possibility of a transformed life. Buddhist, Daoist, temple and novel traditions give him different settings and responsibilities.'],
 stories:[story('Conflict with the dragon family','In a widely performed narrative, Nezha fights a dragon prince, bringing a threat against his family and community. He gives back his body to his parents to prevent others from bearing the consequences. The episode raises difficult questions of responsibility rather than celebrating unrestrained rebellion.','taiwan','opera'),story('A body made from lotus','An immortal teacher restores Nezha with lotus stems and blossoms. His renewed body allows his story to continue beyond death. The lotus reconstruction is central to the familiar literary cycle, although retellings vary in the events leading to it and the reconciliation that follows.','taiwan')],
 relationships:[relation('Li Jing','His father in the Chinese literary cycle.'),relation('The dragon prince and king','Opponents in the conflict that threatens his community.'),relation('An immortal teacher','Restores him through the lotus body in the cited account.')],
 symbols:[symbol('Fire wheels','A familiar means of movement and an identifying attribute.'),symbol('Magic ring','An identifying weapon or implement of the Third Prince.'),symbol('Lotus','The substance of his reconstructed body.')],
 practice:['Taiwanese temple processions include performances of the Third Prince. Singapore heritage records likewise document temples dedicated to the youthful deity; modern performance is part of a living tradition.'],
 variants:['The novels Fengshen Yanyi and Journey to the West are important witnesses, not a single binding scripture. A modern film’s characterization should not replace temple traditions.'],adaptation,
 sources:[source('taiwan','Taiwan Review: Dancing with the Gods','https://taiwanreview.nat.gov.tw/AMP/Culture/Taiwan-Review/25135/Dancing-with-the-Gods','tradition'),source('opera','Kaohsiung Cultural Center: Nezha opera synopsis','https://english.khcc.gov.tw/PhotoData/PIC1111031.pdf','tradition'),source('symbols','Singapore National Heritage Board: Balestier heritage trail','https://www.nhb.gov.sg/~/media/nhb/files/places/trails/balestier/balestier.pdf','museum')]
},
quetzalcoatl:{
 identity:'Quetzalcoatl, the Feathered Serpent, is a major Mesoamerican divine figure. This entry centers Nahua and Mexica accounts rather than treating every feathered serpent tradition as identical.',
 worldview:['Human life depends on acts that obtain both existence and sustenance. The deity’s wind aspect, Ehecatl, connects breath and movement with the functioning of the cosmos. Historical rulers and priests could also bear related names or titles.'],
 stories:[story('The bones of earlier people','Quetzalcoatl enters the realm of death to recover the bones of a previous humanity from Mictlantecuhtli. Their recovery and an act of divine self-sacrifice make renewed human life possible. The bones link the present world to people of an earlier cosmic age.','bones','wind'),story('Wind sets the heavens moving','In the creation account discussed by Mexico’s National Museum of Anthropology, Ehecatl-Quetzalcoatl blows to set the sun and moon in motion. The episode makes the succession of day and night dependent on a further divine act after the celestial bodies already exist.','wind')],
 relationships:[relation('Mictlantecuhtli','The lord of death from whom ancestral bones are recovered.'),relation('Ehecatl','The wind manifestation, with distinctive imagery.'),relation('Kukulkan','A related Yukatek Feathered Serpent tradition, not a license to merge all narratives.')],
 symbols:[symbol('Feathered serpent','Joins avian plumage with the serpent body.'),symbol('Shell ornaments','Appear on a Mexica sculpted image.'),symbol('Curved staff','An insignia on the museum’s Ehecatl-Quetzalcoatl stela.')],
 practice:['Priestly and royal associations are part of the deity’s history. An image or name therefore needs a cultural and historical context, not only a modern identification label.'],
 variants:['Creation stories, the wind deity and narratives of a ruler called Topiltzin Quetzalcoatl overlap in complex ways. This entry does not turn them into one historically verified biography.'],adaptation,
 sources:[source('bones','British Museum: Stone bust of Quetzalcoatl','https://www.britishmuseum.org/collection/object/E_Am1825-1210-11'),source('wind','Museo Nacional de Antropologia: Estela de Quetzalcoatl','https://mna.inah.gob.mx/detalle_pieza_mes.php?id=344')]
},
tlaloc:{
 identity:'Tlaloc is a central Mexican rain deity whose Mexica worship connects water, agricultural sustenance, mountains and dangerous weather.',
 worldview:['The same powers that nourish crops can destroy them through hail or severe storms. Tlaloc therefore represents an uncertain relationship with water, not a permanently beneficial irrigation spell.'],
 stories:[story('The mountain of sustenance','At Tenochtitlan’s Templo Mayor, the northern sanctuary belonged to Tlaloc. INAH identifies its sacred mountain setting with the store of nourishment, paired with the southern Coatepec of Huitzilopochtli. The temple joined two distinct divine domains at the center of the city.','temple'),story('Water poured onto the earth','The Templo Mayor Museum explains a blue vessel bearing Tlaloc’s face as a container from which water reaches the earth. Its nourishing associations sit beside evidence of appeasement for crop-damaging weather. This is an attested ritual image rather than an invented personal adventure.','museum')],
 relationships:[relation('Huitzilopochtli','His neighboring deity in the paired sanctuaries of the Templo Mayor.'),relation('Agricultural communities','Depend on the rainfall and sustenance with which Tlaloc is associated.')],
 symbols:[symbol('Ringed eyes','A characteristic identifying feature.'),symbol('Fangs and serpent forms','Prominent elements of the face.'),symbol('Water vessel','Expresses rain and the capacity to pour nourishment onto the world.')],
 practice:['Offerings and temple rites sought a workable relationship with powers that could both sustain and threaten life. The archaeological context is essential to interpreting individual objects.'],
 variants:['Rain deities have long histories across Mesoamerica. A Mixtec-made object catalogued as Tlaloc does not make Mixtec, Maya and Mexica religions identical. Chaak is not simply a spelling of Tlaloc.'],adaptation,
 sources:[source('temple','INAH: Templo Mayor and its sacred mountains','https://lugares.inah.gob.mx/es/node/4463'),source('museum','INAH: Templo Mayor Museum, Tlaloc gallery','https://lugares.inah.gob.mx/en/node/5284'),source('mask','The Met: Mixtec rain god mask','https://www.metmuseum.org/art/collection/search/313255')]
},
maui:{
 identity:'Māui is an ancestral trickster and culture hero across several Polynesian traditions. This entry follows Māori accounts from Aotearoa New Zealand.',
 worldview:['His achievements depend on knowledge received from elders as well as audacity. The women and ancestors who supply that knowledge are essential participants, not anonymous sources of equipment.'],
 stories:[story('Fishing up the land','Māui hides in his brothers’ canoe when they try to leave him behind. Far offshore he uses a hook made from his grandmother’s jawbone and raises the great fish identified with the North Island, Te Ika-a-Māui. Some accounts connect the catch with the underwater house of Tonganui.','fish'),story('Knowledge from the elders','Murirangawhenua’s jawbone also assists Māui in slowing Tamanui-te-rā, the sun. In another cycle, his encounters with Mahuika reveal the source of fire. These stories place intergenerational knowledge at the center of achievements often attributed to the hero alone.','elders')],
 relationships:[relation('Taranga','His mother in the Māori accounts summarized by Te Ara.'),relation('Murirangawhenua','His female elder, whose jawbone enables great deeds.'),relation('Mahuika','A female elder associated with fire knowledge.')],
 symbols:[symbol('Jawbone hook','Connects an inherited gift with the fishing-up of land.'),symbol('Canoe','The setting of the brothers’ expedition.'),symbol('The sun','A being whose pace the hero changes.')],
 practice:['Māui narratives connect places, kin relationships and the transmission of knowledge. They are not detachable lists of powers with no responsibility to their communities.'],
 variants:['Māori, Hawaiian, Samoan, Tongan and other Māui cycles differ in genealogy and events. This entry does not merge them or borrow a modern film’s inventions as traditional lore.'],adaptation,
 sources:[source('fish','Te Ara: The North and South islands','https://teara.govt.nz/en/whenua-how-the-land-was-shaped/page-2','scholarship'),source('elders','Te Ara: Kaumatua in early traditions','https://teara.govt.nz/en/kaumatua-maori-elders/page-2','scholarship')]
},
kukulkan:{
 identity:'Kukulkan is a Yukatek Maya name for the Feathered Serpent, especially associated with Chichen Itza and later traditions concerning Mayapan.',
 worldview:['Feathered serpent imagery links terrestrial and celestial domains, but the meanings belong to particular Maya places and communities. Shared imagery across Mesoamerica does not eliminate differences of language, history or ritual.'],
 stories:[story('The lord remembered at Chichen Itza','Diego de Landa recorded a sixteenth-century tradition of a lord called Cuculcan associated with Chichen Itza and the ordering of Mayapan. His informants disagreed about the timing of his arrival. The account is evidence of remembered tradition through a colonial writer, not a settled biography of a historical king.','landa'),story('A serpent of light','At Chichen Itza, changing sunlight and shadow along the pyramid commonly called Kukulkan’s temple create a descending serpent effect. The Smithsonian presents local Maya interpretation of Kukulkan as connecting earth and sky. This is a visible architectural phenomenon with a living interpretive history.','chichen')],
 relationships:[relation('The Itza','A Maya people closely associated with Chichen Itza’s history.'),relation('Quetzalcoatl','A related Nahua Feathered Serpent tradition, named differently and embedded in other accounts.')],
 symbols:[symbol('Feathered serpent','The principal divine image.'),symbol('Serpent heads on architecture','Place the imagery within the city’s monumental spaces.'),symbol('Plumed face ornaments','Objects likely used in ritual at Chichen Itza.')],
 practice:['Maya artists represented the Feathered Serpent in architectural sculpture and ornaments worn by people. These material settings help distinguish ritual practice from generalized fantasy symbolism.'],
 variants:['Landa’s record is colonial and should be read critically. Kukulkan should not simply receive every deed of Quetzalcoatl or the K’iche’ Q’ukumatz.'],adaptation,
 sources:[source('landa','Diego de Landa: Cuculcan and Mayapan, Gates translation','https://sacred-texts.com/nam/maya/ybac/ybac10.htm','primary'),source('chichen','National Museum of the American Indian: Chichen Itza','https://maya.nmai.si.edu/gallery/chichen-itza'),source('ornaments','The Met: Feathered Serpent face ornaments','https://www.metmuseum.org/art/collection/search/722156')]
},
guanyin:{
 identity:'Guanyin is the Chinese name of Avalokiteshvara, the Buddhist bodhisattva of compassion. A bodhisattva is not simply a creator god or a divine conqueror.',
 worldview:['Compassion responds to the suffering and capacities of particular beings. The many forms of Avalokiteshvara express that responsiveness; their purpose is assistance on the path of liberation, not expansion of a divine empire.'],
 stories:[story('The Universal Door','Chapter 25 of the Lotus Sutra describes Guanyin responding to beings facing dangers and distress. Its teachings connect calling upon the bodhisattva with relief from fear and harmful states of mind. The chapter is a scriptural account of compassionate response rather than one episode in a warrior’s career.','lotus'),story('Hands that see suffering','Chinese thousand-armed images place eyes in the hands. A Smithsonian painting explains the combination as perceiving suffering and offering many means of help. An image of Amitabha above Guanyin identifies another important devotional relationship.','arms')],
 relationships:[relation('Amitabha','The Buddha associated with Guanyin in many devotional images.'),relation('Beings in distress','The recipients of compassionate attention, not subjects to be conquered.')],
 symbols:[symbol('Eyes in the palms','Perception joined with the capacity to respond.'),symbol('Many arms','Multiple means of assistance.'),symbol('Lotus seat','A familiar sacred setting in the cited Buddhist image.')],
 practice:['Devotion includes recitation, offerings and rituals centered on compassionate aid. A dated Ming painting was made for a multiday ritual and includes a broad retinue.'],
 variants:['Forms vary across Chinese and other Buddhist traditions, including gender presentation and the number of heads and arms. Guanyin should not be mislabeled as a Shinto kami or merged with every Asian goddess of mercy.'],adaptation,
 sources:[source('lotus','City of Ten Thousand Buddhas: Lotus Sutra, chapter 25','https://www.cttbusa.org/dfs25/dfs25.asp','primary'),source('arms','National Museum of Asian Art: Thousand-armed Guanyin','https://asia.si.edu/explore-art-culture/collections/search/edanmdm%3Afsg_F1917.110/'),source('ritual','The Met: Zhou Bangzhang’s Guanyin','https://www.metmuseum.org/art/collection/search/811172')]
},
tangaroa:{
 identity:'Tangaroa is an atua of the sea in Māori traditions. This entry concerns Māori accounts and does not combine every Polynesian figure with a related name.',
 worldview:['The sea sustains life and can destroy it. Te Ara stresses that “god of the sea” only partly conveys Tangaroa’s relationship to the ocean’s different energies and moods. Genealogy relates marine beings to one another and to human obligations.'],
 stories:[story('The descendants separate','One genealogy makes Tangaroa a child of Ranginui and Papatūānuku. Through Punga come Ikatere and Tūtewehiwehi: one line goes to the sea and becomes fish, while the other moves inland and becomes reptiles. Differences among living beings are expressed through related descent.','fish'),story('Carving comes from the sea','Ruatepupuke enters Tangaroa’s underwater house to recover his captured son. He sets the house alight and brings carved posts back to the human world. The account explains the origin of carving while exposing the violence and obligations within relations between people and the sea.','carving')],
 relationships:[relation('Ranginui and Papatūānuku','His parents in a widely known genealogy, but not in every account.'),relation('Punga','Ancestor of marine and reptile descendants.'),relation('Ruatepupuke','The figure who brings carving from the underwater house.')],
 symbols:[symbol('Fish','Living descendants within a sacred genealogy.'),symbol('Carved posts','Objects brought from the underwater dwelling.'),symbol('First catch','An offering returned to the sea in documented fishing custom.')],
 practice:['Fishing traditions include karakia and giving back the first fish. These practices express a relationship with Tangaroa, not simply ownership of marine resources.'],
 variants:['Some traditions make Tangaroa Papatūānuku’s husband and Ranginui’s rival. Genealogies vary by community; this difference must remain visible.'],adaptation,
 sources:[source('fish','Te Ara: Tangaroa and the genealogy of fish','https://teara.govt.nz/en/te-hi-ika-maori-fishing/page-1','scholarship'),source('carving','Te Ara: Tangaroa, the sea','https://teara.govt.nz/en/tangaroa-the-sea','scholarship'),source('practice','Te Ara: Maori fishing','https://teara.govt.nz/en/te-hi-ika-maori-fishing','scholarship')]
},
itzamna:{
 identity:'Itzamna, often rendered Itzamnaaj in discussions of Classic Maya art, is an elderly celestial deity. The precise reading and continuity of the ancient name remain subjects of scholarship.',
 worldview:['Maya gods have histories, transformations and relationships recorded through images and inscriptions. A colonial name cannot always be attached to an earlier figure with complete certainty, and visual identification is not the same as a recovered spoken myth.'],
 stories:[story('The great celestial bird','A Maya whistling vessel presents a majestic supernatural bird associated with the elderly celestial god. Museum scholarship relates this bird to narratives of a confrontation with a young solar figure. Its role can include adversary, manifestation or companion; those distinctions should not be collapsed.','bird'),story('Divine ancestry at Copan','The Rosalila temple at Copan places the dynastic founder K’inich Yax K’uk’ Mo’ in a composition with the celestial bird deity. The setting connects rulership, sacred ancestry and architectural memory. It is an attested image with a specific civic context, not an invented adventure attributed to Itzamna.','copan')],
 relationships:[relation('The Principal Bird Deity','Associated with the elderly celestial god, though the exact relationship varies by interpretation.'),relation('K’inich Yax K’uk’ Mo’','Copan’s dynastic founder, placed in a sacred composition with the bird deity.')],
 symbols:[symbol('Elderly face','A principal identifying feature of the celestial figure.'),symbol('Great bird','An important avian manifestation or companion.'),symbol('Name glyph','Evidence for ancient naming, whose reading is not completely settled.')],
 practice:['Royal monuments and vessels connect divine histories with ceremonies and authority. They preserve evidence that should be read alongside inscriptions rather than through a modern universal pantheon chart.'],
 variants:['Classic Maya evidence spans many cities and centuries. Colonial Yukatek Itzamna and every earlier avian image are not automatically one unchanged character.'],adaptation,
 sources:[source('bird','The Met: Maya whistling vessel and Principal Bird Deity','https://www.metmuseum.org/art/collection/search/310542'),source('copan','National Museum of the American Indian: Copan','https://maya.nmai.si.edu/gallery/copan'),source('name','The Met: Lives of the Gods, visiting guide','https://www.metmuseum.org/fr/exhibitions/gods-divinity-maya-art/visiting-guide')]
},
inti:{
 identity:'Inti is the sun in Inka religious tradition, closely associated with dynastic ancestry and the seasonal conditions of Andean life.',
 worldview:['Solar ancestry links a ruling lineage with the ordering of a homeland. The sun’s yearly cycle also connects public ceremony with agricultural expectations, while local communities maintain their own forms of celebration.'],
 stories:[story('The children sent from the lake','In the origin account presented by the National Museum of the American Indian, Inti sends Manco Capac and Mama Ocllo from Lake Titicaca to establish an ordered human community. Their journey ends at Cusco, and Manco Capac becomes the first Inka ruler.','children'),story('The place where the staff sinks','A related version gives the pair a golden staff and instructs them to settle where it sinks into the ground. The sign identifies Cusco. This is a detail of the same founding cycle, not a wholly separate creation of all Andean peoples.','staff')],
 relationships:[relation('Manco Capac and Mama Ocllo','Children sent on the founding journey.'),relation('Tiqzi Wiracocha','Creator of Inti in the Smithsonian’s presentation of Andean creation.'),relation('The Inka dynasty','Claims solar descent in its origin narrative.')],
 symbols:[symbol('Sun','The visible source of the deity’s identity.'),symbol('Golden staff','A sign that identifies the place of settlement.'),symbol('Solstice','A seasonal point around which celebrations of the sun are organized.')],
 practice:['Inti Raymi honors the sun around the southern winter solstice. Celebrations include processions, dance and feasting, with differences among Andean communities.'],
 variants:['Modern Cusco’s large public presentation should not be mistaken for an unchanged transcript of every Inka-era rite. Inti is distinct from the creator Wiracocha and from the many local sacred powers of the Andes.'],adaptation,
 sources:[source('children','National Museum of the American Indian: Children of the Sun','https://americanindian.si.edu/inkaroad/ancestors/creationstories/children-sun.html'),source('staff','National Museum of the American Indian: Inka activity guide','https://americanindian.si.edu/sites/1/files/pdf/education/Inka-activity-guide.pdf'),source('festival','National Museum of the American Indian: Reciprocity and Inti Raymi','https://americanindian.si.edu/nk360/inka-water/reciprocity/reciprocity'),source('creator','National Museum of the American Indian: Tiqzi Wiracocha','https://americanindian.si.edu/inkaroad/ancestors/creationstories/the-creator.html')]
},
huitzilopochtli:{
 identity:'Huitzilopochtli is the Mexica patron deity strongly associated with warfare, the sun and the people’s migration traditions.',
 worldview:['His stories link collective identity to movement, conflict and a sacred center at Tenochtitlan. They must be read within Mexica religion rather than assigned indiscriminately to all peoples labeled “Aztec.”'],
 stories:[story('Birth at Coatepec','When Coatlicue becomes pregnant, Coyolxauhqui and her brothers turn against her. Huitzilopochtli is born and defeats them. The dismembered Coyolxauhqui stone at the foot of his sanctuary’s stairway recalls this conflict and places the sacred mountain narrative within the city’s ceremonial architecture.','birth'),story('The patron on the migration','Recorded migration traditions describe Huitzilopochtli accompanying the people from Aztlan, his sacred image carried by priestly bearers. Along the journey he gives them the name Mexica. The account expresses a people’s relationship with its patron, not an independently verified itinerary.','migration')],
 relationships:[relation('Coatlicue','His mother in the Coatepec narrative.'),relation('Coyolxauhqui','His sister and opponent in that account.'),relation('Tlaloc','Occupies the other principal sanctuary on the Templo Mayor.')],
 symbols:[symbol('Hummingbird','Part of the meaning and imagery of his name.'),symbol('Coatepec','The sacred mountain embodied by his temple setting.'),symbol('Carried divine image','The patron’s presence during migration.')],
 practice:['The Templo Mayor placed his cult at the political and religious center of Tenochtitlan. Warfare and offerings belonged to this historical setting; they should neither be erased nor sensationalized into the entire religion.'],
 variants:['Colonial accounts preserve indigenous traditions through changing political and religious circumstances. Solar associations do not make Huitzilopochtli identical with every solar deity, including Tonatiuh.'],adaptation,
 sources:[source('birth','INAH: Templo Mayor and the Coatepec narrative','https://inah.gob.mx/zonas/zona-arqueologica-templo-mayor'),source('migration','Coe and Koontz: Mexico, hosted by INAH','https://deas.inah.gob.mx/pdf/biblioteca/repositorio/repositorio%2821040%29-4563.pdf','scholarship'),source('solar','INAH: Solar and Huitzilopochtli imagery','https://lugares.inah.gob.mx/en/node/5011')]
},
perun:{
 identity:'Perun is a Slavic thunder deity especially well attested in accounts of pre-Christian Kyivan Rus, where he also guarded warrior oaths and princely authority.',
 worldview:['The strongest surviving written evidence concerns public worship and sworn agreements, not a complete cycle of divine adventures. Most written witnesses were Christian authors describing earlier or rival practices, so their perspectives require attention.'],
 stories:[story('The oath with Byzantium','Chronicle accounts of agreements with Byzantium distinguish people swearing by Perun from Christian oath-takers. The divine name guarantees a binding public promise. This provides firmer evidence for his social role than many elaborate modern reconstructions of his family.','perun','conversion'),story('The idol cast into the river','The chronicle describes Volodymyr establishing a wooden image with a silver head and golden moustache, then ordering its removal after his adoption of Christianity. Its casting into the Dnipro dramatizes a change of state religion. The narrative is an account about worshippers and an image, not Perun’s own death.','perun','chronicle')],
 relationships:[relation('Volodymyr','The prince connected with both establishment and destruction of the Kyiv image.'),relation('Warriors and oath-takers','Groups whose obligations were placed under his name.'),relation('Saint Elijah','Later Christian folk associations absorbed some thunder-related functions; the figures are not identical.')],
 symbols:[symbol('Thunder and lightning','His best-established natural associations.'),symbol('Silver head and golden moustache','Specific attributes of the chronicle’s Kyiv idol.')],
 practice:['The surviving sources attest oaths and public cult. They do not provide enough reliable detail to reconstruct a complete ceremony for this game.'],
 variants:['A detailed Perun–Veles combat cycle is a scholarly reconstruction from comparative evidence, not one fully preserved ancient Slavic scripture. No unsupported second adventure or universal family tree is supplied here.'],adaptation,
 sources:[source('perun','Canadian Institute of Ukrainian Studies: Perun','https://www.encyclopediaofukraine.com/display.asp?linkpath=pages%5CP%5CE%5CPerun.htm','scholarship'),source('conversion','Encyclopedia of Ukraine: Christianization','https://www.encyclopediaofukraine.com/display.asp?linkpath=pages%5CC%5CH%5CChristianizationofUkraine.htm','scholarship'),source('chronicle','Cambridge: Treaties and early Slavic religion','https://www.cambridge.org/core/books/abs/beginnings-of-russian-history/treaties-with-the-greeks-and-russian-heathenism/637AE366E2D9825D50E48FF3CD5A3780','scholarship')]
},
};
