// Source-linked reference data. Codex inclusion does not create a playable unit.
// Internal faction keys are retained for save compatibility, not as lore names.
const bible = (chapter, version = 'KJV') => `https://www.biblegateway.com/passage/?search=${encodeURIComponent(chapter)}&version=${version}`;
const hymns1 = 'https://www.theoi.com/Text/HomericHymns1.html';
const hymns2 = 'https://www.theoi.com/Text/HomericHymns2.html';
const hymns3 = 'https://www.theoi.com/Text/HomericHymns3.html';
const theogony = 'https://www.theoi.com/Text/HesiodTheogony.html';
const gylfaginning = 'https://en.wikisource.org/wiki/The_Prose_Edda_(1916_translation_by_Arthur_Gilchrist_Brodeur)/Gylfaginning';
const youngerEdda = 'https://www.gutenberg.org/files/18947/18947-h/18947-h.htm';
const voluspa = 'https://en.wikisource.org/wiki/The_Poetic_Edda_(tr._Bellows)/Voluspo';
const museum = name => `https://egyptianmuseum.org/deities-${name}`;
const figure = (id, name, role, imagery, lore, sourceUrl, sourceLabel) => ({ id, name, role, imagery, lore, sourceUrl, sourceLabel });

export const MYTHOLOGY_VERSION = 1;
export const MYTHOLOGY_SCOPE = 'A source-linked reference codex. Lore entries are not a list of implemented playable units; game powers and faction alliances are original fiction.';

export const PANTHEONS = {
  gondor: {
    name: 'Radiant Covenant',
    tradition: 'Christianity',
    patron: 'God',
    note: 'Christianity is monotheistic. Jesus, human apostles, heavenly beings, and the Nephilim are distinct categories, not a pantheon of interchangeable gods.',
    figures: [
      figure('jesus', 'Jesus Christ', 'Christ; central figure of Christianity',
        'Broken bread, resurrection wounds, and the empty tomb; no physical portrait is prescribed here.',
        'Luke recounts the risen Jesus meeting his followers, sharing food, and commissioning their witness.',
        bible('Luke 24'), 'Luke 24:1–49 (KJV)'),
      figure('peter', 'Peter', 'One of the Twelve',
        'Keys, used as the passage’s metaphor.',
        'After Peter identifies Jesus as the Christ, Jesus speaks of the church and the keys of the kingdom.',
        bible('Matthew 16'), 'Matthew 16:13–19 (KJV)'),
      figure('andrew', 'Andrew', 'One of the Twelve',
        'Fishing net and the Galilean shore.',
        'Andrew and his brother Peter leave their fishing nets when Jesus calls them.',
        bible('Matthew 4'), 'Matthew 4:18–20 (KJV)'),
      figure('james-zebedee', 'James, son of Zebedee', 'One of the Twelve',
        'Fishing boat and mended nets.',
        'James leaves his father Zebedee and their boat to follow Jesus with his brother John.',
        bible('Matthew 4'), 'Matthew 4:21–22 (KJV)'),
      figure('john-zebedee', 'John, son of Zebedee', 'One of the Twelve',
        'Boat and nets beside his brother James.',
        'Matthew places John with James at their shared calling from Zebedee’s fishing boat.',
        bible('Matthew 4'), 'Matthew 4:21–22 (KJV)'),
      figure('philip', 'Philip', 'One of the Twelve',
        'A road and an invitation to come and see.',
        'After Jesus calls Philip, Philip invites Nathanael to meet him.',
        bible('John 1'), 'John 1:43–46 (KJV)'),
      figure('bartholomew', 'Bartholomew', 'One of the Twelve',
        'An inscribed name scroll is a game design motif; the list gives no appearance.',
        'Matthew names Bartholomew among the Twelve without supplying an individual biography in this passage.',
        bible('Matthew 10'), 'Matthew 10:2–4 (KJV)'),
      figure('thomas', 'Thomas', 'One of the Twelve',
        'An outstretched hand and the wounds of the risen Jesus.',
        'Thomas first asks for evidence of Jesus’s wounds, then encounters the risen Jesus and professes belief.',
        bible('John 20'), 'John 20:24–29 (KJV)'),
      figure('matthew', 'Matthew', 'One of the Twelve',
        'A tax booth; ledger and coins are scene-design motifs.',
        'Jesus calls Matthew from his tax-collection seat, and Matthew rises to follow him.',
        bible('Matthew 9'), 'Matthew 9:9 (KJV)'),
      figure('james-alphaeus', 'James, son of Alphaeus', 'One of the Twelve',
        'A named scroll is a design motif, not a scriptural attribute.',
        'Matthew identifies this apostle by his father Alphaeus, distinguishing him from James son of Zebedee.',
        bible('Matthew 10'), 'Matthew 10:2–3 (KJV)'),
      figure('thaddaeus', 'Thaddaeus', 'One of the Twelve',
        'A named scroll is a design motif; no appearance is given.',
        'The KJV apostle list names Lebbaeus, surnamed Thaddaeus; names and wording differ across lists and translations.',
        bible('Matthew 10'), 'Matthew 10:3 (KJV); compare Luke 6:16'),
      figure('simon-zealot', 'Simon the Zealot', 'One of the Twelve',
        'A named scroll is a design motif; the epithet does not prescribe weapons.',
        'Luke distinguishes this Simon with the epithet Zelotes while listing the Twelve.',
        bible('Luke 6'), 'Luke 6:13–16 (KJV)'),
      figure('judas-iscariot', 'Judas Iscariot', 'One of the Twelve; betrayer in the Gospel narrative',
        'Thirty silver pieces and the identifying kiss.',
        'Matthew relates Judas’s agreement for thirty silver pieces and his identification of Jesus at the arrest.',
        bible('Matthew 26'), 'Matthew 26:14–16, 47–50 (KJV)'),
      figure('michael', 'Michael', 'Heavenly commander',
        'Angelic host confronting a dragon; armor is an artistic interpretation.',
        'Revelation depicts Michael and his angels fighting the dragon and its angels.',
        bible('Revelation 12'), 'Revelation 12:7–9 (KJV); Jude 1:9 calls Michael an archangel'),
      figure('seraphim', 'Seraphim', 'Heavenly beings in Isaiah’s vision',
        'Six wings: two covering the face, two the feet, two for flight; altar coal.',
        'In Isaiah’s temple vision, seraphim praise God, and one touches Isaiah’s lips with a live coal.',
        bible('Isaiah 6'), 'Isaiah 6:1–7 (KJV)'),
      figure('nephilim', 'Nephilim', 'Enigmatic figures in Genesis',
        'No detailed anatomy is given; imposing silhouettes would be a game interpretation.',
        'Genesis names the Nephilim among ancient renowned figures; the term’s meaning and their relationship to the surrounding genealogy remain debated.',
        bible('Genesis 6', 'NET'), 'Genesis 6:1–4 (NET), especially the translation note on verse 4')
    ]
  },
  rohan: {
    name: 'Solar Dynasty',
    tradition: 'Ancient Egyptian religion',
    patron: 'Ra',
    note: 'Egyptian divine forms and relationships varied across places and periods; these entries describe selected attested traditions.',
    figures: [
      figure('ra', 'Ra', 'Solar and creator deity',
        'Sun and the solar barque.',
        'Ra travels through the night’s underworld journey before the sun rises again.',
        museum('ra'), 'Rosicrucian Egyptian Museum — Ra'),
      figure('isis', 'Isis', 'Goddess of magic and healing',
        'Throne-shaped headdress and protective wings.',
        'Isis restores Osiris and protects their son Horus in the Osirian cycle.',
        museum('isis'), 'Rosicrucian Egyptian Museum — Isis'),
      figure('osiris', 'Osiris', 'Ruler of the afterlife',
        'A figure wrapped in linen.',
        'After his death at Seth’s hands and restoration by Isis, Osiris rules the realm of the dead.',
        museum('osiris'), 'Rosicrucian Egyptian Museum — Osiris'),
      figure('horus', 'Horus', 'Falcon deity of kingship',
        'Falcon head and the double crown.',
        'Horus is associated with royal power and, as the son of Isis and Osiris, contests Seth.',
        museum('horus'), 'Rosicrucian Egyptian Museum — Horus'),
      figure('anubis', 'Anubis', 'Guardian of embalming and the dead',
        'Black jackal head and the weighing of the heart.',
        'Anubis oversees funerary protection and appears at the judgment balance beside the deceased.',
        museum('Anubis'), 'Rosicrucian Egyptian Museum — Anubis'),
      figure('thoth', 'Thoth', 'Deity of writing and knowledge',
        'Ibis or baboon form and a scribe’s record.',
        'Thoth is associated with the moon, writing, and recording the judgment of the dead.',
        museum('thoth'), 'Rosicrucian Egyptian Museum — Thoth'),
      figure('hathor', 'Hathor', 'Goddess of love, music, and celebration',
        'Mirror, music, and a festival boat.',
        'Hathor’s worship includes music and festivals, including her ceremonial journey from Dendera to Horus at Edfu.',
        museum('hathor'), 'Rosicrucian Egyptian Museum — Hathor'),
      figure('sekhmet', 'Sekhmet', 'Goddess of destructive power and healing',
        'Lion-headed woman with a solar disk.',
        'Sekhmet is associated both with warfare and plague and with protection and healing.',
        museum('sekhmet'), 'Rosicrucian Egyptian Museum — Sekhmet'),
      figure('bastet', 'Bastet', 'Protective feline goddess',
        'Cat or cat-headed woman.',
        'Bastet is associated with protection, health, and pleasure.',
        museum('Bastet'), 'Rosicrucian Egyptian Museum — Bastet'),
      figure('ptah', 'Ptah', 'Creator and patron of craftspeople',
        'Workshop and temple motifs express his craft association.',
        'Ptah is the Memphite creator deity and patron of craftspeople and architects.',
        museum('ptah'), 'Rosicrucian Egyptian Museum — Ptah'),
      figure('seth', 'Seth', 'Deity associated with desert and storms',
        'The distinctive Seth animal and its forked tail.',
        'Seth opposes Osiris in one cycle yet also defends Ra against the serpent Apep.',
        museum('seth'), 'Rosicrucian Egyptian Museum — Seth'),
      figure('maat', 'Ma’at', 'Divine order, truth, and justice',
        'Ostrich feather and the judgment balance.',
        'Ma’at embodies order and truth; her feather is weighed against the deceased’s heart.',
        museum('Maat'), 'Rosicrucian Egyptian Museum — Ma’at')
    ]
  },
  elves: {
    name: 'Aegis League',
    tradition: 'Ancient Greek religion and literature',
    patron: 'Athena',
    note: 'These are selected literary traditions, not a single fixed Greek canon.',
    figures: [
      figure('athena', 'Athena', 'Goddess of counsel and war',
        'Arms of war.',
        'Hesiod recounts Athena’s birth from Zeus and associates her with wise understanding and battle.',
        theogony, 'Hesiod, Theogony 886–900, 924–929; Evelyn-White translation'),
      figure('zeus', 'Zeus', 'Ruler of the Olympian gods',
        'Lightning and thunderbolt.',
        'The Cyclopes provide Zeus’s thunderbolt, and the gods call on him to rule after the Titan conflict.',
        theogony, 'Hesiod, Theogony 139–146, 501–506, 881–885; Evelyn-White translation'),
      figure('hera', 'Hera', 'Queen among the gods',
        'Golden throne.',
        'The hymn honors Hera as Zeus’s wife and a queen revered by the gods.',
        hymns3, 'Homeric Hymn 12, To Hera; Evelyn-White translation'),
      figure('poseidon', 'Poseidon', 'Deity of sea and earthquakes',
        'Horses, ships, and waves.',
        'The hymn invokes Poseidon as earth-shaker, tamer of horses, and protector of voyagers.',
        hymns3, 'Homeric Hymn 22, To Poseidon; Evelyn-White translation'),
      figure('demeter', 'Demeter', 'Goddess of grain and cultivation',
        'Grain and searching torches.',
        'Demeter withholds the earth’s crops while grieving the abduction of her daughter Persephone.',
        hymns1, 'Homeric Hymn 2, To Demeter, 40–50 and 301–333; Evelyn-White translation'),
      figure('apollo', 'Apollo', 'Deity of archery, song, and prophecy',
        'Bow, lyre, and sanctuary.',
        'The Apollo hymn recounts his Delian birth and the establishment of his oracle at Delphi.',
        hymns1, 'Homeric Hymn 3, To Apollo; Evelyn-White translation'),
      figure('artemis', 'Artemis', 'Goddess of the hunt',
        'Bow, hounds, and mountains.',
        'The hymn portrays Artemis hunting and later leading a dance at Apollo’s house.',
        hymns3, 'Homeric Hymn 27, To Artemis; Evelyn-White translation'),
      figure('ares', 'Ares', 'God associated with war',
        'Helmet, bronze armor, shield, and spear.',
        'His hymn seeks courage while also asking him to restrain destructive fury.',
        hymns3, 'Homeric Hymn 8, To Ares; Evelyn-White translation'),
      figure('aphrodite', 'Aphrodite', 'Goddess of desire',
        'Sea foam, golden jewelry, and a crown.',
        'One hymn describes Aphrodite arriving from the sea and being adorned by the Seasons.',
        hymns3, 'Homeric Hymn 6, To Aphrodite; Evelyn-White translation'),
      figure('hephaestus', 'Hephaestus', 'Divine craftworker',
        'A workshop expresses his craft association.',
        'Hesiod describes Hephaestus as Hera’s son and a craftsman surpassing the other heavenly gods.',
        theogony, 'Hesiod, Theogony 924–929; Evelyn-White translation'),
      figure('hermes', 'Hermes', 'Divine messenger and ingenious trickster',
        'Tortoise-shell lyre and cattle tracks.',
        'The Hermes hymn recounts his invention of the lyre and theft of Apollo’s cattle.',
        hymns2, 'Homeric Hymn 4, To Hermes; Evelyn-White translation'),
      figure('dionysus', 'Dionysus', 'God associated with wine',
        'Vines, ivy, and a ship.',
        'When pirates seize Dionysus, miraculous vines and transformations reveal his divinity.',
        hymns3, 'Homeric Hymn 7, To Dionysus; Evelyn-White translation'),
      figure('hades', 'Hades', 'Ruler of the dead',
        'Chariot and a shadowed underworld court.',
        'The Demeter hymn depicts Hades carrying Persephone into his realm and later permitting her return.',
        hymns1, 'Homeric Hymn 2, To Demeter, 1–39 and 347–386; Evelyn-White translation'),
      figure('persephone', 'Persephone', 'Daughter of Demeter; underworld queen',
        'Meadow flowers and pomegranate seed.',
        'After eating pomegranate in the underworld, Persephone divides her year between that realm and her mother.',
        hymns1, 'Homeric Hymn 2, To Demeter, 370–403; Evelyn-White translation')
    ]
  },
  mordor: {
    name: 'Stormforged',
    tradition: 'Norse mythology',
    patron: 'Thor',
    note: 'The Eddas preserve medieval Icelandic accounts of earlier traditions; spellings and details vary among texts.',
    figures: [
      figure('thor', 'Thor', 'Powerful defender among the gods',
        'Mjölnir, iron gloves, and a goat-drawn chariot.',
        'Snorri gives Thor a mighty hammer and strength-enhancing belt.',
        gylfaginning, 'Snorri, Gylfaginning XXI; Brodeur translation'),
      figure('odin', 'Odin', 'Ruler and seeker of knowledge',
        'Ravens Huginn and Muninn.',
        'Odin’s ravens range across the world and return with what they have seen and heard.',
        youngerEdda, 'Snorri, Gylfaginning, the ravens of Odin; Anderson translation'),
      figure('loki', 'Loki', 'Cunning, disruptive figure among the gods',
        'Disguise and mistletoe.',
        'Disguised, Loki learns from Frigg that mistletoe was excluded from the oaths protecting Baldr.',
        youngerEdda, 'Snorri, Gylfaginning, The Death of Balder; Anderson translation'),
      figure('freyja', 'Freyja', 'Vanir goddess',
        'A cat-drawn chariot.',
        'Freyja receives half of the battle-slain at Fólkvangr.',
        gylfaginning, 'Snorri, Gylfaginning XXIV; Brodeur translation'),
      figure('freyr', 'Freyr', 'Vanir deity of prosperity',
        'Rain, sunlight, and crops.',
        'Freyr governs rain and sunshine and is invoked for harvests and peace.',
        gylfaginning, 'Snorri, Gylfaginning XXIV; Brodeur translation'),
      figure('tyr', 'Týr', 'God of courage',
        'The hand pledged to Fenrir.',
        'Týr loses his hand when the gods bind Fenrir.',
        gylfaginning, 'Snorri, Gylfaginning XXV and XXXIV; Brodeur translation'),
      figure('heimdall', 'Heimdall', 'Watchman of the gods',
        'Gjallarhorn and the bridge Bifröst.',
        'Heimdall guards the bridge with exceptionally keen sight and hearing.',
        gylfaginning, 'Snorri, Gylfaginning XXVII; Brodeur translation'),
      figure('baldr', 'Baldr', 'God whose death portends catastrophe',
        'Mistletoe and mourning.',
        'Völuspá tells of Baldr’s death through mistletoe and foresees his return after the world’s renewal.',
        voluspa, 'Völuspá 31–34 and 62, with numbering varying by edition; Bellows translation'),
      figure('frigg', 'Frigg', 'Goddess and mother of Baldr',
        'Fensalir and the protective oath.',
        'Frigg seeks promises from things throughout the world not to harm her son Baldr.',
        youngerEdda, 'Snorri, Gylfaginning, The Death of Balder; Anderson translation'),
      figure('hel', 'Hel', 'Ruler of a realm of the dead',
        'Half-dark, half-flesh coloring.',
        'Snorri assigns Hel authority over those dying of sickness or age.',
        gylfaginning, 'Snorri, Gylfaginning XXXIV; Brodeur translation'),
      figure('fenrir', 'Fenrir', 'The bound wolf',
        'An immense wolf and the slender fetter Gleipnir.',
        'The gods bind Fenrir after ordinary restraints fail.',
        gylfaginning, 'Snorri, Gylfaginning XXXIV; Brodeur translation'),
      figure('jormungandr', 'Jörmungandr', 'The Midgard serpent',
        'An ocean-encircling serpent biting its tail.',
        'The serpent grows around the inhabited world after Odin casts it into the sea.',
        gylfaginning, 'Snorri, Gylfaginning XXXIV; Brodeur translation')
    ]
  }
};
