const VERSION="pregenesis-web-31fa49893a61b8";
const ASSETS=["./index.html","./app.js","./art-direction.js","./assets/app-icon.svg","./assets/brand/bem-fan-dead.webp","./assets/brand/bem-fan-lit.webp","./assets/brand/bem-glow.webp","./assets/brand/bem-ident.mp3","./assets/emblems/athena.svg","./assets/emblems/michael.svg","./assets/emblems/moses.svg","./assets/emblems/ra.svg","./assets/emblems/thor.svg","./assets/figures/portraits/athena.webp","./assets/figures/portraits/michael.webp","./assets/figures/portraits/moses.webp","./assets/figures/portraits/ra.webp","./assets/figures/portraits/thor.webp","./assets/fonts/LICENSE-PreGenesis.txt","./assets/fonts/PreGenesis-Display-Medium.woff2","./assets/fonts/PreGenesis-Display.woff2","./assets/fonts/PreGenesis-Text-Bold.woff2","./assets/fonts/PreGenesis-Text-Regular.woff2","./assets/fonts/fonts.css","./assets/icons.svg","./city-planning.js","./engine.js","./faction-lore.js","./faction-traits.js","./factions.js","./hud.css","./lore-biblical.js","./lore-classical.js","./lore-world.js","./manifest.webmanifest","./multiplayer-client.js","./mythic-miniatures.js","./mythology.js","./offline.js","./preferences.js","./save-validation.js","./tokens.css","./ui/actions.js","./ui/audio.js","./ui/champions.js","./ui/codex.js","./ui/context.js","./ui/dialogs.js","./ui/game.js","./ui/hud.js","./ui/icons.js","./ui/ident.js","./ui/input.js","./ui/lobby.js","./ui/markup.js","./ui/overlay.js","./ui/portraits.js","./ui/reveal.js","./ui/settings.js","./ui/storage.js","./ui/text.js","./ui/title.js","./vendor/three.core.js","./vendor/three.module.js","./world.js","./offline.js?release=0.11.0"];
const PREFIXES=["pregenesis-web-","crowns-web-"];
// A release installs atomically and waits until the player presses Update.
self.addEventListener('install',event=>event.waitUntil(caches.open(VERSION).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')event.waitUntil(self.skipWaiting());});
// Old releases of this game are removed; other caches on the origin are left alone.
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==VERSION&&PREFIXES.some(p=>k.startsWith(p))).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.origin!==self.location.origin||url.pathname.startsWith('/api/'))return;event.respondWith(caches.open(VERSION).then(async cache=>{if(event.request.mode==='navigate'){const page=await cache.match('./index.html');return page?(page.redirected?new Response(page.body,{status:page.status,statusText:page.statusText,headers:page.headers}):page):fetch(event.request);}return await cache.match(event.request)||fetch(event.request);}));});
